In [168]:
import pandas as pd
import pymupdf
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


print("Pandas version:", pd.__version__)
print("PyMuPDF imported successfully!")

Pandas version: 3.0.5
PyMuPDF imported successfully!

In [169]:
from pathlib import Path

pdf_path=Path(r'E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf')

print('PDF exists:',pdf_path.exists())
print('PDF path:',pdf_path)

PDF exists: True
PDF path: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf

In [170]:
doc=pymupdf.open(pdf_path)

print('PDF opened successfully')
print('Number_of_pages:',len(doc))

PDF opened successfully
Number_of_pages: 41

In [171]:
page=doc[0]
text=page.get_text('text')
print(text)

www.vedantu.com
1



Class 9 Maths Sample Paper – Set 1
Max. Marks: 80                                                                                   Time Allowed: 3 hours

General Instructions:
1. This Question Paper has 5 Sections A-E.
2. Section A has 20 MCQs carrying 1 mark each.
3. Section B has 5 questions carrying 02 marks each.
4. Section C has 6 questions carrying 03 marks each.
5. Section D has 4 questions carrying 05 marks each.
6. Section E has 3 case based integrated units of assessment carrying 04 marks each.
7. All Questions are compulsory. However, an internal choice in 2 Qs of 5 marks, 2 Qs of 3
marks and 2 Questions of 2 marks has been provided. An internal choice has been provided
in the 2 marks questions of Section E.
8. Draw neat figures wherever required. Take π =22/7 wherever required if not stated.

In [172]:
with pymupdf.open(pdf_path) as doc:
    for page_number, page in enumerate(doc, start=1):
        text = page.get_text("text")
        print(f"Page {page_number}: {len(text)} characters")

Page 1: 884 characters
Page 2: 681 characters
Page 3: 587 characters
Page 4: 424 characters
Page 5: 386 characters
Page 6: 564 characters
Page 7: 1061 characters
Page 8: 287 characters
Page 9: 911 characters
Page 10: 598 characters
Page 11: 445 characters
Page 12: 513 characters
Page 13: 917 characters
Page 14: 817 characters
Page 15: 600 characters
Page 16: 990 characters
Page 17: 855 characters
Page 18: 831 characters
Page 19: 543 characters
Page 20: 536 characters
Page 21: 672 characters
Page 22: 765 characters
Page 23: 821 characters
Page 24: 989 characters
Page 25: 661 characters
Page 26: 700 characters
Page 27: 567 characters
Page 28: 654 characters
Page 29: 438 characters
Page 30: 442 characters
Page 31: 745 characters
Page 32: 843 characters
Page 33: 677 characters
Page 34: 642 characters
Page 35: 535 characters
Page 36: 716 characters
Page 37: 805 characters
Page 38: 672 characters
Page 39: 481 characters
Page 40: 842 characters
Page 41: 127 characters

In [173]:
from pathlib import Path
raw_folder = Path(r"E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw")
pdf_files = list(raw_folder.rglob("*.pdf"))
print("Total PDF files found:", len(pdf_files))

for pdf in pdf_files:
    print(pdf)

Total PDF files found: 36
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP-24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP -24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP -24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\science\Science-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\science\Science-SQP -24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\science\Science-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\social_science\SocialScience-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\social_science\SocialScience-SQP -24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\social_science\SocialScience-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper 2026-27 (Mock Paper 6).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper Set 3 for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper Set 4 (2026-27) – FREE PDF with Solutions.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 2) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Sample Paper Class 9 Maths 2026-27 _ Mock Paper 7 PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper 2026-27 Mock Test Set 6.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper 2026-27 _ Mock Paper 7 PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 4 (2026-27) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 5 (2026-27) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\Class 9 Science Sample Paper Set 3 Download FREE PDF for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper 2025-26 (Mock Paper 6).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper 2026-27 (Mock Paper 7).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper Set 1 FREE PDF for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf

In [174]:
all_pages = []

for pdf_path in pdf_files:
    with pymupdf.open(pdf_path) as doc:

        for page_number, page in enumerate(doc, start=1):
            text = page.get_text("text").strip()

            all_pages.append({
                "source_file": pdf_path.name,
                "source_path": str(pdf_path),
                "page_number": page_number,
                "text": text,
                "text_length": len(text)
            })

print("Total pages extracted:", len(all_pages))

Total pages extracted: 605

In [175]:
import shutil
tesseract_path=shutil.which("tesseract")
print("Tesseract path:",tesseract_path)

Tesseract path: None

In [176]:
import pytesseract
print('pytesseract installed succesfully')

pytesseract installed succesfully

In [177]:
import shutil
tesseract_path=shutil.which("tesseract")
print("Tesseract path:",tesseract_path)

Tesseract path: None

In [178]:
import pytesseract
pytesseract.pytesseract.tesseract_cmd= r"C:\Program Files\Tesseract-OCR\tesseract.exe"
print(pytesseract.get_tesseract_version())

5.5.0.20241111

In [179]:
for i, pdf in enumerate(pdf_files[:10]):
    print(i, pdf)

0 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP -23-24.pdf
1 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP-24-25.pdf
2 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP-25-26.pdf
3 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP -23-24.pdf
4 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP -24-25.pdf
5 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP-25-26.pdf
6 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP -23-24.pdf
7 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP -24-25.pdf
8 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP-25-26.pdf
9 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\science\Science-SQP -23-24.pdf

In [180]:
class9_pdfs = [
    pdf for pdf in pdf_files
    if "class9" in [part.lower() for part in pdf.parts]
]

print("Class 9 PDFs:", len(class9_pdfs))

for pdf in class9_pdfs:
    print(pdf)

Class 9 PDFs: 21
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper 2026-27 (Mock Paper 6).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper Set 3 for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper Set 4 (2026-27) – FREE PDF with Solutions.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 2) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Sample Paper Class 9 Maths 2026-27 _ Mock Paper 7 PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper 2026-27 Mock Test Set 6.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper 2026-27 _ Mock Paper 7 PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 4 (2026-27) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 5 (2026-27) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\Class 9 Science Sample Paper Set 3 Download FREE PDF for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper 2025-26 (Mock Paper 6).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper 2026-27 (Mock Paper 7).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper Set 1 FREE PDF for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf

In [181]:
from PIL import Image
import io
pdf_path = class9_pdfs[0]
doc = pymupdf.open(pdf_path)
page = doc[0]
pix = page.get_pixmap(dpi=200)

image = Image.open(io.BytesIO(pix.tobytes("png")))
ocr_text = pytesseract.image_to_string(image)
print(ocr_text[:2000])
doc.close()

\Wedanti

LIVE ONLINE TUTORING

CBSE Class 9 Subject Maths Sample Question Paper — Set 6

General Instructions

V There are 90 questions in total. All questions are compulsory.

V The paper is divided into Sections A, B, C, D, and E.
V Internal choice follows CBSE norms.

V Questions strictly follow the current CBSE syllabus.

V Include the total marks and time duration based on the questions.

SECTION A — Objective Type Questions

(Include NEW MCQs and Assertion-Reason questions)

1. Which of the following numbers cannot be represented as a terminating decimal?

(a) 3/5
(b) 2/7
(c)1/4
(d) %

2. The value of (81)°"“ is:
(a) 9

(b) 27

(c) 64

(d) 16

3. If ais a root of the equation x’ - 2x + 1= 0, then ais:
(a) only

(b) -lonly

(c) both land -1

(d)o

4. Which of the following is a binomial?
(a)x*

(b) x +2

(c) 4x

(d) x? +x+1

www.vedantu.com

In [182]:
all_extracted_pages=[]

for pdf_path in pdf_files:
      # Find class from folder name
    class_name = "class9" if "class9" in [part.lower() for part in pdf_path.parts] else "class10"

    # Find subject from folder name
    subject = pdf_path.parent.name

    print(f"Processing: {class_name} | {subject} | {pdf_path.name}")

    doc = pymupdf.open(pdf_path)

    for page_number, page in enumerate(doc, start=1):

        # First try normal PDF text extraction
        native_text = page.get_text("text").strip()

        # OCR only when native text is very little
        ocr_text = ""

        if len(native_text) < 150:

            pix = page.get_pixmap(dpi=200)

            image = Image.open(
                io.BytesIO(pix.tobytes("png"))
            )

            ocr_text = pytesseract.image_to_string(image).strip()

        # Choose the better available text
        final_text = native_text if len(native_text) >= 150 else ocr_text

        all_extracted_pages.append({
            "class": class_name,
            "subject": subject,
            "source_file": pdf_path.name,
            "page_number": page_number,
            "native_text": native_text,
            "ocr_text": ocr_text,
            "final_text": final_text
        })

    doc.close()

print("\nTotal pages processed:", len(all_extracted_pages))

Processing: class10 | computer_application | ComputerApplication-SQP -23-24.pdf
Processing: class10 | computer_application | ComputerApplication-SQP-24-25.pdf
Processing: class10 | computer_application | ComputerApplication-SQP-25-26.pdf
Processing: class10 | home_science | HomeScience-SQP -23-24.pdf
Processing: class10 | home_science | HomeScience-SQP -24-25.pdf
Processing: class10 | home_science | HomeScience-SQP-25-26.pdf
Processing: class10 | maths | MathsStandard-SQP -23-24.pdf
Processing: class10 | maths | MathsStandard-SQP -24-25.pdf
Processing: class10 | maths | MathsStandard-SQP-25-26.pdf
Processing: class10 | science | Science-SQP -23-24.pdf
Processing: class10 | science | Science-SQP -24-25.pdf
Processing: class10 | science | Science-SQP-25-26.pdf
Processing: class10 | social_science | SocialScience-SQP -23-24.pdf
Processing: class10 | social_science | SocialScience-SQP -24-25.pdf
Processing: class10 | social_science | SocialScience-SQP-25-26.pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Paper 2026-27 (Mock Paper 6).pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Paper Set 3 for 2026-27.pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Paper Set 4 (2026-27) – FREE PDF with Solutions.pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Question Paper (Set 2) 2026-27 FREE PDF.pdf
Processing: class9 | maths | CBSE Sample Paper Class 9 Maths 2026-27 _ Mock Paper 7 PDF.pdf
Processing: class9 | maths | Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper 2026-27 Mock Test Set 6.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper 2026-27 _ Mock Paper 7 PDF.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper Set 4 (2026-27) - FREE PDF Download.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper Set 5 (2026-27) - FREE PDF Download.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
Processing: class9 | science | Class 9 Science Sample Paper Set 3 Download FREE PDF for 2026-27.pdf
Processing: class9 | social_science | CBSE Class 9 Social Science Sample Paper 2025-26 (Mock Paper 6).pdf
Processing: class9 | social_science | CBSE Class 9 Social Science Sample Paper 2026-27 (Mock Paper 7).pdf
Processing: class9 | social_science | CBSE Class 9 Social Science Sample Paper Set 1 FREE PDF for 2026-27.pdf
Processing: class9 | social_science | CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
Processing: class9 | social_science | Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
Processing: class9 | social_science | Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
Processing: class9 | social_science | Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf

Total pages processed: 605

In [183]:
df_pages = pd.DataFrame(all_extracted_pages)

print("Total page rows:", len(df_pages))
print("Total PDFs:", df_pages["source_file"].nunique())

print("\nClass-wise pages:")
print(df_pages["class"].value_counts())

print("\nSubject-wise pages:")
print(df_pages["subject"].value_counts())

Total page rows: 605
Total PDFs: 36

Class-wise pages:
class
class9     466
class10    139
Name: count, dtype: int64

Subject-wise pages:
subject
maths                   195
science                 186
social_science          186
computer_application     19
home_science             19
Name: count, dtype: int64

In [184]:
print("Pages that used OCR:", (df_pages["ocr_text"] != "").sum())
print("Pages with no final text:", (df_pages["final_text"].str.strip() == "").sum())

Pages that used OCR: 14
Pages with no final text: 0

In [185]:
import re
import pandas as pd

question_rows = []

for (class_name, subject, source_file), group in df_pages.groupby(
    ["class", "subject", "source_file"]
):
    
    group = group.sort_values("page_number")
    full_text = "\n".join(group["final_text"].fillna(""))

    # Remove text before the first section
    section_match = re.search(
        r"\bSECTION\s*[-–]?\s*[A-E]\b",
        full_text,
        flags=re.IGNORECASE
    )

    if section_match:
        full_text = full_text[section_match.start():]

    # Find numbered questions: 1. / 1) / 2. / 2)
    pattern = r"(?m)^\s*(\d{1,3})[\.\)]\s+(.*?)(?=^\s*\d{1,3}[\.\)]\s+|\Z)"

    matches = re.finditer(
        pattern,
        full_text,
        flags=re.MULTILINE | re.DOTALL
    )

    for match in matches:
        question_number = int(match.group(1))
        question_text = re.sub(r"\s+", " ", match.group(2)).strip()

        # Ignore very short accidental matches
        if len(question_text) < 20:
            continue

        session_match = re.search(r"(20\d{2}-\d{2})", source_file)
        session = session_match.group(1) if session_match else "Unknown"

        question_rows.append({
            "question_id": len(question_rows) + 1,
            "class": class_name,
            "subject": subject,
            "session": session,
            "source_file": source_file,
            "question_number": question_number,
            "question_text": question_text,
            "answer": ""
        })

question_df = pd.DataFrame(question_rows)

print("Total questions extracted:", len(question_df))
display(question_df.head(10))

Total questions extracted: 1891

,question_id,class,subject,session,source_file,question_number,question_text,answer
0,1,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,Section B has 7 Short Answer (SA-I) type questions carrying 02 marks each.,
1,2,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Section C has 4 Short Answer (SA-II) type questions carrying 03 marks each.,
2,3,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,Section D has 1 Long Answer (LA) type question carrying 04 marks.,
3,4,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,7,Section E has 2 Source based /Case-based /Passage based Questions carrying 04 marks each. SECTION – A (All questions are compulsory),
4,5,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,1,The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell,
5,6,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,2,Which of the following is an example of social networking website? a. wikipedia.org b. Facebook.com c. cbse.gov.in d. ncert.nic.in,
6,7,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,3,M in HTML stands for: a. Modify b. Management c. Multiple d. Markup,
7,8,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic. a. News group b. Blog c. WWW d. e-Groups",
8,9,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Which of the following is not a valid value for the target attribute of <a> tag? a. _blank b. _self c. _top d. _bottom Page 2 of 5,
9,10,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,"link, vlink, alink are attributes of___________ tag. a. <body> b. <a> c. <html> d. <img>",

In [186]:
from pathlib import Path

processed_folder = raw_folder.parent / "processed"
processed_folder.mkdir(exist_ok=True)

print("Processed folder:", processed_folder)

Processed folder: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed

In [187]:
output_file = processed_folder / "question_dataset.csv"

question_df.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("Dataset saved:")
print(output_file)

Dataset saved:
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\question_dataset.csv

In [188]:
# Create a richer question-bank dataset from the extracted questions

question_bank = question_df.copy()

# Section
question_bank["section"] = ""

# Question type
question_bank["question_type"] = ""

# Options
question_bank["options"] = ""

# Marks
question_bank["marks"] = ""

# Topic - will be populated during subject-wise cleaning
question_bank["topic"] = ""

# Difficulty - will be assigned later
question_bank["difficulty"] = ""

# Diagram/image indicator
question_bank["has_diagram"] = False

# Answer is unavailable in the current raw question set
question_bank["correct_answer"] = ""

# Explanation is unavailable in the current raw question set
question_bank["answer_explanation"] = ""

print("Rows:", len(question_bank))
print("Columns:")
print(question_bank.columns.tolist())

display(question_bank.head(10))

Rows: 1891
Columns:
['question_id', 'class', 'subject', 'session', 'source_file', 'question_number', 'question_text', 'answer', 'section', 'question_type', 'options', 'marks', 'topic', 'difficulty', 'has_diagram', 'correct_answer', 'answer_explanation']

,question_id,class,subject,session,source_file,question_number,question_text,answer,section,question_type,options,marks,topic,difficulty,has_diagram,correct_answer,answer_explanation
0,1,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,Section B has 7 Short Answer (SA-I) type questions carrying 02 marks each.,,,,,,,,False,,
1,2,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Section C has 4 Short Answer (SA-II) type questions carrying 03 marks each.,,,,,,,,False,,
2,3,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,Section D has 1 Long Answer (LA) type question carrying 04 marks.,,,,,,,,False,,
3,4,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,7,Section E has 2 Source based /Case-based /Passage based Questions carrying 04 marks each. SECTION – A (All questions are compulsory),,,,,,,,False,,
4,5,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,1,The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell,,,,,,,,False,,
5,6,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,2,Which of the following is an example of social networking website? a. wikipedia.org b. Facebook.com c. cbse.gov.in d. ncert.nic.in,,,,,,,,False,,
6,7,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,3,M in HTML stands for: a. Modify b. Management c. Multiple d. Markup,,,,,,,,False,,
7,8,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic. a. News group b. Blog c. WWW d. e-Groups",,,,,,,,False,,
8,9,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Which of the following is not a valid value for the target attribute of <a> tag? a. _blank b. _self c. _top d. _bottom Page 2 of 5,,,,,,,,False,,
9,10,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,"link, vlink, alink are attributes of___________ tag. a. <body> b. <a> c. <html> d. <img>",,,,,,,,False,,

In [189]:
import re

def detect_question_type(text):
    text_lower = text.lower()

    if re.search(r"\(a\).*?\(b\).*?\(c\).*?\(d\)", text, re.DOTALL):
        return "MCQ"
    elif "assertion" in text_lower and "reason" in text_lower:
        return "Assertion-Reason"
    elif "case-based" in text_lower or "passage" in text_lower:
        return "Case-Based"
    else:
        return "Short/Long Answer"


def extract_options(text):
    matches = re.findall(
        r"\([a-dA-D]\)\s*(.*?)(?=\s*\([a-dA-D]\)|$)",
        text,
        re.DOTALL
    )

    return " | ".join(x.strip() for x in matches)


question_bank["question_type"] = question_bank["question_text"].apply(
    detect_question_type
)

question_bank["options"] = question_bank["question_text"].apply(
    extract_options
)

display(
    question_bank[
        ["question_id", "class", "subject",
         "question_number", "question_type", "options",
         "question_text"]
    ].head(10)
)

,question_id,class,subject,question_number,question_type,options,question_text
0,1,class10,computer_application,4,Short/Long Answer,,Section B has 7 Short Answer (SA-I) type questions carrying 02 marks each.
1,2,class10,computer_application,5,Short/Long Answer,,Section C has 4 Short Answer (SA-II) type questions carrying 03 marks each.
2,3,class10,computer_application,6,Short/Long Answer,,Section D has 1 Long Answer (LA) type question carrying 04 marks.
3,4,class10,computer_application,7,Case-Based,,Section E has 2 Source based /Case-based /Passage based Questions carrying 04 marks each. SECTION – A (All questions are compulsory)
4,5,class10,computer_application,1,Short/Long Answer,,The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell
5,6,class10,computer_application,2,Short/Long Answer,,Which of the following is an example of social networking website? a. wikipedia.org b. Facebook.com c. cbse.gov.in d. ncert.nic.in
6,7,class10,computer_application,3,Short/Long Answer,,M in HTML stands for: a. Modify b. Management c. Multiple d. Markup
7,8,class10,computer_application,4,Short/Long Answer,,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic. a. News group b. Blog c. WWW d. e-Groups"
8,9,class10,computer_application,5,Short/Long Answer,,Which of the following is not a valid value for the target attribute of <a> tag? a. _blank b. _self c. _top d. _bottom Page 2 of 5
9,10,class10,computer_application,6,Short/Long Answer,,"link, vlink, alink are attributes of___________ tag. a. <body> b. <a> c. <html> d. <img>"

In [190]:
final_file = processed_folder / "question_bank_enriched.csv"

question_bank.to_csv(
    final_file,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:")
print(final_file)

Saved:
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\question_bank_enriched.csv

In [191]:
df=pd.read_csv('E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\question_bank_enriched.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\vivek\AppData\Local\Temp\ipykernel_41040\1262069675.py:1: SyntaxWarning: invalid escape sequence '\C'
  df=pd.read_csv('E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\question_bank_enriched.csv')

,question_id,class,subject,session,source_file,question_number,question_text,answer,section,question_type,options,marks,topic,difficulty,has_diagram,correct_answer,answer_explanation
0,1,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,Section B has 7 Short Answer (SA-I) type questions carrying 02 marks each.,NaN,NaN,Short/Long Answer,NaN,NaN,NaN,NaN,False,NaN,NaN
1,2,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Section C has 4 Short Answer (SA-II) type questions carrying 03 marks each.,NaN,NaN,Short/Long Answer,NaN,NaN,NaN,NaN,False,NaN,NaN
2,3,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,Section D has 1 Long Answer (LA) type question carrying 04 marks.,NaN,NaN,Short/Long Answer,NaN,NaN,NaN,NaN,False,NaN,NaN
3,4,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,7,Section E has 2 Source based /Case-based /Passage based Questions carrying 04 marks each. SECTION – A (All questions are compulsory),NaN,NaN,Case-Based,NaN,NaN,NaN,NaN,False,NaN,NaN
4,5,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,1,The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell,NaN,NaN,Short/Long Answer,NaN,NaN,NaN,NaN,False,NaN,NaN

In [192]:
df.shape

(1891, 17)

In [193]:
df.describe()

,question_id,question_number,answer,section,marks,topic,difficulty,correct_answer,answer_explanation
count,1891.000000,1891.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,946.000000,19.283977,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,546.028998,23.530128,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,473.500000,7.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,946.000000,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1418.500000,29.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1891.000000,800.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [194]:
df.columns

Index(['question_id', 'class', 'subject', 'session', 'source_file',
       'question_number', 'question_text', 'answer', 'section',
       'question_type', 'options', 'marks', 'topic', 'difficulty',
       'has_diagram', 'correct_answer', 'answer_explanation'],
      dtype='str')

In [195]:
display(question_bank.head(10).T)

,0,1,2,3,4,5,6,7,8,9
question_id,1,2,3,4,5,6,7,8,9,10
class,class10,class10,class10,class10,class10,class10,class10,class10,class10,class10
subject,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application
session,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
source_file,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf
question_number,4,5,6,7,1,2,3,4,5,6
question_text,Section B has 7 Short Answer (SA-I) type questions carrying 02 marks each.,Section C has 4 Short Answer (SA-II) type questions carrying 03 marks each.,Section D has 1 Long Answer (LA) type question carrying 04 marks.,Section E has 2 Source based /Case-based /Passage based Questions carrying 04 marks each. SECTION – A (All questions are compulsory),The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell,Which of the following is an example of social networking website? a. wikipedia.org b. Facebook.com c. cbse.gov.in d. ncert.nic.in,M in HTML stands for: a. Modify b. Management c. Multiple d. Markup,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic. a. News group b. Blog c. WWW d. e-Groups",Which of the following is not a valid value for the target attribute of <a> tag? a. _blank b. _self c. _top d. _bottom Page 2 of 5,"link, vlink, alink are attributes of___________ tag. a. <body> b. <a> c. <html> d. <img>"
answer,,,,,,,,,,
section,,,,,,,,,,
question_type,Short/Long Answer,Short/Long Answer,Short/Long Answer,Case-Based,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer
options,,,,,,,,,,
marks,,,,,,,,,,
topic,,,,,,,,,,
difficulty,,,,,,,,,,
has_diagram,False,False,False,False,False,False,False,False,False,False
correct_answer,,,,,,,,,,
answer_explanation,,,,,,,,,,

In [196]:
clean_bank = question_bank[
    ~question_bank["question_text"].str.startswith("Section", na=False)
].copy()

print("Before cleaning:", len(question_bank))
print("After removing section text:", len(clean_bank))

display(clean_bank.head(10).T)

Before cleaning: 1891
After removing section text: 1827

,4,5,6,7,8,9,10,11,12,13
question_id,5,6,7,8,9,10,11,12,13,14
class,class10,class10,class10,class10,class10,class10,class10,class10,class10,class10
subject,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application
session,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
source_file,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf
question_number,1,2,3,4,5,6,7,8,9,10
question_text,The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell,Which of the following is an example of social networking website? a. wikipedia.org b. Facebook.com c. cbse.gov.in d. ncert.nic.in,M in HTML stands for: a. Modify b. Management c. Multiple d. Markup,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic. a. News group b. Blog c. WWW d. e-Groups",Which of the following is not a valid value for the target attribute of <a> tag? a. _blank b. _self c. _top d. _bottom Page 2 of 5,"link, vlink, alink are attributes of___________ tag. a. <body> b. <a> c. <html> d. <img>","The_______ attribute of <img> tag specifies an alternate text for an image, if the image cannot be displayed. a. alt b. text c. alternate d. msg",Which of the following tag can be used to draw a horizontal line in webpage? a. <line> b. <hrule> c. <hr> d. <rule>,"In HTML, <dl>, <dd> and <dt> tags are used to create: a. Description list b. Definition list c. Detail list d. Dynamic list","A software _________ is a legal instrument governing the use or redistribution of software. a. license b. law c. document d. piracy Questions No-11 & 12 are Assertion and Reason types. Each question consists of two statements, namely, Assertion (A) and Reason (R). Select the most suitable option..."
answer,,,,,,,,,,
section,,,,,,,,,,
question_type,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Assertion-Reason
options,,,,,,,,,,and Reason (R). Select the most suitable option considering the Assertion & Reason.
marks,,,,,,,,,,
topic,,,,,,,,,,
difficulty,,,,,,,,,,
has_diagram,False,False,False,False,False,False,False,False,False,False
correct_answer,,,,,,,,,,
answer_explanation,,,,,,,,,,

In [197]:
print("Empty questions:", clean_bank["question_text"].isna().sum())

print(
    "Very short questions:",
    (clean_bank["question_text"].fillna("").str.len() < 20).sum()
)

print(
    "Duplicate questions:",
    clean_bank.duplicated(
        subset=["class", "subject", "question_text"]
    ).sum()
)

Empty questions: 0
Very short questions: 0
Duplicate questions: 82

In [198]:
duplicates = clean_bank[
    clean_bank.duplicated(
        subset=["class", "subject", "question_text"],
        keep=False
    )
]

display(
    duplicates[
        ["class", "subject", "source_file", "question_text"]
    ].sort_values(["class", "subject", "question_text"]).head(20)
)

,class,subject,source_file,question_text
346,class10,social_science,SocialScience-SQP -24-25.pdf,"There is no overall choice in the question paper. However, an internal choice has been provided in few questions. Only one of the choices in such questions must be attempted."
384,class10,social_science,SocialScience-SQP-25-26.pdf,"There is no overall choice in the question paper. However, an internal choice has been provided in few questions. Only one of the choices in such questions must be attempted."
496,class9,maths,CBSE Class 9 Maths Sample Paper Set 3 for 2026-27.pdf,"All Questions are compulsory. However, an internal choice in 2 Qs of 5 marks, 2 Qs of 3 marks and 2 Questions of 2 marks has been provided. An internal choice has been provided in the 2 marks questions of Section E."
549,class9,maths,CBSE Class 9 Maths Sample Paper Set 4 (2026-27) – FREE PDF with Solutions.pdf,"All Questions are compulsory. However, an internal choice in 2 Qs of 5 marks, 2 Qs of 3 marks and 2 Questions of 2 marks has been provided. An internal choice has been provided in the 2 marks questions of Section E."
649,class9,maths,CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf,"All Questions are compulsory. However, an internal choice in 2 Qs of 5 marks, 2 Qs of 3 marks and 2 Questions of 2 marks has been provided. An internal choice has been provided in the 2 marks questions of Section E."
712,class9,maths,CBSE Class 9 Maths Sample Question Paper (Set 2) 2026-27 FREE PDF.pdf,"All Questions are compulsory. However, an internal choice in 2 Qs of 5 marks, 2 Qs of 3 marks and 2 Questions of 2 marks has been provided. An internal choice has been provided in the 2 marks questions of Section E."
844,class9,maths,Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf,"All Questions are compulsory. However, an internal choice in 2 Qs of 5 marks, 2 Qs of 3 marks and 2 Questions of 2 marks has been provided. An internal choice has been provided in the 2 marks questions of Section E."
497,class9,maths,CBSE Class 9 Maths Sample Paper Set 3 for 2026-27.pdf,Draw neat figures wherever required. Take π =22/7 wherever required if not stated. Q. No. Questions Marks Section A
550,class9,maths,CBSE Class 9 Maths Sample Paper Set 4 (2026-27) – FREE PDF with Solutions.pdf,Draw neat figures wherever required. Take π =22/7 wherever required if not stated. Q. No. Questions Marks Section A
845,class9,maths,Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf,Draw neat figures wherever required. Take π =22/7 wherever required if not stated. Q. No. Questions Marks Section A
650,class9,maths,CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf,Draw neat figures wherever required. Take π =22/7 wherever required if not stated. www.vedantu.com 2 Section A Q. No. Questions Marks
713,class9,maths,CBSE Class 9 Maths Sample Question Paper (Set 2) 2026-27 FREE PDF.pdf,Draw neat figures wherever required. Take π =22/7 wherever required if not stated. www.vedantu.com 2 Section A Q. No. Questions Marks
1294,class9,science,CBSE Class 9 Science Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf,"(A) Both (A) and (R) are true, and (R) is the correct explanation of (A). Explanation: Cotton being good absorber of water helps in absorbing the sweat, which on evaporation gives a cooling sensation in the body."
1374,class9,science,Class 9 Science Sample Paper Set 3 Download FREE PDF for 2026-27.pdf,"(A) Both (A) and (R) are true, and (R) is the correct explanation of (A). Explanation: Cotton being good absorber of water helps in absorbing the sweat, which on evaporation gives a cooling sensation in the body."
1297,class9,science,CBSE Class 9 Science Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf,"(A) Both (A) and (R) are true, and (R) is the correct explanation of (A). Explanation: During the disturbance in cellular metabolism lysosomes may burst and the enzymes digest their own cell. Therefore, lysosomes are also known as suicidal bags. Lysosomes are able to do this because they contain..."
1377,class9,science,Class 9 Science Sample Paper Set 3 Download FREE PDF for 2026-27.pdf,"(A) Both (A) and (R) are true, and (R) is the correct explanation of (A). Explanation: During the disturbance in cellular metabolism lysosomes may burst and the enzymes digest their own cell. Therefore, lysosomes are also known as suicidal bags. Lysosomes are able to do this because they contain..."
1279,class9,science,CBSE Class 9 Science Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf,(A) Pearl Explanation: Oysters are cultivated for obtaining pearls
1373,class9,science,Class 9 Science Sample Paper Set 3 Download FREE PDF for 2026-27.pdf,(A) Pearl Explanation: Oysters are cultivated for obtaining pearls
1074,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf,"(A) is correct Explanation: Valence electrons are the electrons found in the outermost layer of an atom. Since both Atom 1 and Atom 2 each have just one valence electron, they will have the same valency."
1155,class9,science,CBSE Class 9 Science Sample Paper Set 4 (2026-27) - FREE PDF Download.pdf,"(A) is correct Explanation: Valence electrons are the electrons found in the outermost layer of an atom. Since both Atom 1 and Atom 2 each have just one valence electron, they will have the same valency."

In [199]:
instruction_patterns = (
    "all questions",
    "there is no overall choice",
    "draw neat figures",
    "general instructions",
    "(a) both",
    "(a) is correct",
    "(a) pearl explanation"
)

clean_bank = clean_bank[
    ~clean_bank["question_text"]
    .fillna("")
    .str.lower()
    .str.startswith(instruction_patterns)
].copy()

print("Rows after removing obvious non-questions:", len(clean_bank))

Rows after removing obvious non-questions: 1796

In [200]:
print(
    "Duplicate questions:",
    clean_bank.duplicated(
        subset=["class", "subject", "question_text"]
    ).sum()
)

Duplicate questions: 70

In [201]:
duplicates = clean_bank[
    clean_bank.duplicated(
        subset=["class", "subject", "question_text"],
        keep=False
    )
]

display(
    duplicates[
        ["class", "subject", "source_file", "question_text"]
    ].head(10)
)

,class,subject,source_file,question_text
1035,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf,The pictures show the arrangement of electrons in the shells of different atoms. which two atoms have the same valency? (A) Atom 1 and Atom 2 (B) Atom 2 and Atom 3 (C) Atom 3 and Atom 4 (D) Atom 4 and Atom 1 1
1038,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf,"In a laboratory, while doing an experiment, carbon dioxide was taken in an enclosed cylinder and compressed by applying pressure and keeping a low temperature. Which state of matter we will obtain after completion of the above-given process? (A) Solid (B) Liquid (C) Gas (D) Both (A) and (B) 1"
1040,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf,Which of the following figures does not represent Bohr’s model of an atom correctly? 1 www.vedantu.com 4 (A) (i) and (ii) (B) (ii) and (iii) (C) (ii) and (iv) (D) (i) and (iv)
1043,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf,What would be the valency of an element that is chemically inactive? (A) 0 (B) 1 (C) 2 (D) 5 1
1044,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf,"A few substances are arranged in the increasing order of forces of attraction between their particles. Which one of the following represents a correct arrangement? (A) Water, air, wind (B) Air, sugar, oil (C) Oxygen, water, sugar (D) Salt, juice, air 1"
1045,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf,Contractile proteins are found in: (A) Bones (B) Blood (C) Muscles 1 www.vedantu.com 6 (D) Cartilage
1047,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf,Which of these is an alloy? (A) Silver (B) Copper (C) Bronze (D) Aluminium 1
1049,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf,The area below v-t graph is a measure of: a) Angular speed b) Displacement c) Angular acceleration d) Acceleration 1
1050,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf,"On converting 25°C, 38°C and 66°C to Kelvin scale, the correct sequence of temperatures will be: (A)298K,311K and 339K (B) 298K,300K and 338K (C) 273 K, 278 K and 543 K (D) 298 K, 310 K and 338 K 1 Assertion Based Questions Question No. 17 to 20 consist of two statements — Assertion (A) and Reas..."
1051,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf,"Assertion (A): When heat energy is supplied to the solid, it starts melting. Reason (R): Solid particles take up the heat and help in melting. 1"

In [202]:
duplicate_check = (
    duplicates
    .groupby(["source_file", "question_text"])
    .size()
    .reset_index(name="count")
)

display(
    duplicate_check[
        duplicate_check["count"] > 1
    ].head(10)
)

,source_file,question_text,count
105,CBSE Class 9 Science Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf,Which of one of the following nutrients is not available in fertilisers. a) Iron b) Potassium c) Nitrogen d) Phosphorou 1,2

In [203]:
clean_bank = clean_bank.drop_duplicates(
    subset=["class", "subject", "source_file", "question_text"],
    keep="first"
).copy()

print("Rows after removing exact duplicates:", len(clean_bank))

Rows after removing exact duplicates: 1795

In [204]:
print(clean_bank["session"].value_counts())

session
2026-27    991
Unknown    743
2025-26     61
Name: count, dtype: int64

In [205]:
import re

def get_session(filename):
    match = re.search(r"(20\d{2}-\d{2})", filename)
    
    if match:
        return match.group(1)
    
    match = re.search(r"(\d{2})-(\d{2})", filename)
    
    if match:
        return "20" + match.group(1) + "-" + match.group(2)
    
    return "Unknown"

clean_bank["session"] = clean_bank["source_file"].apply(get_session)

print(clean_bank["session"].value_counts())

session
2026-27    991
Unknown    358
2025-26    166
2024-25    141
2023-24    139
Name: count, dtype: int64

In [206]:
unknown_sessions = clean_bank[
    clean_bank["session"] == "Unknown"
]

display(
    unknown_sessions[
        ["class", "subject", "source_file"]
    ].drop_duplicates().head(30)
)

,class,subject,source_file
846,class9,maths,Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
1609,class9,social_science,CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
1666,class9,social_science,Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
1749,class9,social_science,Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
1820,class9,social_science,Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf

In [207]:
print(
    unknown_sessions["source_file"]
    .drop_duplicates()
    .to_string(index=False)
)

     Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
         Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
         Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
        Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf

In [208]:
for filename in unknown_sessions["source_file"].drop_duplicates():

    pdf_path = next(pdf for pdf in pdf_files if pdf.name == filename)

    doc = pymupdf.open(pdf_path)

    first_page_text = doc[0].get_text("text")

    print("\n" + "=" * 80)
    print(filename)
    print("-" * 80)
    print(first_page_text[:1500])

    doc.close()

================================================================================
Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class IX Maths Sample Paper – Set 5
Max. Marks: 80






Time Allowed: 3 hours
General Instructions:
1. This Question Paper has 5 Sections A-E.
2. Section A has 20 MCQs carrying 1 mark each.
3. Section B has 5 questions carrying 02 marks each.
4. Section C has 6 questions carrying 03 marks each.
5. Section D has 4 questions carrying 05 marks each.
6. Section E has 3 case based integrated units of assessment carrying 04 marks each.
7. All Questions are compulsory. However, an internal choice in 2 Qs of 5 marks, 2 Qs of 3
marks and 2 Questions of 2 marks has been provided. An internal choice has been provided in
the 2 marks questions of Section E.
8. Draw neat figures wherever required. Take π =22/7 wherever required if not stated.

Q.
No.
Questions
Marks
Section A
1.
If f is a differentiable function and
( )
0
f
x

= for all x in some interval, then
( )
f x is
1


================================================================================
CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class IX Social Science Sample Paper – Set 5
Max. Marks: 80                                                                                   Time Allowed: 3 hours

General Instructions:
i. Question paper comprises five Sections – A, B, C, D, and E. There are 37 questions in the
question paper. All questions are compulsory.
ii. Section A Questions 1 to 20 are MCQs of 1 mark each.
iii. Section B - Questions no. 21 to 24 are Very Short Answer Type Questions, carrying 2 marks
each. The answer to each question should not exceed 40 words.
iv. Section C - Questions no. 25 to Q.29 are Short Answer Type Questions, carrying 3 marks
each. The answer to each question should not exceed 60 words,
v. Section D - Questions no. 30 to 33 are Long Answer Type Questions, carrying 5 marks each.
Answer to each question should not exceed 120 words
vi. Section E - Questions no. from 34 to 36 are Case Based Questions with three sub-questions
and are of 4 marks each.
vii. Section F - Question no. 37 is Map-based, carrying 5 marks with two parts, 37a from
History (2 marks) and 37b from Geography (3 marks).




================================================================================
Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class 9 Social Science Sample Paper – Set 2
Max. Marks: 80                                                                                   Time Allowed: 3 hours

General Instructions:
Question paper comprises five Sections - A, B, C, D, and E. There are 37 questions in the
question paper. All questions are compulsory.
i.
Section A - Questions 1 to 20 are MCQs of 1 mark each.
ii.
Section B - Questions no. 21 to 24 are Very Short Answer Type Questions, carrying 2
marks each. The answer to each question should not exceed 40 words.
iii.
Section C – Questions no. 25 to Q.29 are Short Answer Type Questions, carrying 3
marks each. The answer to each question should not exceed 60 words,
iv.
Section D - Questions no. 30 to 33 are Long Answer Type Questions, carrying 5 marks
each. Answer to each question should not exceed 120 words
v.
Section E - Questions no. from 34 to 36 are Case Based Questions with three sub-
questions and are of 4 marks each.
vi.
Section F - Question no. 37 is Map-based, carrying 5 marks with two parts, 37a from
History (2 marks) and 37b from Geography (3 marks).
vii.
There is no overall choice in the question paper. However, an internal choice has been
provided in a few questions. Only one of the choices in such questions has to be
attempted.
viii.
In addition to this, separate instructions are given with each section and question,
wherever necessary.





================================================================================
Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class 9 Social Science Sample Paper – Set 4
Max. Marks: 80                                                                                   Time Allowed: 3 hours

General Instructions:
The question paper comprises five Sections - A, B, C, D, and E. There are 37 questions on
the question paper. All questions are compulsory.
i.
Section A - Questions 1 to 20 are MCQs of 1 mark each.
ii.
Section B - Questions no. 21 to 24 are Very Short Answer Type Questions, carrying 2
marks each. The answer to each question should not exceed 40 words.
iii.
Section C – Questions no. 25 to Q.29 are Short Answer Type Questions, carrying 3
marks each. The answer to each question should not exceed 60 words,
iv.
Section D - Questions no. 30 to 33 are Long Answer Type Questions, carrying 5
marks each. Answer to each question should not exceed 120 words
v.
Section E - Questions no. from 34 to 36 are Case Based Questions with three sub-
questions and are of 4 marks each.
vi.
Section F - Question no. 37 is Map-based, carrying 5 marks with two parts, 37a from
History (2 marks) and 37b from Geography (3 marks).
vii.
There is no overall choice in the question paper. However, an internal choice has been
provided in a few questions. Only one of the choices in such questions has to be
attempted.
viii.
In addition to this, separate instructions are given with each section and question,
wherever necessary.






================================================================================
Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class IX Social Science Sample Paper – Set 3
Max. Marks: 80 Marks

                             Time Allowed: 3 hours

General Instructions:
i. Question paper comprises five Sections – A, B, C, D, and E. There are 37 questions in the
question paper. All questions are compulsory.
ii. Section A Questions 1 to 20 are MCQs of 1 mark each.
iii. Section B - Questions no. 21 to 24 are Very Short Answer Type Questions, carrying 2 marks
each. The answer to each question should not exceed 40 words.
iv. Section C - Questions no. 25 to Q.29 are Short Answer Type Questions, carrying 3 marks
each. The answer to each question should not exceed 60 words,
v. Section D - Questions no. 30 to 33 are Long Answer Type Questions, carrying 5 marks each.
Answer to each question should not exceed 120 words
vi. Section E - Questions no. from 34 to 36 are Case Based Questions with three sub-questions
and are of 4 marks each.
vii. Section F - Question no. 37 is Map-based, carrying 5 marks with two parts, 37a from
History (2 marks) and 37b from Geography (3 marks).
viii. There is no overall choice in the question paper. However, an internal choice has been
provided in a few questions. Only one of the choices in such questions has to be attempted.
ix. In addition to this, separate instructions are given with each section and question, wherever
necessary.

In [209]:
clean_bank.loc[
    (clean_bank["class"] == "class9") &
    (clean_bank["session"] == "Unknown"),
    "session"
] = "2026-27"

print(clean_bank["session"].value_counts())

session
2026-27    1349
2025-26     166
2024-25     141
2023-24     139
Name: count, dtype: int64

In [210]:
print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1571
MCQ                   166
Assertion-Reason       47
Case-Based             11
Name: count, dtype: int64

In [211]:
display(
    clean_bank[
        clean_bank["question_type"] == "Short/Long Answer"
    ][
        ["class", "subject", "source_file", "question_number", "question_text"]
    ].head(15)
)

,class,subject,source_file,question_number,question_text
4,class10,computer_application,ComputerApplication-SQP -23-24.pdf,1,The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell
5,class10,computer_application,ComputerApplication-SQP -23-24.pdf,2,Which of the following is an example of social networking website? a. wikipedia.org b. Facebook.com c. cbse.gov.in d. ncert.nic.in
6,class10,computer_application,ComputerApplication-SQP -23-24.pdf,3,M in HTML stands for: a. Modify b. Management c. Multiple d. Markup
7,class10,computer_application,ComputerApplication-SQP -23-24.pdf,4,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic. a. News group b. Blog c. WWW d. e-Groups"
8,class10,computer_application,ComputerApplication-SQP -23-24.pdf,5,Which of the following is not a valid value for the target attribute of <a> tag? a. _blank b. _self c. _top d. _bottom Page 2 of 5
9,class10,computer_application,ComputerApplication-SQP -23-24.pdf,6,"link, vlink, alink are attributes of___________ tag. a. <body> b. <a> c. <html> d. <img>"
10,class10,computer_application,ComputerApplication-SQP -23-24.pdf,7,"The_______ attribute of <img> tag specifies an alternate text for an image, if the image cannot be displayed. a. alt b. text c. alternate d. msg"
11,class10,computer_application,ComputerApplication-SQP -23-24.pdf,8,Which of the following tag can be used to draw a horizontal line in webpage? a. <line> b. <hrule> c. <hr> d. <rule>
12,class10,computer_application,ComputerApplication-SQP -23-24.pdf,9,"In HTML, <dl>, <dd> and <dt> tags are used to create: a. Description list b. Definition list c. Detail list d. Dynamic list"
16,class10,computer_application,ComputerApplication-SQP -23-24.pdf,13,Write any two points of comparison in between SMS and MMS.
17,class10,computer_application,ComputerApplication-SQP -23-24.pdf,14,What is e-Learning? Mention its two main advantages. OR Briefly discuss the role of e-governance in any country’s growth and development.
18,class10,computer_application,ComputerApplication-SQP -23-24.pdf,15,Compare 3G and 4G mobile technologies on any two major points.
19,class10,computer_application,ComputerApplication-SQP -23-24.pdf,16,Which software are termed as open-source software? Name any two such software. OR What do you understand by the term Intellectual property right? Discuss briefly.
20,class10,computer_application,ComputerApplication-SQP -23-24.pdf,17,Mention any two purposes of using comments while designing a HTML webpage.
21,class10,computer_application,ComputerApplication-SQP -23-24.pdf,18,Twisha has got confused with a few tags and their attributes. Help her match the tag with correct attribute.

In [212]:
mcq_pattern = r"(?is)(?:\(?a\)?[\.\):])[\s\S]+(?:\(?b\)?[\.\):])[\s\S]+(?:\(?c\)?[\.\):])[\s\S]+(?:\(?d\)?[\.\):])"

is_mcq = clean_bank["question_text"].fillna("").str.contains(
    mcq_pattern,
    regex=True
)

clean_bank.loc[is_mcq, "question_type"] = "MCQ"

print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1193
MCQ                   569
Assertion-Reason       25
Case-Based              8
Name: count, dtype: int64

In [213]:
# Restore the original question types
original_types = question_bank.set_index("question_id")["question_type"]

clean_bank["question_type"] = clean_bank["question_id"].map(original_types)

# Change only Short/Long Answer rows that clearly contain a,b,c,d options
is_mcq = clean_bank["question_text"].fillna("").str.contains(
    mcq_pattern,
    regex=True
)

clean_bank.loc[
    is_mcq & clean_bank["question_type"].eq("Short/Long Answer"),
    "question_type"
] = "MCQ"

print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1193
MCQ                   544
Assertion-Reason       47
Case-Based             11
Name: count, dtype: int64

In [214]:
display(
    clean_bank[
        clean_bank["question_type"] == "MCQ"
    ][
        ["class", "subject", "question_text"]
    ].head(10)
)

,class,subject,question_text
4,class10,computer_application,The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell
5,class10,computer_application,Which of the following is an example of social networking website? a. wikipedia.org b. Facebook.com c. cbse.gov.in d. ncert.nic.in
6,class10,computer_application,M in HTML stands for: a. Modify b. Management c. Multiple d. Markup
7,class10,computer_application,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic. a. News group b. Blog c. WWW d. e-Groups"
8,class10,computer_application,Which of the following is not a valid value for the target attribute of <a> tag? a. _blank b. _self c. _top d. _bottom Page 2 of 5
9,class10,computer_application,"link, vlink, alink are attributes of___________ tag. a. <body> b. <a> c. <html> d. <img>"
10,class10,computer_application,"The_______ attribute of <img> tag specifies an alternate text for an image, if the image cannot be displayed. a. alt b. text c. alternate d. msg"
11,class10,computer_application,Which of the following tag can be used to draw a horizontal line in webpage? a. <line> b. <hrule> c. <hr> d. <rule>
12,class10,computer_application,"In HTML, <dl>, <dd> and <dt> tags are used to create: a. Description list b. Definition list c. Detail list d. Dynamic list"
14,class10,computer_application,Assertion (A): Search engine is a hardware device that searches for any websites on the World Wide Web. Reason (R): Google Search and Microsoft’s Bing are two popular search engines. (a) Both Assertion (A) and Reason (R) are true and Reason (R) is a correct explanation of Assertion (A). (b) Both...

In [215]:
# Fix Assertion-Reason questions first
is_assertion_reason = (
    clean_bank["question_text"]
    .fillna("")
    .str.contains("assertion", case=False)
    &
    clean_bank["question_text"]
    .fillna("")
    .str.contains("reason", case=False)
)

clean_bank.loc[is_assertion_reason, "question_type"] = "Assertion-Reason"

print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1193
MCQ                   519
Assertion-Reason       72
Case-Based             11
Name: count, dtype: int64

In [216]:
display(
    clean_bank[
        clean_bank["question_type"] == "Case-Based"
    ][
        ["class", "subject", "question_text"]
    ].head(10)
)

,class,subject,question_text
78,class10,home_science,CASE STUDY BASED QUESTIONS Read the passage carefully. Answer question no. 14 to 18. Childhood is the period of human life span between infancy and adolescence extending from ages 2-11 years. It is a time of remarkable growth and development. Growth and development in different domain take place...
111,class10,home_science,"Read the passage carefully and answer Question no. 15 to 18 Time and energy are two important resources but these are limited and one must use them wisely and efficiently. By mastering time and energy management, individuals can achieve their goals while maintaining a sense of equilibrium and vi..."
331,class10,social_science,"(A) : A farmer has borrowed money from a money lender at a high rate of interest, as he could not pay the interest, he was forced to borrow from another landlord to settle the amount for the interest borrowed to the money lender. State the consequences he may face in this situation. OR (B) : “Se..."
383,class10,social_science,Which of the following is the main factor that led to the rise of multiple political parties at the same level in India? (A) A federal political system (B) Varied economic conditions. (C) Linguistic and regional diversity (D) Low levels of literacy and political awareness 1 18 The result of grea...
532,class9,maths,Construct a right triangle whose hypotenuse is 6 cm and one of the legs is 4 cm. Write the steps of construction. 5 SECTION E (Case-Based Questions: 4 marks each)
543,class9,maths,Join BC. Then ABC is right-angled with hypotenuse 6 BC = cm and leg 4 AB = cm. www.vedantu.com 24 SECTION E (Case-Based Questions: 4 marks each) with Solution Q36. Solution: (a) The y -coordinate gives the vertical distance from the x -axis. So the distance is 4 units. (b) The x -coordinate give...
913,class9,maths,"0.3 0.2 0.5. P X P X P X P X  = + + =  = = + = = + = Section E (Q36--Q38, 4 marks each, case-based)"
1499,class9,social_science,"Read the following passage and answer the questions that follow:​ In the village of Rampur, most of the families are dependent on agriculture for their livelihood, but many also do non-farm work such as running shops, driving rickshaws, and working in small factories. The government has introduc..."
1561,class9,social_science,Give reasons as to why. i. Seasonal reversal of wind direction takes place over the Indian subcontinent? ii. The bulk of rainfall in India is concentrated over a few months. iii. The Tamil Nadu coast receives winter rainfall. iv. The delta region of the eastern coast is frequently struck by cycl...
1562,class9,social_science,"Read the following text carefully and answer the questions that follow: Under the shadow of war, the Nazis proceeded to realise their murderous, racial ideal. Genocide and war became two sides of the same coin. Occupied Poland was divided up. Much of north-western 4 www.vedantu.com 10 Poland was..."

In [217]:
display(
    clean_bank[
        clean_bank["question_type"] == "Case-Based"
    ][
        ["class", "subject", "source_file",
         "question_number", "question_text"]
    ]
)

,class,subject,source_file,question_number,question_text
78,class10,home_science,HomeScience-SQP -23-24.pdf,14,CASE STUDY BASED QUESTIONS Read the passage carefully. Answer question no. 14 to 18. Childhood is the period of human life span between infancy and adolescence extending from ages 2-11 years. It is a time of remarkable growth and development. Growth and development in different domain take place...
111,class10,home_science,HomeScience-SQP -24-25.pdf,16,"Read the passage carefully and answer Question no. 15 to 18 Time and energy are two important resources but these are limited and one must use them wisely and efficiently. By mastering time and energy management, individuals can achieve their goals while maintaining a sense of equilibrium and vi..."
331,class10,social_science,SocialScience-SQP -23-24.pdf,33,"(A) : A farmer has borrowed money from a money lender at a high rate of interest, as he could not pay the interest, he was forced to borrow from another landlord to settle the amount for the interest borrowed to the money lender. State the consequences he may face in this situation. OR (B) : “Se..."
383,class10,social_science,SocialScience-SQP -24-25.pdf,17,Which of the following is the main factor that led to the rise of multiple political parties at the same level in India? (A) A federal political system (B) Varied economic conditions. (C) Linguistic and regional diversity (D) Low levels of literacy and political awareness 1 18 The result of grea...
532,class9,maths,CBSE Class 9 Maths Sample Paper Set 3 for 2026-27.pdf,35,Construct a right triangle whose hypotenuse is 6 cm and one of the legs is 4 cm. Write the steps of construction. 5 SECTION E (Case-Based Questions: 4 marks each)
543,class9,maths,CBSE Class 9 Maths Sample Paper Set 3 for 2026-27.pdf,4,Join BC. Then ABC is right-angled with hypotenuse 6 BC = cm and leg 4 AB = cm. www.vedantu.com 24 SECTION E (Case-Based Questions: 4 marks each) with Solution Q36. Solution: (a) The y -coordinate gives the vertical distance from the x -axis. So the distance is 4 units. (b) The x -coordinate give...
913,class9,maths,Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf,3,"0.3 0.2 0.5. P X P X P X P X  = + + =  = = + = = + = Section E (Q36--Q38, 4 marks each, case-based)"
1499,class9,social_science,CBSE Class 9 Social Science Sample Paper 2026-27 (Mock Paper 7).pdf,35,"Read the following passage and answer the questions that follow:​ In the village of Rampur, most of the families are dependent on agriculture for their livelihood, but many also do non-farm work such as running shops, driving rickshaws, and working in small factories. The government has introduc..."
1561,class9,social_science,CBSE Class 9 Social Science Sample Paper Set 1 FREE PDF for 2026-27.pdf,33,Give reasons as to why. i. Seasonal reversal of wind direction takes place over the Indian subcontinent? ii. The bulk of rainfall in India is concentrated over a few months. iii. The Tamil Nadu coast receives winter rainfall. iv. The delta region of the eastern coast is frequently struck by cycl...
1562,class9,social_science,CBSE Class 9 Social Science Sample Paper Set 1 FREE PDF for 2026-27.pdf,34,"Read the following text carefully and answer the questions that follow: Under the shadow of war, the Nazis proceeded to realise their murderous, racial ideal. Genocide and war became two sides of the same coin. Occupied Poland was divided up. Much of north-western 4 www.vedantu.com 10 Poland was..."
1603,class9,social_science,CBSE Class 9 Social Science Sample Paper Set 1 FREE PDF for 2026-27.pdf,34,"i. The passage reflects the Nazi racial ideology, particularly their belief in the superiority of the Aryan race and the desire to exterminate or dominate other races. The forced relocation, killings, and the systematic destruction of Polish and Jewish populations exemplify the Nazis' focus on r..."

In [218]:
# Reset current Case-Based labels
clean_bank.loc[
    clean_bank["question_type"] == "Case-Based",
    "question_type"
] = "Short/Long Answer"

# Identify clearly case/passage-based questions
text = clean_bank["question_text"].fillna("")

is_case = (
    text.str.contains("case study", case=False, na=False)
    | text.str.contains("read the passage", case=False, na=False)
    | text.str.contains("read the following text", case=False, na=False)
)

clean_bank.loc[is_case, "question_type"] = "Case-Based"

print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1172
MCQ                   517
Assertion-Reason       72
Case-Based             34
Name: count, dtype: int64

In [219]:
print(
    "MCQs with empty options:",
    clean_bank.loc[
        clean_bank["question_type"] == "MCQ",
        "options"
    ].fillna("").str.strip().eq("").sum()
)

MCQs with empty options: 195

In [220]:
display(
    clean_bank[
        (clean_bank["question_type"] == "MCQ") &
        (clean_bank["options"].fillna("").str.strip() == "")
    ][
        ["class", "subject", "question_text"]
    ].head(5)
)

,class,subject,question_text
4,class10,computer_application,The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell
5,class10,computer_application,Which of the following is an example of social networking website? a. wikipedia.org b. Facebook.com c. cbse.gov.in d. ncert.nic.in
6,class10,computer_application,M in HTML stands for: a. Modify b. Management c. Multiple d. Markup
7,class10,computer_application,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic. a. News group b. Blog c. WWW d. e-Groups"
8,class10,computer_application,Which of the following is not a valid value for the target attribute of <a> tag? a. _blank b. _self c. _top d. _bottom Page 2 of 5

In [221]:
for _, row in clean_bank[
    (clean_bank["question_type"] == "MCQ") &
    (clean_bank["options"].fillna("").str.strip() == "")
].head(5).iterrows():

    print("\nQUESTION:")
    print(row["question_text"])
    print("-" * 80)

QUESTION:
The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell
--------------------------------------------------------------------------------

QUESTION:
Which of the following is an example of social networking website? a. wikipedia.org b. Facebook.com c. cbse.gov.in d. ncert.nic.in
--------------------------------------------------------------------------------

QUESTION:
M in HTML stands for: a. Modify b. Management c. Multiple d. Markup
--------------------------------------------------------------------------------

QUESTION:
A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic. a. News group b. Blog c. WWW d. e-Groups
--------------------------------------------------------------------------------

QUESTION:
Which of the following is not a valid value for the target attribute of <a> tag? a. _blank b. _self c. _top d. _bottom Page 2 of 5
--------------------------------------------------------------------------------

In [222]:
def extract_options(text):
    pattern = r"(?i)(?:^|\s)([a-d])\.\s*(.*?)(?=\s+[a-d]\.\s+|$)"
    matches = re.findall(pattern, text)

    return " | ".join(
        f"{letter}. {option.strip()}"
        for letter, option in matches
    )

clean_bank["options"] = clean_bank["question_text"].apply(extract_options)

print(
    "MCQs with options:",
    clean_bank.loc[
        clean_bank["question_type"] == "MCQ",
        "options"
    ].ne("").sum()
)

MCQs with options: 100

In [223]:
display(
    clean_bank[
        (clean_bank["question_type"] == "MCQ") &
        (clean_bank["options"].fillna("").str.strip() == "")
    ][
        ["class", "subject", "source_file", "question_text"]
    ].head(5)
)

,class,subject,source_file,question_text
97,class10,home_science,HomeScience-SQP -24-25.pdf,“While advertising manufacturers often give an exaggerated picture of their product”. Which malpractice of manufacturer is exhibited in this statement? (A)Charging high price (B)Adulteration of goods (C)Misleading information (D)Lack of standardized products 1
98,class10,home_science,HomeScience-SQP -24-25.pdf,Which of the following characteristic of cognitive development is observed in 4 to 6 years old child? (A) Diminished egocentrism (B) Ability to conserve (C) Egocentrism (D) Can differentiate between living and non-living things OR Which of the following characteristic of emotional development is...
99,class10,home_science,HomeScience-SQP -24-25.pdf,The food whose nature or quality is so affected that it is injurious to health is- (A) Organic food (B) Unsafe food (C) Raw food (D) Super food 1
100,class10,home_science,HomeScience-SQP -24-25.pdf,"Which of the following are characteristics to identify a stain on a fabric? (A) Colour, smell or feel (B) Colour, taste or look (C)Taste, shape or feel (D) Colour, shape or feel 1"
101,class10,home_science,HomeScience-SQP -24-25.pdf,“Adolescents give more importance to their friends and like to spend more time with them.” Which type of development is exhibited in this statement? (A) Physical (B) Language (C) Social (D) Cognitive 1

In [224]:
for _, row in clean_bank[
    (clean_bank["question_type"] == "MCQ") &
    (clean_bank["options"].fillna("").str.strip() == "")
].head(5).iterrows():

    print("\nQUESTION:")
    print(row["question_text"])
    print("-" * 80)

QUESTION:
“While advertising manufacturers often give an exaggerated picture of their product”. Which malpractice of manufacturer is exhibited in this statement? (A)Charging high price (B)Adulteration of goods (C)Misleading information (D)Lack of standardized products 1
--------------------------------------------------------------------------------

QUESTION:
Which of the following characteristic of cognitive development is observed in 4 to 6 years old child? (A) Diminished egocentrism (B) Ability to conserve (C) Egocentrism (D) Can differentiate between living and non-living things OR Which of the following characteristic of emotional development is observed in 8 to 10 years old child? (A) Have imaginary friends (B) Can control impulses (C) Do not hide emotions (D)Emotions are transitory (change rapidly) and unpredictable 1 2
--------------------------------------------------------------------------------

QUESTION:
The food whose nature or quality is so affected that it is injurious to health is- (A) Organic food (B) Unsafe food (C) Raw food (D) Super food 1
--------------------------------------------------------------------------------

QUESTION:
Which of the following are characteristics to identify a stain on a fabric? (A) Colour, smell or feel (B) Colour, taste or look (C)Taste, shape or feel (D) Colour, shape or feel 1
--------------------------------------------------------------------------------

QUESTION:
“Adolescents give more importance to their friends and like to spend more time with them.” Which type of development is exhibited in this statement? (A) Physical (B) Language (C) Social (D) Cognitive 1
--------------------------------------------------------------------------------

In [225]:
def extract_options(text):
    pattern = r"(?i)(?:^|\s)(\([a-d]\)|[a-d][\.\:\)])\s+(.+?)(?=\s+(?:\([a-d]\)|[a-d][\.\:\)])\s+|$)"
    
    matches = re.findall(pattern, text)

    return " | ".join(
        f"{label.upper()} {option.strip()}"
        for label, option in matches
    )


clean_bank["options"] = clean_bank["question_text"].apply(extract_options)

print(
    "MCQs with options:",
    clean_bank.loc[
        clean_bank["question_type"] == "MCQ",
        "options"
    ].ne("").sum()
)

MCQs with options: 515

In [226]:
display(
    clean_bank[
        clean_bank["question_type"] == "MCQ"
    ][["question_text", "options"]].head(5)
)

,question_text,options
4,The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell,A. Safe Shell | B. Software Shell | C. Secure Shell | D. Simple Shell
5,Which of the following is an example of social networking website? a. wikipedia.org b. Facebook.com c. cbse.gov.in d. ncert.nic.in,A. wikipedia.org | B. Facebook.com | C. cbse.gov.in | D. ncert.nic.in
6,M in HTML stands for: a. Modify b. Management c. Multiple d. Markup,A. Modify | B. Management | C. Multiple | D. Markup
7,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic. a. News group b. Blog c. WWW d. e-Groups",A. News group | B. Blog | C. WWW | D. e-Groups
8,Which of the following is not a valid value for the target attribute of <a> tag? a. _blank b. _self c. _top d. _bottom Page 2 of 5,A. _blank | B. _self | C. _top | D. _bottom Page 2 of 5

In [227]:
display(
    clean_bank[
        (clean_bank["question_type"] == "MCQ") &
        (clean_bank["options"].fillna("").str.strip() == "")
    ][
        ["class", "subject", "source_file", "question_text"]
    ]
)

,class,subject,source_file,question_text
97,class10,home_science,HomeScience-SQP -24-25.pdf,“While advertising manufacturers often give an exaggerated picture of their product”. Which malpractice of manufacturer is exhibited in this statement? (A)Charging high price (B)Adulteration of goods (C)Misleading information (D)Lack of standardized products 1
1761,class9,social_science,Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf,"Arrange the following events in chronological order: i. The Great Economic Depression begins. ii. The mass murder of the Jews begins. iii. Second World War begins. iv. First World War begins. a)iv, ii, i, iii b)iii, i, ii, iv c)i, iv, iii, ii d)iv, i, iii, ii 1"

In [228]:
for _, row in clean_bank[
    (clean_bank["question_type"] == "MCQ") &
    (clean_bank["options"].fillna("").str.strip() == "")
].iterrows():

    print("\nQUESTION:")
    print(row["question_text"])
    print("-" * 80)

QUESTION:
“While advertising manufacturers often give an exaggerated picture of their product”. Which malpractice of manufacturer is exhibited in this statement? (A)Charging high price (B)Adulteration of goods (C)Misleading information (D)Lack of standardized products 1
--------------------------------------------------------------------------------

QUESTION:
Arrange the following events in chronological order: i. The Great Economic Depression begins. ii. The mass murder of the Jews begins. iii. Second World War begins. iv. First World War begins. a)iv, ii, i, iii b)iii, i, ii, iv c)i, iv, iii, ii d)iv, i, iii, ii 1
--------------------------------------------------------------------------------

In [229]:
def remove_options(text):
    return re.split(
        r"(?i)\s+(?:\([a-d]\)|[a-d][\.\:\)])\s+",
        text,
        maxsplit=1
    )[0].strip()

clean_bank["question_text_clean"] = (
    clean_bank["question_text"]
    .apply(remove_options)
)

display(
    clean_bank[
        ["question_text", "question_text_clean", "options"]
    ].head(5)
)

,question_text,question_text_clean,options
4,The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell,The acronym SSH stands for_________________.,A. Safe Shell | B. Software Shell | C. Secure Shell | D. Simple Shell
5,Which of the following is an example of social networking website? a. wikipedia.org b. Facebook.com c. cbse.gov.in d. ncert.nic.in,Which of the following is an example of social networking website?,A. wikipedia.org | B. Facebook.com | C. cbse.gov.in | D. ncert.nic.in
6,M in HTML stands for: a. Modify b. Management c. Multiple d. Markup,M in HTML stands for:,A. Modify | B. Management | C. Multiple | D. Markup
7,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic. a. News group b. Blog c. WWW d. e-Groups","A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic.",A. News group | B. Blog | C. WWW | D. e-Groups
8,Which of the following is not a valid value for the target attribute of <a> tag? a. _blank b. _self c. _top d. _bottom Page 2 of 5,Which of the following is not a valid value for the target attribute of <a> tag?,A. _blank | B. _self | C. _top | D. _bottom Page 2 of 5

In [230]:
clean_file = processed_folder / "clean_question_bank.csv"

clean_bank.to_csv(
    clean_file,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", clean_file)
print("Rows:", len(clean_bank))
print("Columns:", len(clean_bank.columns))

Saved: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\clean_question_bank.csv
Rows: 1795
Columns: 18

In [231]:
print("Missing question text:", clean_bank["question_text_clean"].isna().sum())
print("Missing class:", clean_bank["class"].isna().sum())
print("Missing subject:", clean_bank["subject"].isna().sum())
print("Missing session:", clean_bank["session"].isna().sum())

Missing question text: 0
Missing class: 0
Missing subject: 0
Missing session: 0

In [232]:
llm_dataset = clean_bank[
    [
        "question_id",
        "class",
        "subject",
        "session",
        "question_type",
        "question_text_clean",
        "options",
        "source_file"
    ]
].copy()

print("LLM dataset rows:", len(llm_dataset))
print("LLM dataset columns:", llm_dataset.columns.tolist())

display(llm_dataset.head(10))

LLM dataset rows: 1795
LLM dataset columns: ['question_id', 'class', 'subject', 'session', 'question_type', 'question_text_clean', 'options', 'source_file']

,question_id,class,subject,session,question_type,question_text_clean,options,source_file
4,5,class10,computer_application,2023-24,MCQ,The acronym SSH stands for_________________.,A. Safe Shell | B. Software Shell | C. Secure Shell | D. Simple Shell,ComputerApplication-SQP -23-24.pdf
5,6,class10,computer_application,2023-24,MCQ,Which of the following is an example of social networking website?,A. wikipedia.org | B. Facebook.com | C. cbse.gov.in | D. ncert.nic.in,ComputerApplication-SQP -23-24.pdf
6,7,class10,computer_application,2023-24,MCQ,M in HTML stands for:,A. Modify | B. Management | C. Multiple | D. Markup,ComputerApplication-SQP -23-24.pdf
7,8,class10,computer_application,2023-24,MCQ,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic.",A. News group | B. Blog | C. WWW | D. e-Groups,ComputerApplication-SQP -23-24.pdf
8,9,class10,computer_application,2023-24,MCQ,Which of the following is not a valid value for the target attribute of <a> tag?,A. _blank | B. _self | C. _top | D. _bottom Page 2 of 5,ComputerApplication-SQP -23-24.pdf
9,10,class10,computer_application,2023-24,MCQ,"link, vlink, alink are attributes of___________ tag.",A. <body> | B. <a> | C. <html> | D. <img>,ComputerApplication-SQP -23-24.pdf
10,11,class10,computer_application,2023-24,MCQ,"The_______ attribute of <img> tag specifies an alternate text for an image, if the image cannot be displayed.",A. alt | B. text | C. alternate | D. msg,ComputerApplication-SQP -23-24.pdf
11,12,class10,computer_application,2023-24,MCQ,Which of the following tag can be used to draw a horizontal line in webpage?,A. <line> | B. <hrule> | C. <hr> | D. <rule>,ComputerApplication-SQP -23-24.pdf
12,13,class10,computer_application,2023-24,MCQ,"In HTML, <dl>, <dd> and <dt> tags are used to create:",A. Description list | B. Definition list | C. Detail list | D. Dynamic list,ComputerApplication-SQP -23-24.pdf
13,14,class10,computer_application,2023-24,Assertion-Reason,A software _________ is a legal instrument governing the use or redistribution of software.,"A. license | B. law | C. document | D. piracy Questions No-11 & 12 are Assertion and Reason types. Each question consists of two statements, namely, Assertion | (A) and Reason (R). Select the most suitable option considering the Assertion & Reason.",ComputerApplication-SQP -23-24.pdf

In [233]:
llm_file = processed_folder / "llm_input_dataset.csv"

llm_dataset.to_csv(
    llm_file,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", llm_file)

Saved: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\llm_input_dataset.csv

In [234]:
import psutil

ram_gb = psutil.virtual_memory().total / (1024 ** 3)

print(f"System RAM: {ram_gb:.1f} GB")

System RAM: 15.9 GB

In [235]:
import torch

print("PyTorch version:", torch.__version__)
print("GPU available:", torch.cuda.is_available())

PyTorch version: 2.14.0+cpu
GPU available: False

In [236]:
from transformers import pipeline
generator = pipeline(
    "text-generation",
    model="Qwen/Qwen2.5-1.5B-Instruct"
)
print("Model loaded successfully!")

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

Model loaded successfully!

In [237]:
messages = [
    {"role": "user",
     "content": "Write one simple Class 9 Maths question about linear equations."
    }]
result = generator(messages, max_new_tokens=100)
print(result)

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[{'generated_text': [{'role': 'user', 'content': 'Write one simple Class 9 Maths question about linear equations.'}, {'role': 'assistant', 'content': "Sure! Here's a simple Class 9 Maths question about linear equations:\n\n**Question:**\n\nSolve the following equation for \\( x \\):\n\n\\[ 3x + 5 = 20 \\]\n\n**Answer Steps:**\n1. Subtract 5 from both sides of the equation to isolate the term with \\( x \\):\n   \\[ 3x + 5 - 5 = 20 - 5 \\]\n   Simplifying this gives:\n   \\[ 3x"}]}]

In [238]:
sample = llm_dataset[
    llm_dataset["question_type"] == "MCQ"
].iloc[0]

print("Class:", sample["class"])
print("Subject:", sample["subject"])
print("Type:", sample["question_type"])
print("Question:", sample["question_text_clean"])
print("Options:", sample["options"])

Class: class10
Subject: computer_application
Type: MCQ
Question: The acronym SSH stands for_________________.
Options: A. Safe Shell | B. Software Shell | C. Secure Shell | D. Simple Shell

In [239]:
sample = llm_dataset[
    llm_dataset["question_type"] == "MCQ"
].iloc[0]

print("Class:", sample["class"])
print("Subject:", sample["subject"])
print("Type:", sample["question_type"])
print("Question:", sample["question_text_clean"])
print("Options:", sample["options"])

Class: class10
Subject: computer_application
Type: MCQ
Question: The acronym SSH stands for_________________.
Options: A. Safe Shell | B. Software Shell | C. Secure Shell | D. Simple Shell

In [240]:
from transformers import GenerationConfig

test_generation_config = GenerationConfig(
    max_new_tokens=120,
    do_sample=True,
    temperature=0.7,
    top_p=0.9,
    repetition_penalty=1.15
)

def generate_new_question(class_name, subject, question_type,
                          source_question, source_options):

    prompt = f"""
You are an expert CBSE question paper writer.

Generate ONE completely NEW question for:

Class: {class_name}
Subject: {subject}
Question Type: {question_type}

SOURCE QUESTION:
{source_question}

SOURCE OPTIONS:
{source_options}

Your task:
Create a NEW application-based or scenario-based question
that tests the SAME KNOWLEDGE CONCEPT as the source.

Do not ask a direct definition or full-form question.
Change the question structure completely.
Do not reuse the source wording or source options.

The generated question should preferably use a short
real-world or practical situation.

Very important:
- Do NOT change to a different concept.
- Do NOT introduce an unrelated topic.
- Do NOT copy or paraphrase the source question.
- Do NOT reuse the source options.
- Do NOT simply change one word.
- The new question must be self-contained.
- Do not refer to maps, images, figures, or diagrams.
- For MCQ, provide exactly 4 options.
- Only ONE option must be correct.
- The correct answer must be factually consistent with the SAME concept as the source.

Example of what NOT to do:
Source about SSH -> do NOT create a question about SSL.
Source about social networking websites -> do NOT create a question about backend programming.

Use exactly this format:

QUESTION:
<new question>

A) <option>
B) <option>
C) <option>
D) <option>

ANSWER:
<correct option>
"""

    result = generator(
        [{"role": "user", "content": prompt}],
        generation_config=test_generation_config
    )

    return result[0]["generated_text"][-1]["content"]

In [241]:
generated_file = processed_folder / "generated_questions.csv"

generated_df = pd.read_csv(generated_file)

print("Generated questions:", len(generated_df))
display(generated_df.head(5))

Generated questions: 14

,class,subject,question_type,source_question,generated_question,quality_status
0,class9,science,MCQ,(a) Amoeba and Euglena arc unicellular organisms. www.vedantu.com 30,QUESTION:\nWhich of the following statements is true about amoebas?\n\nA) They have multiple nuclei and chloroplasts.\nB) They are photosynthetic and live in water.\nC) They reproduce through binary fission but lack cellular structure.\nD) They move using pseudopodia and feed on organic matter.\...,PASS_FORMAT
1,class9,social_science,MCQ,"Read the information given below and select the correct option. Most of men and women in the eighteenth century could not read or write. So, images and symbols were frequently used instead of printed words to communicate important ideas. Which of the following was a symbol of royal power?",QUESTION:\nWhich of the following was a symbol of royal power during the eighteenth century?\n\nA) The Bible\nB) The Crown Jewels\nC) The Royal Coat of Arms\nD) The Flag of Great Britain\n\nANSWER:\nC) The Royal Coat of Arms,PASS_FORMAT
2,class9,social_science,MCQ,The river Narmada has its source at:,QUESTION:\nWhat is the primary source of water for the river Narmada?\n\nA) Himalayas\nB) Aravallis\nC) Western Ghats\nD) Eastern Ghats\n\nANSWER:\nB) Aravallis,PASS_FORMAT
3,class9,maths,MCQ,Which of the following numbers cannot be represented as a terminating decimal?,QUESTION:\nWhich of the following numbers cannot be represented as a terminating decimal?\n\nA) 1/3 \nB) 2/5 \nC) 7/8 \nD) 3/2 \n\nANSWER:\nA) 1/3,PASS_FORMAT
4,class9,social_science,MCQ,"On the given map of France, A is marked as a place where troops entered following the King’s Command. Identify it from the following options. 1 www.vedantu.com 6","QUESTION:\nOn the given map of France, A is marked as a place where troops entered following the King's Command. Identify it from the following options. 3\n\nA) Paris\nB) Marseille\nC) Strasbourg\nD) Bordeaux\n\nANSWER:\nD) Bordeaux",PASS_FORMAT

In [242]:
display(
    generated_df[
        ["class", "subject", "source_question", "generated_question"]
    ].head(5)
)

,class,subject,source_question,generated_question
0,class9,science,(a) Amoeba and Euglena arc unicellular organisms. www.vedantu.com 30,QUESTION:\nWhich of the following statements is true about amoebas?\n\nA) They have multiple nuclei and chloroplasts.\nB) They are photosynthetic and live in water.\nC) They reproduce through binary fission but lack cellular structure.\nD) They move using pseudopodia and feed on organic matter.\...
1,class9,social_science,"Read the information given below and select the correct option. Most of men and women in the eighteenth century could not read or write. So, images and symbols were frequently used instead of printed words to communicate important ideas. Which of the following was a symbol of royal power?",QUESTION:\nWhich of the following was a symbol of royal power during the eighteenth century?\n\nA) The Bible\nB) The Crown Jewels\nC) The Royal Coat of Arms\nD) The Flag of Great Britain\n\nANSWER:\nC) The Royal Coat of Arms
2,class9,social_science,The river Narmada has its source at:,QUESTION:\nWhat is the primary source of water for the river Narmada?\n\nA) Himalayas\nB) Aravallis\nC) Western Ghats\nD) Eastern Ghats\n\nANSWER:\nB) Aravallis
3,class9,maths,Which of the following numbers cannot be represented as a terminating decimal?,QUESTION:\nWhich of the following numbers cannot be represented as a terminating decimal?\n\nA) 1/3 \nB) 2/5 \nC) 7/8 \nD) 3/2 \n\nANSWER:\nA) 1/3
4,class9,social_science,"On the given map of France, A is marked as a place where troops entered following the King’s Command. Identify it from the following options. 1 www.vedantu.com 6","QUESTION:\nOn the given map of France, A is marked as a place where troops entered following the King's Command. Identify it from the following options. 3\n\nA) Paris\nB) Marseille\nC) Strasbourg\nD) Bordeaux\n\nANSWER:\nD) Bordeaux"

In [243]:
for i, row in generated_df.head(5).iterrows():
    print("\n" + "=" * 80)
    print("CLASS:", row["class"])
    print("SUBJECT:", row["subject"])
    print("SOURCE:", row["source_question"])
    print("\nGENERATED:")
    print(row["generated_question"])

================================================================================
CLASS: class9
SUBJECT: science
SOURCE: (a) Amoeba and Euglena arc unicellular organisms. www.vedantu.com 30

GENERATED:
QUESTION:
Which of the following statements is true about amoebas?

A) They have multiple nuclei and chloroplasts.
B) They are photosynthetic and live in water.
C) They reproduce through binary fission but lack cellular structure.
D) They move using pseudopodia and feed on organic matter.

ANSWER:
D) They move using pseudopodia and feed on organic matter.

================================================================================
CLASS: class9
SUBJECT: social_science
SOURCE: Read the information given below and select the correct option. Most of men and women in the eighteenth century could not read or write. So, images and symbols were frequently used instead of printed words to communicate important ideas. Which of the following was a symbol of royal power?

GENERATED:
QUESTION:
Which of the following was a symbol of royal power during the eighteenth century?

A) The Bible
B) The Crown Jewels
C) The Royal Coat of Arms
D) The Flag of Great Britain

ANSWER:
C) The Royal Coat of Arms

================================================================================
CLASS: class9
SUBJECT: social_science
SOURCE: The river Narmada has its source at:

GENERATED:
QUESTION:
What is the primary source of water for the river Narmada?

A) Himalayas
B) Aravallis
C) Western Ghats
D) Eastern Ghats

ANSWER:
B) Aravallis

================================================================================
CLASS: class9
SUBJECT: maths
SOURCE: Which of the following numbers cannot be represented as a terminating decimal?

GENERATED:
QUESTION:
Which of the following numbers cannot be represented as a terminating decimal?

A) 1/3
B) 2/5
C) 7/8
D) 3/2

ANSWER:
A) 1/3

================================================================================
CLASS: class9
SUBJECT: social_science
SOURCE: On the given map of France, A is marked as a place where troops entered following the King’s Command. Identify it from the following options. 1 www.vedantu.com 6

GENERATED:
QUESTION:
On the given map of France, A is marked as a place where troops entered following the King's Command. Identify it from the following options. 3

A) Paris
B) Marseille
C) Strasbourg
D) Bordeaux

ANSWER:
D) Bordeaux

In [244]:
print("Generated:", len(generated_df))

for i, row in generated_df.iterrows():
    print(
        i,
        "|",
        row["class"],
        "|",
        row["subject"]
    )

Generated: 14
0 | class9 | science
1 | class9 | social_science
2 | class9 | social_science
3 | class9 | maths
4 | class9 | social_science
5 | class10 | social_science
6 | class9 | maths
7 | class9 | social_science
8 | class9 | science
9 | class9 | maths
10 | class9 | social_science
11 | class9 | science
12 | class9 | science
13 | class10 | maths

In [245]:
import re
from difflib import SequenceMatcher

def validate_generated(row):
    text = row["generated_question"]

    option_count = len(
        re.findall(r"(?m)^[A-D][\)\.]\s+", text)
    )

    has_answer = bool(
        re.search(r"(?im)^ANSWER:\s*$", text)
    )

    source = row["source_question"]
    similarity = SequenceMatcher(
        None,
        source.lower(),
        text.lower()
    ).ratio()

    if option_count == 4 and has_answer and similarity < 0.75:
        return "PASS_FORMAT"

    return "REVIEW"

generated_df["quality_status"] = generated_df.apply(
    validate_generated,
    axis=1
)

print(generated_df["quality_status"].value_counts())

display(
    generated_df[
        ["class", "subject", "quality_status"]
    ]
)

quality_status
REVIEW    14
Name: count, dtype: int64

      class         subject quality_status
0    class9         science         REVIEW
1    class9  social_science         REVIEW
2    class9  social_science         REVIEW
3    class9           maths         REVIEW
4    class9  social_science         REVIEW
5   class10  social_science         REVIEW
6    class9           maths         REVIEW
7    class9  social_science         REVIEW
8    class9         science         REVIEW
9    class9           maths         REVIEW
10   class9  social_science         REVIEW
11   class9         science         REVIEW
12   class9         science         REVIEW
13  class10           maths         REVIEW

In [246]:
for i, row in generated_df.iterrows():
    text = row["generated_question"]

    option_count = len(
        re.findall(r"(?m)^[A-D][\)\.]\s+", text)
    )

    has_answer = bool(
        re.search(r"(?im)^ANSWER:\s*$", text)
    )

    similarity = SequenceMatcher(
        None,
        row["source_question"].lower(),
        text.lower()
    ).ratio()

    print(
        i,
        "| options:", option_count,
        "| answer:", has_answer,
        "| similarity:", round(similarity, 2)
    )

0 | options: 5 | answer: True | similarity: 0.02
1 | options: 5 | answer: True | similarity: 0.02
2 | options: 5 | answer: True | similarity: 0.33
3 | options: 5 | answer: True | similarity: 0.71
4 | options: 5 | answer: True | similarity: 0.73
5 | options: 5 | answer: True | similarity: 0.05
6 | options: 5 | answer: True | similarity: 0.25
7 | options: 5 | answer: True | similarity: 0.03
8 | options: 5 | answer: True | similarity: 0.05
9 | options: 4 | answer: False | similarity: 0.31
10 | options: 5 | answer: True | similarity: 0.58
11 | options: 5 | answer: True | similarity: 0.0
12 | options: 5 | answer: True | similarity: 0.1
13 | options: 5 | answer: True | similarity: 0.65

In [247]:
def validate_generated(row):
    text = row["generated_question"]

    # Count options only before the ANSWER section
    question_part = text.split("ANSWER:", 1)[0]

    option_count = len(
        re.findall(r"(?m)^[A-D][\)\.]\s+", question_part)
    )

    has_answer = "ANSWER:" in text

    similarity = SequenceMatcher(
        None,
        row["source_question"].lower(),
        text.lower()
    ).ratio()

    if option_count == 4 and has_answer and similarity < 0.75:
        return "PASS_FORMAT"

    return "REVIEW"


generated_df["quality_status"] = generated_df.apply(
    validate_generated,
    axis=1
)

print(generated_df["quality_status"].value_counts())

quality_status
PASS_FORMAT    13
REVIEW          1
Name: count, dtype: int64

In [248]:
display(
    generated_df[
        generated_df["quality_status"] == "REVIEW"
    ][
        ["class", "subject", "source_question", "generated_question"]
    ]
)

,class,subject,source_question,generated_question
9,class9,maths,Which of these is a valid LPP objective function to be maximized?,"QUESTION:\nWhich of these is a valid LPP objective function to be maximized?\n\nA) Maximize Z = 2x + 3y \n subject to x + y ≤ 10 \n and x, y ≥ 0 \n\nB) Minimize Z = -5x + 7y \n subject to 2x + y ≥ 8 \n and x, y ≥ 0 \n\nC) Maximize Z = -4x + 6y \n subject to x + y ≤ 15 \n and ..."

In [249]:
replacement = """QUESTION:
Which event is considered to have marked the beginning of the French Revolution?

A) The storming of the Bastille
B) The signing of the Treaty of Versailles
C) The Reign of Terror
D) Napoleon's rise to power

ANSWER:
A) The storming of the Bastille"""

print(replacement)

QUESTION:
Which event is considered to have marked the beginning of the French Revolution?

A) The storming of the Bastille
B) The signing of the Treaty of Versailles
C) The Reign of Terror
D) Napoleon's rise to power

ANSWER:
A) The storming of the Bastille

In [250]:
accepted_df = generated_df[
    generated_df["quality_status"] == "PASS_FORMAT"
].copy()

replacement_row = {
    "class": "class9",
    "subject": "social_science",
    "question_type": "MCQ",
    "source_question": "French Revolution topic",
    "generated_question": replacement,
    "quality_status": "PASS_FORMAT",
    "answer_status": "Needs verification"
}

accepted_df["answer_status"] = "Needs verification"

accepted_df = pd.concat(
    [accepted_df, pd.DataFrame([replacement_row])],
    ignore_index=True
)

print("Final generated questions:", len(accepted_df))

Final generated questions: 14

In [251]:
final_generated_file = processed_folder / "final_generated_questions.csv"
accepted_df.to_csv(final_generated_file,index=False,encoding="utf-8-sig")
print("Saved:", final_generated_file)

Saved: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\final_generated_questions.csv

In [252]:
final_df = pd.read_csv(final_generated_file)

print("Total generated questions:", len(final_df))
print("\nColumns:")
print(final_df.columns.tolist())

print("\nQuality status:")
print(final_df["quality_status"].value_counts())

final_df.head()

Total generated questions: 14

Columns:
['class', 'subject', 'question_type', 'source_question', 'generated_question', 'quality_status', 'answer_status']

Quality status:
quality_status
PASS_FORMAT    14
Name: count, dtype: int64

,class,subject,question_type,source_question,generated_question,quality_status,answer_status
0,class9,science,MCQ,(a) Amoeba and Euglena arc unicellular organisms. www.vedantu.com 30,QUESTION:\nWhich of the following statements is true about amoebas?\n\nA) They have multiple nuclei and chloroplasts.\nB) They are photosynthetic and live in water.\nC) They reproduce through binary fission but lack cellular structure.\nD) They move using pseudopodia and feed on organic matter.\...,PASS_FORMAT,Needs verification
1,class9,social_science,MCQ,"Read the information given below and select the correct option. Most of men and women in the eighteenth century could not read or write. So, images and symbols were frequently used instead of printed words to communicate important ideas. Which of the following was a symbol of royal power?",QUESTION:\nWhich of the following was a symbol of royal power during the eighteenth century?\n\nA) The Bible\nB) The Crown Jewels\nC) The Royal Coat of Arms\nD) The Flag of Great Britain\n\nANSWER:\nC) The Royal Coat of Arms,PASS_FORMAT,Needs verification
2,class9,social_science,MCQ,The river Narmada has its source at:,QUESTION:\nWhat is the primary source of water for the river Narmada?\n\nA) Himalayas\nB) Aravallis\nC) Western Ghats\nD) Eastern Ghats\n\nANSWER:\nB) Aravallis,PASS_FORMAT,Needs verification
3,class9,maths,MCQ,Which of the following numbers cannot be represented as a terminating decimal?,QUESTION:\nWhich of the following numbers cannot be represented as a terminating decimal?\n\nA) 1/3 \nB) 2/5 \nC) 7/8 \nD) 3/2 \n\nANSWER:\nA) 1/3,PASS_FORMAT,Needs verification
4,class9,social_science,MCQ,"On the given map of France, A is marked as a place where troops entered following the King’s Command. Identify it from the following options. 1 www.vedantu.com 6","QUESTION:\nOn the given map of France, A is marked as a place where troops entered following the King's Command. Identify it from the following options. 3\n\nA) Paris\nB) Marseille\nC) Strasbourg\nD) Bordeaux\n\nANSWER:\nD) Bordeaux",PASS_FORMAT,Needs verification

In [253]:
for i, row in final_df.iterrows():
    print("=" * 80)
    print(f"Question {i+1}")
    print("Subject:", row["subject"])
    print("\nSource:")
    print(row["source_question"])
    print("\nGenerated:")
    print(row["generated_question"])

================================================================================
Question 1
Subject: science

Source:
(a) Amoeba and Euglena arc unicellular organisms. www.vedantu.com 30

Generated:
QUESTION:
Which of the following statements is true about amoebas?

A) They have multiple nuclei and chloroplasts.
B) They are photosynthetic and live in water.
C) They reproduce through binary fission but lack cellular structure.
D) They move using pseudopodia and feed on organic matter.

ANSWER:
D) They move using pseudopodia and feed on organic matter.
================================================================================
Question 2
Subject: social_science

Source:
Read the information given below and select the correct option. Most of men and women in the eighteenth century could not read or write. So, images and symbols were frequently used instead of printed words to communicate important ideas. Which of the following was a symbol of royal power?

Generated:
QUESTION:
Which of the following was a symbol of royal power during the eighteenth century?

A) The Bible
B) The Crown Jewels
C) The Royal Coat of Arms
D) The Flag of Great Britain

ANSWER:
C) The Royal Coat of Arms
================================================================================
Question 3
Subject: social_science

Source:
The river Narmada has its source at:

Generated:
QUESTION:
What is the primary source of water for the river Narmada?

A) Himalayas
B) Aravallis
C) Western Ghats
D) Eastern Ghats

ANSWER:
B) Aravallis
================================================================================
Question 4
Subject: maths

Source:
Which of the following numbers cannot be represented as a terminating decimal?

Generated:
QUESTION:
Which of the following numbers cannot be represented as a terminating decimal?

A) 1/3
B) 2/5
C) 7/8
D) 3/2

ANSWER:
A) 1/3
================================================================================
Question 5
Subject: social_science

Source:
On the given map of France, A is marked as a place where troops entered following the King’s Command. Identify it from the following options. 1 www.vedantu.com 6

Generated:
QUESTION:
On the given map of France, A is marked as a place where troops entered following the King's Command. Identify it from the following options. 3

A) Paris
B) Marseille
C) Strasbourg
D) Bordeaux

ANSWER:
D) Bordeaux
================================================================================
Question 6
Subject: social_science

Source:
Changes in power-sharing require a 1/3rd majority in both houses of Parliament. Options

Generated:
QUESTION:
What is required to change the government in India?

A) More than half of members from one house
B) More than half of members from both houses
C) More than three-fourths of members from one house
D) More than three-fourths of members from both houses

ANSWER:
B) More than half of members from both houses
================================================================================
Question 7
Subject: maths

Source:
The feasible region of a linear programming problem (LPP) is always a

Generated:
QUESTION:
What does the feasible region of a linear programming problem (LPP) represent?

A) Area where all constraints and objective function intersect
B) Region within which solutions to LPP problems exist
C) Set of points that satisfy both inequalities or equations simultaneously
D) Space defined by non-negative coefficients only

ANSWER:
B) Region within which solutions to LPP problems exist
================================================================================
Question 8
Subject: social_science

Source:
Two places A and B have been marked on the given outline map of the world. Identify then and write their correct names on the lines drawn near them

Generated:
QUESTION:
Which two countries are identified in the following outline map?

A) Japan and Russia
B) China and India
C) Brazil and Argentina
D) United States and Canada

ANSWER:
D) United States and Canada
================================================================================
Question 9
Subject: science

Source:
Plasmolysis is the process in which the cell membrane pulls away from the cell wall due to the loss of water from the cell. This happens when the cell is placed in a hypertonic solution, causing water to leave the cell by osmosis. When a plasmolysed cell is placed in water (a hypotonic solution), it absorbs water, and the cell membrane moves back toward the cell wall. This process is called deplasmolysis, and the cell becomes turgid again. OR

Generated:
QUESTION:
Which statement best describes the effect of placing a plasmolysed plant cell in a hypotonic solution?

A) The cell will absorb water and become turgid.
B) The cell will lose water and shrink.
C) The cell will remain unchanged as no water enters or exits.
D) The cell will burst due to excessive water absorption.

ANSWER:
A) The cell will absorb water and become turgid.
================================================================================
Question 10
Subject: social_science

Source:
Which of the following is known as the twin of the Narmada?

Generated:
QUESTION:
Which of the following is known as the twin of the Narmada?

A) Godavari
B) Mahanadi
C) Kaveri
D) Tungabhadra

ANSWER:
D) Tungabhadra
================================================================================
Question 11
Subject: science

Source:
Three students used three different containers

Generated:
QUESTION:
Three students used three different containers to measure water in liters. The first student filled her container to the brim and measured 50 liters. The second student poured half of what she had into a larger container but still managed to fill another smaller container with the remaining amount, which was also 25 liters. How much water did the third student use if her measurement is twice that of the second student?

A) 10 liters
B) 25 liters
C) 50 liters
D) 75 liters

ANSWER:
D) 75 liters
================================================================================
Question 12
Subject: science

Source:
Rutherford’s a-particle scattering experiment showed that: (i) Electrons have a negative charge. (ii) The mass and positive charge of the atom is concentrated in the nucleus. (iii) Neutron exists outside the nucleus. (iv) Most of the space in the atom is empty. Which of the above statements are correct?

Generated:
QUESTION:
Which statement correctly describes the findings of Rutherford's alpha particle scattering experiment?

A) Electrons have a negative charge.
B) The mass and positive charge of the atom are concentrated in the nucleus.
C) Neutrons exist outside the nucleus.
D) Most of the space in the atom is empty.

ANSWER:
B) The mass and positive charge of the atom are concentrated in the nucleus.
================================================================================
Question 13
Subject: maths

Source:
Which of the following gives the middle most observation of the data?

Generated:
QUESTION:
Which of the following gives the middle most observation of the data?

A) Median
B) Mean
C) Mode
D) Range

ANSWER:
A) Median
================================================================================
Question 14
Subject: social_science

Source:
French Revolution topic

Generated:
QUESTION:
Which event is considered to have marked the beginning of the French Revolution?

A) The storming of the Bastille
B) The signing of the Treaty of Versailles
C) The Reign of Terror
D) Napoleon's rise to power

ANSWER:
A) The storming of the Bastille

In [254]:
review_questions = [4, 5, 6, 8, 10, 11, 12, 13]

review_df = final_df.iloc[
    [q - 1 for q in review_questions]
].copy()

review_df[[
    "subject",
    "source_question",
    "generated_question",
    "quality_status"
]]

,subject,source_question,generated_question,quality_status
3,maths,Which of the following numbers cannot be represented as a terminating decimal?,QUESTION:\nWhich of the following numbers cannot be represented as a terminating decimal?\n\nA) 1/3 \nB) 2/5 \nC) 7/8 \nD) 3/2 \n\nANSWER:\nA) 1/3,PASS_FORMAT
4,social_science,"On the given map of France, A is marked as a place where troops entered following the King’s Command. Identify it from the following options. 1 www.vedantu.com 6","QUESTION:\nOn the given map of France, A is marked as a place where troops entered following the King's Command. Identify it from the following options. 3\n\nA) Paris\nB) Marseille\nC) Strasbourg\nD) Bordeaux\n\nANSWER:\nD) Bordeaux",PASS_FORMAT
5,social_science,Changes in power-sharing require a 1/3rd majority in both houses of Parliament. Options,QUESTION:\nWhat is required to change the government in India?\n\nA) More than half of members from one house\nB) More than half of members from both houses\nC) More than three-fourths of members from one house\nD) More than three-fourths of members from both houses\n\nANSWER:\nB) More than half...,PASS_FORMAT
7,social_science,Two places A and B have been marked on the given outline map of the world. Identify then and write their correct names on the lines drawn near them,QUESTION:\nWhich two countries are identified in the following outline map?\n\nA) Japan and Russia\nB) China and India\nC) Brazil and Argentina\nD) United States and Canada\n\nANSWER:\nD) United States and Canada,PASS_FORMAT
9,social_science,Which of the following is known as the twin of the Narmada?,QUESTION:\nWhich of the following is known as the twin of the Narmada?\n\nA) Godavari\nB) Mahanadi\nC) Kaveri\nD) Tungabhadra\n\nANSWER:\nD) Tungabhadra,PASS_FORMAT
10,science,Three students used three different containers,QUESTION:\nThree students used three different containers to measure water in liters. The first student filled her container to the brim and measured 50 liters. The second student poured half of what she had into a larger container but still managed to fill another smaller container with the rem...,PASS_FORMAT
11,science,Rutherford’s a-particle scattering experiment showed that: (i) Electrons have a negative charge. (ii) The mass and positive charge of the atom is concentrated in the nucleus. (iii) Neutron exists outside the nucleus. (iv) Most of the space in the atom is empty. Which of the above statements are ...,QUESTION:\nWhich statement correctly describes the findings of Rutherford's alpha particle scattering experiment?\n\nA) Electrons have a negative charge.\nB) The mass and positive charge of the atom are concentrated in the nucleus.\nC) Neutrons exist outside the nucleus.\nD) Most of the space in...,PASS_FORMAT
12,maths,Which of the following gives the middle most observation of the data?,QUESTION:\nWhich of the following gives the middle most observation of the data?\n\nA) Median \nB) Mean \nC) Mode \nD) Range \n\nANSWER:\nA) Median,PASS_FORMAT

In [255]:
review_status = {
    0: "Needs Review",
    1: "Needs Review",
    2: "Needs Review",
    3: "Reject",
    4: "Reject",
    5: "Reject",
    6: "Needs Review",
    7: "Reject",
    8: "Good Candidate",
    9: "Reject",
    10: "Reject",
    11: "Reject",
    12: "Reject",
    13: "Needs Review"
}
final_df["review_status"] = final_df.index.map(review_status)
print(final_df["review_status"].value_counts())
final_df[["subject", "review_status", "generated_question"]]

review_status
Reject            8
Needs Review      5
Good Candidate    1
Name: count, dtype: int64

,subject,review_status,generated_question
0,science,Needs Review,QUESTION:\nWhich of the following statements is true about amoebas?\n\nA) They have multiple nuclei and chloroplasts.\nB) They are photosynthetic and live in water.\nC) They reproduce through binary fission but lack cellular structure.\nD) They move using pseudopodia and feed on organic matter.\...
1,social_science,Needs Review,QUESTION:\nWhich of the following was a symbol of royal power during the eighteenth century?\n\nA) The Bible\nB) The Crown Jewels\nC) The Royal Coat of Arms\nD) The Flag of Great Britain\n\nANSWER:\nC) The Royal Coat of Arms
2,social_science,Needs Review,QUESTION:\nWhat is the primary source of water for the river Narmada?\n\nA) Himalayas\nB) Aravallis\nC) Western Ghats\nD) Eastern Ghats\n\nANSWER:\nB) Aravallis
3,maths,Reject,QUESTION:\nWhich of the following numbers cannot be represented as a terminating decimal?\n\nA) 1/3 \nB) 2/5 \nC) 7/8 \nD) 3/2 \n\nANSWER:\nA) 1/3
4,social_science,Reject,"QUESTION:\nOn the given map of France, A is marked as a place where troops entered following the King's Command. Identify it from the following options. 3\n\nA) Paris\nB) Marseille\nC) Strasbourg\nD) Bordeaux\n\nANSWER:\nD) Bordeaux"
5,social_science,Reject,QUESTION:\nWhat is required to change the government in India?\n\nA) More than half of members from one house\nB) More than half of members from both houses\nC) More than three-fourths of members from one house\nD) More than three-fourths of members from both houses\n\nANSWER:\nB) More than half...
6,maths,Needs Review,QUESTION:\nWhat does the feasible region of a linear programming problem (LPP) represent?\n\nA) Area where all constraints and objective function intersect\nB) Region within which solutions to LPP problems exist\nC) Set of points that satisfy both inequalities or equations simultaneously\nD) Spa...
7,social_science,Reject,QUESTION:\nWhich two countries are identified in the following outline map?\n\nA) Japan and Russia\nB) China and India\nC) Brazil and Argentina\nD) United States and Canada\n\nANSWER:\nD) United States and Canada
8,science,Good Candidate,QUESTION:\nWhich statement best describes the effect of placing a plasmolysed plant cell in a hypotonic solution?\n\nA) The cell will absorb water and become turgid.\nB) The cell will lose water and shrink.\nC) The cell will remain unchanged as no water enters or exits.\nD) The cell will burst d...
9,social_science,Reject,QUESTION:\nWhich of the following is known as the twin of the Narmada?\n\nA) Godavari\nB) Mahanadi\nC) Kaveri\nD) Tungabhadra\n\nANSWER:\nD) Tungabhadra
10,science,Reject,QUESTION:\nThree students used three different containers to measure water in liters. The first student filled her container to the brim and measured 50 liters. The second student poured half of what she had into a larger container but still managed to fill another smaller container with the rem...
11,science,Reject,QUESTION:\nWhich statement correctly describes the findings of Rutherford's alpha particle scattering experiment?\n\nA) Electrons have a negative charge.\nB) The mass and positive charge of the atom are concentrated in the nucleus.\nC) Neutrons exist outside the nucleus.\nD) Most of the space in...
12,maths,Reject,QUESTION:\nWhich of the following gives the middle most observation of the data?\n\nA) Median \nB) Mean \nC) Mode \nD) Range \n\nANSWER:\nA) Median
13,social_science,Needs Review,QUESTION:\nWhich event is considered to have marked the beginning of the French Revolution?\n\nA) The storming of the Bastille\nB) The signing of the Treaty of Versailles\nC) The Reign of Terror\nD) Napoleon's rise to power\n\nANSWER:\nA) The storming of the Bastille

In [256]:
llm_input_dataset = pd.read_csv(
    processed_folder / "llm_input_dataset.csv"
)
print("Columns in llm_input_dataset:")
print(llm_input_dataset.columns.tolist())

print("\nFirst 5 rows:")
display(llm_input_dataset.head())

Columns in llm_input_dataset:
['question_id', 'class', 'subject', 'session', 'question_type', 'question_text_clean', 'options', 'source_file']

First 5 rows:

,question_id,class,subject,session,question_type,question_text_clean,options,source_file
0,5,class10,computer_application,2023-24,MCQ,The acronym SSH stands for_________________.,A. Safe Shell | B. Software Shell | C. Secure Shell | D. Simple Shell,ComputerApplication-SQP -23-24.pdf
1,6,class10,computer_application,2023-24,MCQ,Which of the following is an example of social networking website?,A. wikipedia.org | B. Facebook.com | C. cbse.gov.in | D. ncert.nic.in,ComputerApplication-SQP -23-24.pdf
2,7,class10,computer_application,2023-24,MCQ,M in HTML stands for:,A. Modify | B. Management | C. Multiple | D. Markup,ComputerApplication-SQP -23-24.pdf
3,8,class10,computer_application,2023-24,MCQ,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic.",A. News group | B. Blog | C. WWW | D. e-Groups,ComputerApplication-SQP -23-24.pdf
4,9,class10,computer_application,2023-24,MCQ,Which of the following is not a valid value for the target attribute of <a> tag?,A. _blank | B. _self | C. _top | D. _bottom Page 2 of 5,ComputerApplication-SQP -23-24.pdf

In [257]:
candidate_df = llm_input_dataset[
    (llm_input_dataset["question_type"] == "MCQ") &
    (llm_input_dataset["question_text_clean"].notna()) &
    (llm_input_dataset["options"].notna()) &
    (llm_input_dataset["question_text_clean"].str.len().between(20, 250))
].copy()

# Remove questions that depend on visual material
visual_words = r"\b(map|figure|diagram|image|picture|outline map|given map)\b"
candidate_df = candidate_df[
    ~candidate_df["question_text_clean"].str.contains(
        visual_words,
        case=False,
        regex=True,
        na=False
    )
]
print("Candidate questions:", len(candidate_df))
display(
    candidate_df[
        ["question_id", "class", "subject",
         "question_text_clean", "options"]
    ].head(20))

Candidate questions: 448

C:\Users\vivek\AppData\Local\Temp\ipykernel_41040\4240940937.py:11: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ~candidate_df["question_text_clean"].str.contains(

,question_id,class,subject,question_text_clean,options
0,5,class10,computer_application,The acronym SSH stands for_________________.,A. Safe Shell | B. Software Shell | C. Secure Shell | D. Simple Shell
1,6,class10,computer_application,Which of the following is an example of social networking website?,A. wikipedia.org | B. Facebook.com | C. cbse.gov.in | D. ncert.nic.in
2,7,class10,computer_application,M in HTML stands for:,A. Modify | B. Management | C. Multiple | D. Markup
3,8,class10,computer_application,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic.",A. News group | B. Blog | C. WWW | D. e-Groups
4,9,class10,computer_application,Which of the following is not a valid value for the target attribute of <a> tag?,A. _blank | B. _self | C. _top | D. _bottom Page 2 of 5
5,10,class10,computer_application,"link, vlink, alink are attributes of___________ tag.",A. <body> | B. <a> | C. <html> | D. <img>
7,12,class10,computer_application,Which of the following tag can be used to draw a horizontal line in webpage?,A. <line> | B. <hrule> | C. <hr> | D. <rule>
8,13,class10,computer_application,"In HTML, <dl>, <dd> and <dt> tags are used to create:",A. Description list | B. Definition list | C. Detail list | D. Dynamic list
26,31,class10,computer_application,"It is an era of Internet and we as a netizen spend most of our time in the cyber world. Saumya, a class X student, is new to the cyber world. Help her in the following:","A. Suggest any two netiquettes, which she should follow in order to become a good netizen. | B. As the last day was approaching, so one of her friends has just submitted the science project by copying and pasting from the internet, without even acknowledging the original source. Is this the righ..."
27,36,class10,computer_application,Shreya wants to securely copy files between two Servers or two connected machines over the Internet. Which Protocol should she prefer for getting her task completed?,A. FTP | B. HTTP | C. SCP | D. Telnet 1
28,37,class10,computer_application,Which of the following is not an e-governance project in India?,A. www.drdo.nic.in | B. www.passport.gov.in | C. www.incometaxindia.gov.in | D. www.flipkart.com 1
29,38,class10,computer_application,Which tag besides <B> can be used to make the text bold in HTML?,A. <strong> | B. <dark> | C. <fat> | D. <I> 1
30,39,class10,computer_application,What is the full form of SMTP?,A. Simple Message Transfer Protocol | B. Secure Message Transmission Protocol | C. Simple Mail Transfer Protocol | D. Secure Mail Transmit Protocol 1 Page 2 of 7
31,40,class10,computer_application,Which protocol is used for video conferencing among multiple participants?,A. Telnet | B. Http | C. VoIP | D. SFTP 1
32,41,class10,computer_application,Select the correct option to fill in the blank: A website may consist of _____,A. Static Webpages | B. Dynamic Webpages | C. Both a and | B. D. Domain. 1
33,42,class10,computer_application,"Aman, a student of Class X, wants to create numbered list in HTML, which of the following tag should he use?",A. <UL> | B. <OL> | C. <DL> | D. <list> 1
34,43,class10,computer_application,Making a copy of your webpage on the computer is known as …………...?,A. Uploading | B. Browsing | C. Downloading | D. None of the above. 1
35,44,class10,computer_application,"Himani, a class X student, wants to remotely access a computer system far from her house. Which protocol, out of the following, should she prefer to access or log in it remotely?",A. FTP | B. SFTP | C. TCP/IP | D. TELNET 1
53,66,class10,home_science,What could be the possible reason of cross contamination in food?,A. Using same chopping boards for both vegetarian and non- vegetarian food | B. Packing and labelling of food products | C. Keeping the raw food in refrigerator | D. Cutting the food in uniform size 1 MCQ
54,67,class10,home_science,Which is the best way to save energy while working in the office?,A. Improve posture | B. Sleep in between the working hours | C. Eat balanced diet | D. Deep breath and exercise regularly 1 MCQ

In [258]:
selected_questions = candidate_df[
    candidate_df["question_id"].isin([5, 6, 7, 8, 12])
].copy()
display(
    selected_questions[
        ["question_id", "class", "subject",
         "question_text_clean", "options"]])

,question_id,class,subject,question_text_clean,options
0,5,class10,computer_application,The acronym SSH stands for_________________.,A. Safe Shell | B. Software Shell | C. Secure Shell | D. Simple Shell
1,6,class10,computer_application,Which of the following is an example of social networking website?,A. wikipedia.org | B. Facebook.com | C. cbse.gov.in | D. ncert.nic.in
2,7,class10,computer_application,M in HTML stands for:,A. Modify | B. Management | C. Multiple | D. Markup
3,8,class10,computer_application,"A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic.",A. News group | B. Blog | C. WWW | D. e-Groups
7,12,class10,computer_application,Which of the following tag can be used to draw a horizontal line in webpage?,A. <line> | B. <hrule> | C. <hr> | D. <rule>