In [94]:
import pandas as pd
import pymupdf


print("Pandas version:", pd.__version__)
print("PyMuPDF imported successfully!")

Pandas version: 3.0.5
PyMuPDF imported successfully!

In [95]:
from pathlib import Path

pdf_path=Path(r'E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf')

print('PDF exists:',pdf_path.exists())
print('PDF path:',pdf_path)

PDF exists: True
PDF path: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf

In [96]:
doc=pymupdf.open(pdf_path)

print('PDF opened successfully')
print('Number_of_pages:',len(doc))

PDF opened successfully
Number_of_pages: 41

In [97]:
page=doc[0]
text=page.get_text('text')
print(text)

www.vedantu.com
1



Class 9 Maths Sample Paper – Set 1
Max. Marks: 80                                                                                   Time Allowed: 3 hours

General Instructions:
1. This Question Paper has 5 Sections A-E.
2. Section A has 20 MCQs carrying 1 mark each.
3. Section B has 5 questions carrying 02 marks each.
4. Section C has 6 questions carrying 03 marks each.
5. Section D has 4 questions carrying 05 marks each.
6. Section E has 3 case based integrated units of assessment carrying 04 marks each.
7. All Questions are compulsory. However, an internal choice in 2 Qs of 5 marks, 2 Qs of 3
marks and 2 Questions of 2 marks has been provided. An internal choice has been provided
in the 2 marks questions of Section E.
8. Draw neat figures wherever required. Take π =22/7 wherever required if not stated.

In [98]:
for page_number,page in enumerate(doc,start=1):
    text=page.get_text('text')
    print(f"Page{page}:{len(text)} characters")

Pagepage 0 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:884 characters
Pagepage 1 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:681 characters
Pagepage 2 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:587 characters
Pagepage 3 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:424 characters
Pagepage 4 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:386 characters
Pagepage 5 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:564 characters
Pagepage 6 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:1061 characters
Pagepage 7 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:287 characters
Pagepage 8 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:911 characters
Pagepage 9 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:598 characters
Pagepage 10 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:445 characters
Pagepage 11 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:513 characters
Pagepage 12 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:917 characters
Pagepage 13 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:817 characters
Pagepage 14 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:600 characters
Pagepage 15 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:990 characters
Pagepage 16 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:855 characters
Pagepage 17 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:831 characters
Pagepage 18 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:543 characters
Pagepage 19 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:536 characters
Pagepage 20 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:672 characters
Pagepage 21 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:765 characters
Pagepage 22 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:821 characters
Pagepage 23 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:989 characters
Pagepage 24 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:661 characters
Pagepage 25 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:700 characters
Pagepage 26 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:567 characters
Pagepage 27 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:654 characters
Pagepage 28 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:438 characters
Pagepage 29 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:442 characters
Pagepage 30 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:745 characters
Pagepage 31 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:843 characters
Pagepage 32 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:677 characters
Pagepage 33 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:642 characters
Pagepage 34 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:535 characters
Pagepage 35 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:716 characters
Pagepage 36 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:805 characters
Pagepage 37 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:672 characters
Pagepage 38 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:481 characters
Pagepage 39 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:842 characters
Pagepage 40 of <E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf, doc# 80>:127 characters

In [99]:
page=doc[2]

image_info=page.get_image_info(xrefs=True)

for i,image in enumerate(image_info, start=1):
    print(
        f"Image {i}: "
        f"width={image['width']}, "
        f"height={image['height']}, "
        f"bbox={image['bbox']}"
    )

Image 1: width=1566, height=2030, bbox=(24.0, 31.67999267578125, 588.0, 762.719970703125)
Image 2: width=1566, height=2030, bbox=(24.0, 31.67999267578125, 588.0, 762.719970703125)
Image 3: width=1562, height=2025, bbox=(24.719999313354492, 32.52001953125, 587.2799682617188, 761.760009765625)
Image 4: width=1562, height=2025, bbox=(24.719999313354492, 32.52001953125, 587.2799682617188, 761.760009765625)
Image 5: width=1561, height=2025, bbox=(24.719999313354492, 32.52001953125, 587.0399780273438, 761.760009765625)
Image 6: width=408, height=412, bbox=(72.28600311279297, 173.66000366210938, 539.156005859375, 646.8300170898438)
Image 7: width=1566, height=223, bbox=(24.0, 31.200027465820312, 588.1199951171875, 111.84002685546875)
Image 8: width=1566, height=223, bbox=(24.0, 31.200027465820312, 588.1199951171875, 111.84002685546875)
Image 9: width=1566, height=223, bbox=(24.0, 31.200027465820312, 588.1199951171875, 111.84002685546875)
Image 10: width=1566, height=223, bbox=(24.0, 31.200027465820312, 588.1199951171875, 111.84002685546875)
Image 11: width=1566, height=209, bbox=(24.0, 31.199989318847656, 587.8800048828125, 106.79998779296875)
Image 12: width=10, height=56, bbox=(539.8800048828125, 98.75997924804688, 543.7200317382812, 119.03997802734375)
Image 13: width=211, height=73, bbox=(449.75, 38.11699295043945, 570.77001953125, 89.17999267578125)
Image 14: width=624, height=17, bbox=(71.9729995727539, 91.79402160644531, 539.7330322265625, 104.9000244140625)
Image 15: width=266, height=172, bbox=(116.30000305175781, 435.4000244140625, 315.79998779296875, 564.4000244140625)

In [100]:
for page_number in [1, 3, 13]:
    page = doc[page_number - 1]

    print(f"\n--- PDF Page {page_number} ---")

    image_info = page.get_image_info(xrefs=True)

    for i, image in enumerate(image_info, start=1):
        print(
            f"Image {i}: "
            f"width={image['width']}, "
            f"height={image['height']}"
        )

--- PDF Page 1 ---
Image 1: width=1566, height=2030
Image 2: width=1566, height=2030
Image 3: width=1562, height=2025
Image 4: width=1562, height=2025
Image 5: width=1561, height=2025
Image 6: width=408, height=412
Image 7: width=1566, height=223
Image 8: width=1566, height=223
Image 9: width=1566, height=223
Image 10: width=1566, height=223
Image 11: width=1566, height=209
Image 12: width=10, height=56
Image 13: width=211, height=73
Image 14: width=624, height=17

--- PDF Page 3 ---
Image 1: width=1566, height=2030
Image 2: width=1566, height=2030
Image 3: width=1562, height=2025
Image 4: width=1562, height=2025
Image 5: width=1561, height=2025
Image 6: width=408, height=412
Image 7: width=1566, height=223
Image 8: width=1566, height=223
Image 9: width=1566, height=223
Image 10: width=1566, height=223
Image 11: width=1566, height=209
Image 12: width=10, height=56
Image 13: width=211, height=73
Image 14: width=624, height=17
Image 15: width=266, height=172

--- PDF Page 13 ---
Image 1: width=1566, height=2030
Image 2: width=1566, height=2030
Image 3: width=1562, height=2025
Image 4: width=1562, height=2025
Image 5: width=1561, height=2025
Image 6: width=408, height=412
Image 7: width=1566, height=223
Image 8: width=1566, height=223
Image 9: width=1566, height=223
Image 10: width=1566, height=223
Image 11: width=1566, height=209
Image 12: width=10, height=56
Image 13: width=211, height=73
Image 14: width=624, height=17
Image 15: width=286, height=186

In [101]:
from pathlib import Path
raw_folder = Path(r"E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw")
pdf_files = list(raw_folder.rglob("*.pdf"))
print("Total PDF files found:", len(pdf_files))

for pdf in pdf_files:
    print(pdf)

Total PDF files found: 36
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP-24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP -24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP -24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\science\Science-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\science\Science-SQP -24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\science\Science-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\social_science\SocialScience-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\social_science\SocialScience-SQP -24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\social_science\SocialScience-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper 2026-27 (Mock Paper 6).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper Set 3 for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper Set 4 (2026-27) – FREE PDF with Solutions.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 2) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Sample Paper Class 9 Maths 2026-27 _ Mock Paper 7 PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper 2026-27 Mock Test Set 6.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper 2026-27 _ Mock Paper 7 PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 4 (2026-27) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 5 (2026-27) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\Class 9 Science Sample Paper Set 3 Download FREE PDF for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper 2025-26 (Mock Paper 6).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper 2026-27 (Mock Paper 7).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper Set 1 FREE PDF for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf

In [102]:
all_pages=[]
for pdf_path in pdf_files:
    doc=pymupdf.open(pdf_path)

    for page_number,page in enumerate(doc,start=1):
        text=page.get_text("text").strip()
        all_pages.append({
            "source_file": pdf_path.name,
            "source_path": str(pdf_path),
            "page_number": page_number,
            "text": text,
            "text_length": len(text)
        })

all_pages

[{'source_file': 'ComputerApplication-SQP -23-24.pdf',
  'source_path': 'E:\\COLLEGEPUR\\WORKS\\AIML work\\CBSE_AI_Assessment\\data\\raw\\class10\\computer_application\\ComputerApplication-SQP -23-24.pdf',
  'page_number': 1,
  'text': 'Page 1 of 5  \n  \nClass: X Session: 2023-24  \nComputer Applications (Code 165)  \nSample Question Paper (Theory)  \nMaximum Marks: 50    \n  \n  \n  \n  \n  \n  Time Allowed: 2 hours  \n  \nGeneral Instructions:   \n1. This Question Paper has 5 Sections A-E.   \n2. All Questions are compulsory. However, internal choices have been provided in some of the \nquestions.   \n3. Section A has 12 questions carrying 01 mark each.   \n4. Section B has 7 Short Answer (SA-I) type questions carrying 02 marks each.   \n5. Section C has 4 Short Answer (SA-II) type questions carrying 03 marks each.   \n6. Section D has 1 Long Answer (LA) type question carrying 04 marks.   \n7. Section E has 2 Source based /Case-based /Passage based Questions carrying 04 marks each.  \n \nSECTION – A  \n(All questions are compulsory)   \n \n1. The acronym SSH stands for_________________.  \na. Safe Shell \nb. Software Shell  \nc. Secure Shell \nd. Simple Shell \n2. Which of the following is an example of social networking website?  \na. wikipedia.org \nb. Facebook.com \nc. cbse.gov.in \nd. ncert.nic.in  \n3. M in HTML stands for: \na. Modify \nb. Management  \nc. Multiple \nd. Markup \n4. A _____________ is an online journal or informational website run by an individual, \ngroup, or corporation that offers regularly updated content about a topic.   \na. News group  \nb. Blog \nc. WWW \nd. e-Groups \n5. Which of the following is not a valid value for the target attribute of <a> tag? \na. _blank \nb. _self  \nc. _top \nd. _bottom',
  'text_length': 1471},
 {'source_file': 'ComputerApplication-SQP -23-24.pdf',
  'source_path': 'E:\\COLLEGEPUR\\WORKS\\AIML work\\CBSE_AI_Assessment\\data\\raw\\class10\\computer_application\\ComputerApplication-SQP -23-24.pdf',
  'page_number': 2,
  'text': 'Page 2 of 5  \n  \n6. link, vlink, alink are attributes of___________ tag. \n   a.   <body>  \nb. <a>  \nc. <html>  \nd. <img> \n  \n7. The_______ attribute of <img> tag specifies an alternate text for an image, if the image \ncannot be displayed. \na. alt  \nb. text \nc. alternate  \nd. msg \n      \n8. Which of the following tag can be used to draw a horizontal line in webpage? \n                    a. <line>  \n                    b. <hrule>  \n                    c. <hr>  \n                    d. <rule>  \n \n9. In HTML, <dl>, <dd> and <dt> tags are used to create: \n   a. Description list \n   b. Definition list \n   c. Detail list \n   d. Dynamic list \n \n10. A software _________ is a legal instrument governing the use or redistribution of \nsoftware.  \n   a. license  \n   b. law \n   c. document  \n   d. piracy \n  \nQuestions No-11 & 12 are Assertion and Reason types. Each question consists of two \nstatements, namely, Assertion (A) and Reason (R). Select the most suitable option \nconsidering the Assertion & Reason.  \n  \n11.   \nAssertion (A): Search engine is a hardware device that searches for any websites on the World \nWide Web. \nReason (R): Google Search and Microsoft’s Bing are two popular search engines.  \n(a) Both Assertion (A) and Reason (R) are true and Reason (R) is a correct explanation of \nAssertion (A).  \n(b) Both Assertion (A) and Reason (R) are true but Reason (R) is not a correct explanation of \nAssertion (A). \n(c) Assertion (A) is true and Reason (R) is false.  \n(d) Assertion (A) is false and Reason (R) is true.',
  'text_length': 1528},
 {'source_file': 'ComputerApplication-SQP -23-24.pdf',
  'source_path': 'E:\\COLLEGEPUR\\WORKS\\AIML work\\CBSE_AI_Assessment\\data\\raw\\class10\\computer_application\\ComputerApplication-SQP -23-24.pdf',
  'page_number': 3,
  'text': 'Page 3 of 5  \n  \n12.   \nAssertion (A): CSS saves a lot of work. It can control the layout of multiple web pages all at \nonce. \nReason (R): All the required style settings can be stored in an external stylesheet and a link \nto it can be added in the <head> section of each web page. \n(a) Both Assertion (A) and Reason (R) are true and Reason (R) is a correct explanation of \nAssertion (A).  \n(b) Both Assertion (A) and Reason (R) are true but Reason (R) is not a correct explanation of \nAssertion (A).  \n(c) Assertion (A) is true and Reason (R) is false.  \n(d) Assertion (A) is false and Reason (R) is true.  \n \nSECTION –B  \n(2 marks each)  \n13. Write any two points of comparison in between SMS and MMS.  \n14. What is e-Learning? Mention its two main advantages.  \nOR \n   Briefly discuss the role of e-governance in any country’s growth and development. \n  \n15. Compare 3G and 4G mobile technologies on any two major points. \n \n16. Which software are termed as open-source software? Name any two such software. \nOR \nWhat do you understand by the term Intellectual property right? Discuss briefly. \n  \n17. Mention any two purposes of using comments while designing a HTML webpage.   \n  \n18. Twisha has got confused with a few tags and their attributes. Help her match the tag with  \n      correct attribute. \n1. \n<font>  \n \n \n       i. align \n2. \n<a> \n \n \n \n       ii. face \n3. \n<h1>  \n \n \n       iii. colspan \n4. \n<td> \n \n \n \n       iv. href \n \nOR \n  \n    Mention any two attributes of <font> tag along with their purposes.   \n  \n19. Write suitable html statements to display the following text on a webpage in appropriate \nsubscript and superscript form: \na. CO2 \nb. X2  \nSECTION –C  \n(3 marks each)  \n20. Ronaldo, a web designer in a start-up company, wants to give headings in a webpage through  \n    <h1> tag. Additionally, he wants to implement following styles on all the <h1> tag of the  \n    same webpage at one go.  \n\uf0b7 Color-blue \n\uf0b7 Background color-yellow \n\uf0b7 border of the heading - 2px in red',
  'text_length': 2003},
 {'source_file': 'ComputerApplication-SQP -23-24.pdf',
  'source_path': 'E:\\COLLEGEPUR\\WORKS\\AIML work\\CBSE_AI_Assessment\\data\\raw\\class10\\computer_application\\ComputerApplication-SQP -23-24.pdf',
  'page_number': 4,
  'text': 'Page 4 of 5  \n  \nHe is not able to implement the above-mentioned additional styles of <h1> tag through \nregular html code. Suggest him a way out and also help him in writing the code for same.   \n \n21. Rajat, a web developer, wants to show a video named “tiger.mp4” in dimensions of \n300px width and 200px height on the web page. Help Rajat by writing its html code. \n  \n22. Abhilasha has just designed a web page. At the end of the web page, she wants to insert an \nimage “next.jpg”.  \nShe needs to link another web page with this image, i.e., whenever anyone click on the \nimage “next.jpg”, another web page named “second.html” should open. Help her in writing \nthe code to achieve it.    \n Note: Assume that image and both the web pages are stored in the same folder.  \nOR  \nWrite HTML code to design the content of the web page in the form of lists as shown \nbelow: \n \n \n \n23. What do you understand by the term “Digital Divide”? Mention any two measures to \novercome it. \nSECTION –D  \n(4 marks)  \n24. Customer Analytics firm needs to design a survey form as shown below: \n \n \nWrite the suitable HTML code to design it.  \nOR \nObserve the screenshot of the given web page:',
  'text_length': 1175},
 {'source_file': 'ComputerApplication-SQP -23-24.pdf',
  'source_path': 'E:\\COLLEGEPUR\\WORKS\\AIML work\\CBSE_AI_Assessment\\data\\raw\\class10\\computer_application\\ComputerApplication-SQP -23-24.pdf',
  'page_number': 5,
  'text': 'Page 5 of 5  \n  \n \nWrite suitable HTML code to design it. \n \n \n \nSECTION - E  \n(4 marks each)  \n \nCase Study -1    \n \n25. Sanchay, has recently joined the Global Network company as a network trainee. Help \nSanchay by suggesting the best suitable answers for the following issues which needs to \nresolved: \na. Company wants to engage employees in some online fun filled activities to \nstrengthen their inter-personal skills. Suggest any two popular video \nconferencing software to be used for the same. \nb. Company wants employees to upgrade themselves by exploring internet about \nlatest happenings in the networking field. Suggest any two suitable web \nbrowsers for the same. \nc. Sometimes few of the employee needs to remotely login to their office PC from \ntheir home. Suggest any one popular software and the protocol being used for \nthe same. \nd. Company wants its employees to be safe while entering their login credentials \nand bank account details on the internet. Out of http and https, which protocols \nshould be preferred and why? \nCase Study -2 \n26. It is an era of Internet and we as a netizen spend most of our time in the cyber world. \nSaumya, a class X student, is new to the cyber world. Help her in the following:  \na. Suggest any two netiquettes, which she should follow in order to become a \ngood netizen. \nb. As the last day was approaching, so one of her friends has just submitted the \nscience project by copying and pasting from the internet, without even \nacknowledging the original source. Is this the right act or wrong? Name the \nterm which is being used for this act. \nc. E-commerce is growing exponentially and so is the risk involved in it. Mention \nany two common E-commerce frauds in order to make Saumya aware about it. \nd. Suggest her any two precautions to be taken while using E-commerce.',
  'text_length': 1825},
 {'source_file': 'ComputerApplication-SQP-24-25.pdf',
  'source_path': 'E:\\COLLEGEPUR\\WORKS\\AIML work\\CBSE_AI_Assessment\\data\\raw\\class10\\computer_application\\ComputerApplication-SQP-24-25.pdf',
  'page_number': 1,
  'text': 'Page 1 of 7 \n \nSample Question Paper (Theory) \nComputer Applications (Code 165) \nClass: X Session: 2024-25  \n \nMaximum Marks: 50 \nTime Allowed: 2 hours \n \nGeneral Instructions: \n1. This Question Paper has 5 Sections A-E. \n2. All Questions are compulsory. However, internal choices have been provided in some of the questions. \n3. Section A has 12 questions carrying 01 mark each. \n4. Section B has 7 Short Answer (SA-I) type questions carrying 02 marks each. \n5. Section C has 4 Short Answer (SA-II) type questions carrying 03 marks each. \n6. Section D has 1 Long Answer (LA) type question carrying 04 marks. \n7. Section E has 2 Source based /Case-based /Passage based Questions carrying 04 marks each. \n \n \nSection – A (All questions are compulsory) \n1.  Shreya wants to securely copy files between two Servers or two connected machines \nover the Internet. Which Protocol should she prefer for getting her task completed? \nA. FTP \nB. HTTP \nC. SCP \nD. Telnet  \n1 \n2.  Which of the following is not an e-governance project in India? \nA. www.drdo.nic.in \nB. www.passport.gov.in \nC. www.incometaxindia.gov.in \nD. www.flipkart.com \n1 \n3.  Which tag besides <B> can be used to make the text bold in HTML? \nA. <strong> \nB. <dark> \nC. <fat> \nD. <I> \n1 \n4.  What is the full form of SMTP? \nA. Simple Message Transfer Protocol \nB. Secure Message Transmission Protocol \nC. Simple Mail Transfer Protocol \nD. Secure Mail Transmit Protocol \n1',
  'text_length': 1429},
 {'source_file': 'ComputerApplication-SQP-24-25.pdf',
  'source_path': 'E:\\COLLEGEPUR\\WORKS\\AIML work\\CBSE_AI_Assessment\\data\\raw\\class10\\computer_application\\ComputerApplication-SQP-24-25.pdf',
  'page_number': 2,
  'text': 'Page 2 of 7 \n \n5.  Which protocol is used for video conferencing among multiple participants? \nA. Telnet \nB. Http \nC. VoIP \nD. SFTP \n1 \n6.  Select the correct option to fill in the blank: \nA website may consist of _____ \nA. Static Webpages \nB. Dynamic Webpages \nC. Both a and b. \nD. Domain. \n1 \n7.  Aman, a student of Class X, wants to create numbered list in HTML, which of the \nfollowing tag should he use? \nA. <UL> \nB. <OL> \nC. <DL> \nD. <list> \n1 \n8.  Making a copy of your webpage on the computer is known as   …………...? \nA. Uploading \nB. Browsing \nC. Downloading \nD. None of the above. \n1 \n9.  Himani, a class X student, wants to remotely access a computer system far from her \nhouse. Which protocol, out of the following, should she prefer to access or log in it \nremotely? \nA. FTP \nB. SFTP \nC. TCP/IP \nD.  TELNET \n1 \n10.  Anshu, a class X student, is writing CSS code for making all <span> elements bold. \nChoose the correct code for getting the desired output from the following options: \nA. span{text-size:bold} \nB. span {font-weight:bold} \nC. <span style="font-size:bold"> \nD. <span style="text-size:bold"> \n1',
  'text_length': 1118},
 {'source_file': 'ComputerApplication-SQP-24-25.pdf',
  'source_path': 'E:\\COLLEGEPUR\\WORKS\\AIML work\\CBSE_AI_Assessment\\data\\raw\\class10\\computer_application\\ComputerApplication-SQP-24-25.pdf',
  'page_number': 3,
  'text': 'Page 3 of 7 \n \nQuestions No-11 & 12 are Assertion and Reason types. Each question consists of two statements, namely \nAssertion (A) and Reason (R). Select the most suitable option considering the Assertion & Reason. \nA. Both Assertion (A) and Reason (R) are true and Reason (R) is a correct explanation of Assertion (A). \nB. Both Assertion (A) and Reason (R) are true but Reason (R) is not a correct explanation of Assertion \n(A). \nC. Assertion (A) is true and Reason (R) is false. \nD. Assertion (A) is false and Reason (R) is true. \n11.  Assertion (A) :  A set of rules, used over the networks, is called a Protocol. \nReason (R)    : HTML is an example of a Protocol. \n1 \n12.  Assertion (A) :Chat and e-mail are live/real time conversation between \npeople/machines. \nReason    (R)    :  We have to be online in both \n1 \nSection – B \n13.  Mishika, a class X student, wants to use a software but does not want to pay for it. \nWhich type of software can she use? Write one example of this type of software. \n2 \n14.  A) Write any two differences between e-Banking and e-Commerce. \nOR \nB) What is e-learning? Name any one e-learning platform. \n2 \n15.  State whether the following statements are True or False: \n \nI) HTML file extension is .tml. \n    II) Rowspan attribute is used to make a cell span multiple rows. \n    III) Unordered list type creates a bulleted list. \n    IV) HREF Stands for hyper reference. \n2 \n16.  A) Your best friend emails you and tells you that he/she has created a webpage on \nan internet site having URL as: www.children.com/india/~abc.html  \nNow you want to create a link to this web page from your web page. Write the \nHTML code to do this. \nOR \nB) \nI) \nWrite HTML code to display Horizontal line of red colour.  \nII) \nWrite HTML Code to create a paragraph whose text colour is blue. \n2 \n17.  What is the purpose of HTML forms? Write HTML Code to create a Textbox in an HTML \nform. \n2 \n18.  A) An incomplete CSS code within <head> . . . </head> is given below. Complete \nthis code by filling in the blanks as per the specifications that follow: \n<head> \n2',
  'text_length': 2081},
 {'source_file': 'ComputerApplication-SQP-24-25.pdf',
  'source_path': 'E:\\COLLEGEPUR\\WORKS\\AIML work\\CBSE_AI_Assessment\\data\\raw\\class10\\computer_application\\ComputerApplication-SQP-24-25.pdf',
  'page_number': 4,
  'text': 'Page 4 of 7 \n \n<style> \nbody {________ : blue;  }     <!--line 1 --> \np {   \n ________: green;             <!--line 2 --> \n ________: Dotum;             <!--line 3 --> \n} \n_____                         <!--line 4 --> \n{                              \nColor : black;                                       \n} \n</style> \n</head> \n \nLine 1: Page background colour should be Blue. \nLine 2: Colour of the Paragraph text should be green. \nLine 3: Font family of the Paragraph text should be Dotum. \nLine 4: The biggest heading should be black in colour. \nOR \nB) Hemant, a class X Student, is writing HTML code to create ordered and unordered \nlists for a webpage as follows: \n<html>  \n<body bgcolor="yellow"> \n<h1>My First Heading  <_____>   <!-- line 1 --> \n<p> \n<font color="red" size="5" \n    ______="Times New Roman">   <!-- line 2 --> \nSOME STATES IN INDIA \n</p> \n<ul> \n<li>DELHI: <______>  \n        <!-- line 3 --> \n<li>MUMBAI    </li> \n<_____>  \n     \n       <!-- line 4 --> \n \nBased on the above code fill in the blanks given in line 1, line2, line 3, and line 4 so \nthat Hemant’s webpage displays output correctly? \n19.  Write any two differences between SMS and MMS. \n2 \nSection – C',
  'text_length': 1184},
 {'source_file': 'ComputerApplication-SQP-24-25.pdf',
  'source_path': 'E:\\COLLEGEPUR\\WORKS\\AIML work\\CBSE_AI_Assessment\\data\\raw\\class10\\computer_application\\ComputerApplication-SQP-24-25.pdf',
  'page_number': 5,
  'text': 'Page 5 of 7 \n \n20.  The following HTML statements are not written properly. Re-write the correct \nstatements with underlined corrections. The desired purpose of each statement is \nmentioned under it. \nI. \n<BODY color="red">  \n<!--Page background color should be red--> \nII.   <FONT  type="arial">  \n<!--Type of Font should be Arial--> \nIII.  <img source="img_girl.jpg" size="500" height="600"> \n<!—Image source should be img_girl.jpg, width and \nheight both should be 500--> \n3 \n21.  Consider the URL:  https://www.cbse.gov.in   and answer the following questions: \nI.    Which component identifies the protocol? \nII.   What is the significance of "s" in https? \nIII.  Expand the terms URL and WWW? \n3 \n22.  A) Write any two ways to add an audio file in a web page using HTML? Explain with \nsample code. \nOR \nB) Write any two ways to add a video file in a web page using HTML? Explain with \nsample code. \n3 \n23.  Write suitable HTML statements to display the following text on a webpage: \nI) \nNH3       \nII) \nX3      \nIII) \n(A+B)3 \n3 \nSection – D \n24.  A) Write the HTML code to design the web page as shown below: - \n4',
  'text_length': 1119},
 {'source_file': 'ComputerApplication-SQP-24-25.pdf',
  'source_path': 'E:\\COLLEGEPUR\\WORKS\\AIML work\\CBSE_AI_Assessment\\data\\raw\\class10\\computer_application\\ComputerApplication-SQP-24-25.pdf',
  'page_number': 6,
  'text': 'Page 6 of 7 \n \n              \n \n \n \n \n \n \n \n \n \n \nOR \nB) Write the HTML code to design the web page as shown below (Table border \nshould be 2, height=100 and width=300 with cellpadding =20): - \n                    \n \n \n \n \n \n \n \n \nSection – E \n25.  Mr. Anek comes from a village, which recently started seeing the digital revolution, \nand now the people of his village have access to the internet. They can shop online, \nmake payments online, sell online and so on.  Anek is also excited with these new \nchanges. He ordered some items online and entered his bank card details on the \nwebpage to make the payment. \nBut still after passing of the promised due date, he has not received his ordered \nitems. There is no way to contact the company as phones are unreachable and emails \nare not being responded. He also noticed after some days that someone is sending \nemails on his behalf, using his personal data. \n \n4',
  'text_length': 914},
 {'source_file': 'ComputerApplication-SQP-24-25.pdf',
  'source_path': 'E:\\COLLEGEPUR\\WORKS\\AIML work\\CBSE_AI_Assessment\\data\\raw\\class10\\computer_application\\ComputerApplication-SQP-24-25.pdf',
  'page_number': 7,

In [103]:
import shutil
tesseract_path=shutil.which("tesseract")
print("Tesseract path:",tesseract_path)

Tesseract path: None

In [104]:
import pytesseract
print('pytesseract installed succesfully')

pytesseract installed succesfully

In [105]:
import shutil
tesseract_path=shutil.which("tesseract")
print("Tesseract path:",tesseract_path)

Tesseract path: None

In [106]:
import pytesseract
pytesseract.pytesseract.tesseract_cmd= r"C:\Program Files\Tesseract-OCR\tesseract.exe"
print(pytesseract.get_tesseract_version())

5.5.0.20241111

In [107]:
for i, pdf in enumerate(pdf_files[:10]):
    print(i, pdf)

0 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP -23-24.pdf
1 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP-24-25.pdf
2 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP-25-26.pdf
3 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP -23-24.pdf
4 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP -24-25.pdf
5 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP-25-26.pdf
6 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP -23-24.pdf
7 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP -24-25.pdf
8 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP-25-26.pdf
9 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\science\Science-SQP -23-24.pdf

In [108]:
class9_pdfs = [
    pdf for pdf in pdf_files
    if "class9" in [part.lower() for part in pdf.parts]
]

print("Class 9 PDFs:", len(class9_pdfs))

for pdf in class9_pdfs:
    print(pdf)

Class 9 PDFs: 21
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper 2026-27 (Mock Paper 6).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper Set 3 for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper Set 4 (2026-27) – FREE PDF with Solutions.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 2) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Sample Paper Class 9 Maths 2026-27 _ Mock Paper 7 PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper 2026-27 Mock Test Set 6.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper 2026-27 _ Mock Paper 7 PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 4 (2026-27) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 5 (2026-27) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\Class 9 Science Sample Paper Set 3 Download FREE PDF for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper 2025-26 (Mock Paper 6).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper 2026-27 (Mock Paper 7).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper Set 1 FREE PDF for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf

In [109]:
from PIL import Image
import io
pdf_path = class9_pdfs[0]
doc = pymupdf.open(pdf_path)
page = doc[0]
pix = page.get_pixmap(dpi=200)

image = Image.open(io.BytesIO(pix.tobytes("png")))
ocr_text = pytesseract.image_to_string(image)
print(ocr_text[:2000])
doc.close()

\Wedanti

LIVE ONLINE TUTORING

CBSE Class 9 Subject Maths Sample Question Paper — Set 6

General Instructions

V There are 90 questions in total. All questions are compulsory.

V The paper is divided into Sections A, B, C, D, and E.
V Internal choice follows CBSE norms.

V Questions strictly follow the current CBSE syllabus.

V Include the total marks and time duration based on the questions.

SECTION A — Objective Type Questions

(Include NEW MCQs and Assertion-Reason questions)

1. Which of the following numbers cannot be represented as a terminating decimal?

(a) 3/5
(b) 2/7
(c)1/4
(d) %

2. The value of (81)°"“ is:
(a) 9

(b) 27

(c) 64

(d) 16

3. If ais a root of the equation x’ - 2x + 1= 0, then ais:
(a) only

(b) -lonly

(c) both land -1

(d)o

4. Which of the following is a binomial?
(a)x*

(b) x +2

(c) 4x

(d) x? +x+1

www.vedantu.com

In [110]:
all_extracted_pages=[]

for pdf_path in pdf_files:
      # Find class from folder name
    class_name = "class9" if "class9" in [part.lower() for part in pdf_path.parts] else "class10"

    # Find subject from folder name
    subject = pdf_path.parent.name

    print(f"Processing: {class_name} | {subject} | {pdf_path.name}")

    doc = pymupdf.open(pdf_path)

    for page_number, page in enumerate(doc, start=1):

        # First try normal PDF text extraction
        native_text = page.get_text("text").strip()

        # OCR only when native text is very little
        ocr_text = ""

        if len(native_text) < 150:

            pix = page.get_pixmap(dpi=200)

            image = Image.open(
                io.BytesIO(pix.tobytes("png"))
            )

            ocr_text = pytesseract.image_to_string(image).strip()

        # Choose the better available text
        final_text = native_text if len(native_text) >= 150 else ocr_text

        all_extracted_pages.append({
            "class": class_name,
            "subject": subject,
            "source_file": pdf_path.name,
            "page_number": page_number,
            "native_text": native_text,
            "ocr_text": ocr_text,
            "final_text": final_text
        })

    doc.close()

print("\nTotal pages processed:", len(all_extracted_pages))

Processing: class10 | computer_application | ComputerApplication-SQP -23-24.pdf
Processing: class10 | computer_application | ComputerApplication-SQP-24-25.pdf
Processing: class10 | computer_application | ComputerApplication-SQP-25-26.pdf
Processing: class10 | home_science | HomeScience-SQP -23-24.pdf
Processing: class10 | home_science | HomeScience-SQP -24-25.pdf
Processing: class10 | home_science | HomeScience-SQP-25-26.pdf
Processing: class10 | maths | MathsStandard-SQP -23-24.pdf
Processing: class10 | maths | MathsStandard-SQP -24-25.pdf
Processing: class10 | maths | MathsStandard-SQP-25-26.pdf
Processing: class10 | science | Science-SQP -23-24.pdf
Processing: class10 | science | Science-SQP -24-25.pdf
Processing: class10 | science | Science-SQP-25-26.pdf
Processing: class10 | social_science | SocialScience-SQP -23-24.pdf
Processing: class10 | social_science | SocialScience-SQP -24-25.pdf
Processing: class10 | social_science | SocialScience-SQP-25-26.pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Paper 2026-27 (Mock Paper 6).pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Paper Set 3 for 2026-27.pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Paper Set 4 (2026-27) – FREE PDF with Solutions.pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Question Paper (Set 2) 2026-27 FREE PDF.pdf
Processing: class9 | maths | CBSE Sample Paper Class 9 Maths 2026-27 _ Mock Paper 7 PDF.pdf
Processing: class9 | maths | Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper 2026-27 Mock Test Set 6.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper 2026-27 _ Mock Paper 7 PDF.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper Set 4 (2026-27) - FREE PDF Download.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper Set 5 (2026-27) - FREE PDF Download.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
Processing: class9 | science | Class 9 Science Sample Paper Set 3 Download FREE PDF for 2026-27.pdf
Processing: class9 | social_science | CBSE Class 9 Social Science Sample Paper 2025-26 (Mock Paper 6).pdf
Processing: class9 | social_science | CBSE Class 9 Social Science Sample Paper 2026-27 (Mock Paper 7).pdf
Processing: class9 | social_science | CBSE Class 9 Social Science Sample Paper Set 1 FREE PDF for 2026-27.pdf
Processing: class9 | social_science | CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
Processing: class9 | social_science | Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
Processing: class9 | social_science | Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
Processing: class9 | social_science | Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf

Total pages processed: 605

In [111]:
df_pages = pd.DataFrame(all_extracted_pages)

print("Total page rows:", len(df_pages))
print("Total PDFs:", df_pages["source_file"].nunique())

print("\nClass-wise pages:")
print(df_pages["class"].value_counts())

print("\nSubject-wise pages:")
print(df_pages["subject"].value_counts())

Total page rows: 605
Total PDFs: 36

Class-wise pages:
class
class9     466
class10    139
Name: count, dtype: int64

Subject-wise pages:
subject
maths                   195
science                 186
social_science          186
computer_application     19
home_science             19
Name: count, dtype: int64

In [112]:
print("Pages that used OCR:", (df_pages["ocr_text"] != "").sum())
print("Pages with no final text:", (df_pages["final_text"].str.strip() == "").sum())

Pages that used OCR: 14
Pages with no final text: 0

In [113]:
import re
import pandas as pd

question_rows = []

for (class_name, subject, source_file), group in df_pages.groupby(
    ["class", "subject", "source_file"]
):
    
    group = group.sort_values("page_number")
    full_text = "\n".join(group["final_text"].fillna(""))

    # Remove text before the first section
    section_match = re.search(
        r"\bSECTION\s*[-–]?\s*[A-E]\b",
        full_text,
        flags=re.IGNORECASE
    )

    if section_match:
        full_text = full_text[section_match.start():]

    # Find numbered questions: 1. / 1) / 2. / 2)
    pattern = r"(?m)^\s*(\d{1,3})[\.\)]\s+(.*?)(?=^\s*\d{1,3}[\.\)]\s+|\Z)"

    matches = re.finditer(
        pattern,
        full_text,
        flags=re.MULTILINE | re.DOTALL
    )

    for match in matches:
        question_number = int(match.group(1))
        question_text = re.sub(r"\s+", " ", match.group(2)).strip()

        # Ignore very short accidental matches
        if len(question_text) < 20:
            continue

        session_match = re.search(r"(20\d{2}-\d{2})", source_file)
        session = session_match.group(1) if session_match else "Unknown"

        question_rows.append({
            "question_id": len(question_rows) + 1,
            "class": class_name,
            "subject": subject,
            "session": session,
            "source_file": source_file,
            "question_number": question_number,
            "question_text": question_text,
            "answer": ""
        })

question_df = pd.DataFrame(question_rows)

print("Total questions extracted:", len(question_df))
display(question_df.head(10))

Total questions extracted: 1891

,question_id,class,subject,session,source_file,question_number,question_text,answer
0,1,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,Section B has 7 Short Answer (SA-I) type quest...,
1,2,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Section C has 4 Short Answer (SA-II) type ques...,
2,3,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,Section D has 1 Long Answer (LA) type question...,
3,4,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,7,Section E has 2 Source based /Case-based /Pass...,
4,5,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,1,The acronym SSH stands for_________________. a...,
5,6,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,2,Which of the following is an example of social...,
6,7,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,3,M in HTML stands for: a. Modify b. Management ...,
7,8,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,A _____________ is an online journal or inform...,
8,9,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Which of the following is not a valid value fo...,
9,10,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,"link, vlink, alink are attributes of__________...",

In [114]:
from pathlib import Path

processed_folder = raw_folder.parent / "processed"
processed_folder.mkdir(exist_ok=True)

print("Processed folder:", processed_folder)

Processed folder: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed

In [115]:
output_file = processed_folder / "question_dataset.csv"

question_df.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("Dataset saved:")
print(output_file)

Dataset saved:
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\question_dataset.csv

In [116]:
# Create a richer question-bank dataset from the extracted questions

question_bank = question_df.copy()

# Section
question_bank["section"] = ""

# Question type
question_bank["question_type"] = ""

# Options
question_bank["options"] = ""

# Marks
question_bank["marks"] = ""

# Topic - will be populated during subject-wise cleaning
question_bank["topic"] = ""

# Difficulty - will be assigned later
question_bank["difficulty"] = ""

# Diagram/image indicator
question_bank["has_diagram"] = False

# Answer is unavailable in the current raw question set
question_bank["correct_answer"] = ""

# Explanation is unavailable in the current raw question set
question_bank["answer_explanation"] = ""

print("Rows:", len(question_bank))
print("Columns:")
print(question_bank.columns.tolist())

display(question_bank.head(10))

Rows: 1891
Columns:
['question_id', 'class', 'subject', 'session', 'source_file', 'question_number', 'question_text', 'answer', 'section', 'question_type', 'options', 'marks', 'topic', 'difficulty', 'has_diagram', 'correct_answer', 'answer_explanation']

,question_id,class,subject,session,source_file,question_number,question_text,answer,section,question_type,options,marks,topic,difficulty,has_diagram,correct_answer,answer_explanation
0,1,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,Section B has 7 Short Answer (SA-I) type quest...,,,,,,,,False,,
1,2,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Section C has 4 Short Answer (SA-II) type ques...,,,,,,,,False,,
2,3,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,Section D has 1 Long Answer (LA) type question...,,,,,,,,False,,
3,4,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,7,Section E has 2 Source based /Case-based /Pass...,,,,,,,,False,,
4,5,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,1,The acronym SSH stands for_________________. a...,,,,,,,,False,,
5,6,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,2,Which of the following is an example of social...,,,,,,,,False,,
6,7,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,3,M in HTML stands for: a. Modify b. Management ...,,,,,,,,False,,
7,8,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,A _____________ is an online journal or inform...,,,,,,,,False,,
8,9,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Which of the following is not a valid value fo...,,,,,,,,False,,
9,10,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,"link, vlink, alink are attributes of__________...",,,,,,,,False,,

In [117]:
import re

def detect_question_type(text):
    text_lower = text.lower()

    if re.search(r"\(a\).*?\(b\).*?\(c\).*?\(d\)", text, re.DOTALL):
        return "MCQ"
    elif "assertion" in text_lower and "reason" in text_lower:
        return "Assertion-Reason"
    elif "case-based" in text_lower or "passage" in text_lower:
        return "Case-Based"
    else:
        return "Short/Long Answer"


def extract_options(text):
    matches = re.findall(
        r"\([a-dA-D]\)\s*(.*?)(?=\s*\([a-dA-D]\)|$)",
        text,
        re.DOTALL
    )

    return " | ".join(x.strip() for x in matches)


question_bank["question_type"] = question_bank["question_text"].apply(
    detect_question_type
)

question_bank["options"] = question_bank["question_text"].apply(
    extract_options
)

display(
    question_bank[
        ["question_id", "class", "subject",
         "question_number", "question_type", "options",
         "question_text"]
    ].head(10)
)

,question_id,class,subject,question_number,question_type,options,question_text
0,1,class10,computer_application,4,Short/Long Answer,,Section B has 7 Short Answer (SA-I) type quest...
1,2,class10,computer_application,5,Short/Long Answer,,Section C has 4 Short Answer (SA-II) type ques...
2,3,class10,computer_application,6,Short/Long Answer,,Section D has 1 Long Answer (LA) type question...
3,4,class10,computer_application,7,Case-Based,,Section E has 2 Source based /Case-based /Pass...
4,5,class10,computer_application,1,Short/Long Answer,,The acronym SSH stands for_________________. a...
5,6,class10,computer_application,2,Short/Long Answer,,Which of the following is an example of social...
6,7,class10,computer_application,3,Short/Long Answer,,M in HTML stands for: a. Modify b. Management ...
7,8,class10,computer_application,4,Short/Long Answer,,A _____________ is an online journal or inform...
8,9,class10,computer_application,5,Short/Long Answer,,Which of the following is not a valid value fo...
9,10,class10,computer_application,6,Short/Long Answer,,"link, vlink, alink are attributes of__________..."

In [118]:
final_file = processed_folder / "question_bank_enriched.csv"

question_bank.to_csv(
    final_file,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:")
print(final_file)

Saved:
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\question_bank_enriched.csv

In [119]:
df=pd.read_csv('E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\question_bank_enriched.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\vivek\AppData\Local\Temp\ipykernel_41072\1262069675.py:1: SyntaxWarning: invalid escape sequence '\C'
  df=pd.read_csv('E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\question_bank_enriched.csv')

,question_id,class,subject,session,source_file,question_number,question_text,answer,section,question_type,options,marks,topic,difficulty,has_diagram,correct_answer,answer_explanation
0,1,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,Section B has 7 Short Answer (SA-I) type quest...,NaN,NaN,Short/Long Answer,NaN,NaN,NaN,NaN,False,NaN,NaN
1,2,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Section C has 4 Short Answer (SA-II) type ques...,NaN,NaN,Short/Long Answer,NaN,NaN,NaN,NaN,False,NaN,NaN
2,3,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,Section D has 1 Long Answer (LA) type question...,NaN,NaN,Short/Long Answer,NaN,NaN,NaN,NaN,False,NaN,NaN
3,4,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,7,Section E has 2 Source based /Case-based /Pass...,NaN,NaN,Case-Based,NaN,NaN,NaN,NaN,False,NaN,NaN
4,5,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,1,The acronym SSH stands for_________________. a...,NaN,NaN,Short/Long Answer,NaN,NaN,NaN,NaN,False,NaN,NaN

In [120]:
df.shape

(1891, 17)

In [121]:
df.describe()

,question_id,question_number,answer,section,marks,topic,difficulty,correct_answer,answer_explanation
count,1891.000000,1891.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,946.000000,19.283977,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,546.028998,23.530128,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,473.500000,7.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,946.000000,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1418.500000,29.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1891.000000,800.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [122]:
df.columns

Index(['question_id', 'class', 'subject', 'session', 'source_file',
       'question_number', 'question_text', 'answer', 'section',
       'question_type', 'options', 'marks', 'topic', 'difficulty',
       'has_diagram', 'correct_answer', 'answer_explanation'],
      dtype='str')

In [123]:
display(question_bank.head(10).T)

,0,1,2,3,4,5,6,7,8,9
question_id,1,2,3,4,5,6,7,8,9,10
class,class10,class10,class10,class10,class10,class10,class10,class10,class10,class10
subject,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application
session,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
source_file,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf
question_number,4,5,6,7,1,2,3,4,5,6
question_text,Section B has 7 Short Answer (SA-I) type quest...,Section C has 4 Short Answer (SA-II) type ques...,Section D has 1 Long Answer (LA) type question...,Section E has 2 Source based /Case-based /Pass...,The acronym SSH stands for_________________. a...,Which of the following is an example of social...,M in HTML stands for: a. Modify b. Management ...,A _____________ is an online journal or inform...,Which of the following is not a valid value fo...,"link, vlink, alink are attributes of__________..."
answer,,,,,,,,,,
section,,,,,,,,,,
question_type,Short/Long Answer,Short/Long Answer,Short/Long Answer,Case-Based,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer
options,,,,,,,,,,
marks,,,,,,,,,,
topic,,,,,,,,,,
difficulty,,,,,,,,,,
has_diagram,False,False,False,False,False,False,False,False,False,False
correct_answer,,,,,,,,,,
answer_explanation,,,,,,,,,,

In [124]:
clean_bank = question_bank[
    ~question_bank["question_text"].str.startswith("Section", na=False)
].copy()

print("Before cleaning:", len(question_bank))
print("After removing section text:", len(clean_bank))

display(clean_bank.head(10).T)

Before cleaning: 1891
After removing section text: 1827

,4,5,6,7,8,9,10,11,12,13
question_id,5,6,7,8,9,10,11,12,13,14
class,class10,class10,class10,class10,class10,class10,class10,class10,class10,class10
subject,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application
session,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
source_file,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf
question_number,1,2,3,4,5,6,7,8,9,10
question_text,The acronym SSH stands for_________________. a...,Which of the following is an example of social...,M in HTML stands for: a. Modify b. Management ...,A _____________ is an online journal or inform...,Which of the following is not a valid value fo...,"link, vlink, alink are attributes of__________...",The_______ attribute of <img> tag specifies an...,Which of the following tag can be used to draw...,"In HTML, <dl>, <dd> and <dt> tags are used to ...",A software _________ is a legal instrument gov...
answer,,,,,,,,,,
section,,,,,,,,,,
question_type,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Assertion-Reason
options,,,,,,,,,,and Reason (R). Select the most suitable optio...
marks,,,,,,,,,,
topic,,,,,,,,,,
difficulty,,,,,,,,,,
has_diagram,False,False,False,False,False,False,False,False,False,False
correct_answer,,,,,,,,,,
answer_explanation,,,,,,,,,,

In [125]:
print("Empty questions:", clean_bank["question_text"].isna().sum())

print(
    "Very short questions:",
    (clean_bank["question_text"].fillna("").str.len() < 20).sum()
)

print(
    "Duplicate questions:",
    clean_bank.duplicated(
        subset=["class", "subject", "question_text"]
    ).sum()
)

Empty questions: 0
Very short questions: 0
Duplicate questions: 82

In [126]:
duplicates = clean_bank[
    clean_bank.duplicated(
        subset=["class", "subject", "question_text"],
        keep=False
    )
]

display(
    duplicates[
        ["class", "subject", "source_file", "question_text"]
    ].sort_values(["class", "subject", "question_text"]).head(20)
)

,class,subject,source_file,question_text
346,class10,social_science,SocialScience-SQP -24-25.pdf,There is no overall choice in the question pap...
384,class10,social_science,SocialScience-SQP-25-26.pdf,There is no overall choice in the question pap...
496,class9,maths,CBSE Class 9 Maths Sample Paper Set 3 for 2026...,"All Questions are compulsory. However, an inte..."
549,class9,maths,CBSE Class 9 Maths Sample Paper Set 4 (2026-27...,"All Questions are compulsory. However, an inte..."
649,class9,maths,CBSE Class 9 Maths Sample Question Paper (Set ...,"All Questions are compulsory. However, an inte..."
712,class9,maths,CBSE Class 9 Maths Sample Question Paper (Set ...,"All Questions are compulsory. However, an inte..."
844,class9,maths,Class 9 CBSE Maths Sample Paper Set 5 – FREE P...,"All Questions are compulsory. However, an inte..."
497,class9,maths,CBSE Class 9 Maths Sample Paper Set 3 for 2026...,Draw neat figures wherever required. Take π =2...
550,class9,maths,CBSE Class 9 Maths Sample Paper Set 4 (2026-27...,Draw neat figures wherever required. Take π =2...
845,class9,maths,Class 9 CBSE Maths Sample Paper Set 5 – FREE P...,Draw neat figures wherever required. Take π =2...
650,class9,maths,CBSE Class 9 Maths Sample Question Paper (Set ...,Draw neat figures wherever required. Take π =2...
713,class9,maths,CBSE Class 9 Maths Sample Question Paper (Set ...,Draw neat figures wherever required. Take π =2...
1294,class9,science,CBSE Class 9 Science Sample Question Paper (Se...,"(A) Both (A) and (R) are true, and (R) is the ..."
1374,class9,science,Class 9 Science Sample Paper Set 3 Download FR...,"(A) Both (A) and (R) are true, and (R) is the ..."
1297,class9,science,CBSE Class 9 Science Sample Question Paper (Se...,"(A) Both (A) and (R) are true, and (R) is the ..."
1377,class9,science,Class 9 Science Sample Paper Set 3 Download FR...,"(A) Both (A) and (R) are true, and (R) is the ..."
1279,class9,science,CBSE Class 9 Science Sample Question Paper (Se...,(A) Pearl Explanation: Oysters are cultivated ...
1373,class9,science,Class 9 Science Sample Paper Set 3 Download FR...,(A) Pearl Explanation: Oysters are cultivated ...
1074,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,(A) is correct Explanation: Valence electrons ...
1155,class9,science,CBSE Class 9 Science Sample Paper Set 4 (2026-...,(A) is correct Explanation: Valence electrons ...

In [127]:
instruction_patterns = (
    "all questions",
    "there is no overall choice",
    "draw neat figures",
    "general instructions",
    "(a) both",
    "(a) is correct",
    "(a) pearl explanation"
)

clean_bank = clean_bank[
    ~clean_bank["question_text"]
    .fillna("")
    .str.lower()
    .str.startswith(instruction_patterns)
].copy()

print("Rows after removing obvious non-questions:", len(clean_bank))

Rows after removing obvious non-questions: 1796

In [128]:
print(
    "Duplicate questions:",
    clean_bank.duplicated(
        subset=["class", "subject", "question_text"]
    ).sum()
)

Duplicate questions: 70

In [129]:
duplicates = clean_bank[
    clean_bank.duplicated(
        subset=["class", "subject", "question_text"],
        keep=False
    )
]

display(
    duplicates[
        ["class", "subject", "source_file", "question_text"]
    ].head(10)
)

,class,subject,source_file,question_text
1035,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,The pictures show the arrangement of electrons...
1038,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,"In a laboratory, while doing an experiment, ca..."
1040,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,Which of the following figures does not repres...
1043,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,What would be the valency of an element that i...
1044,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,A few substances are arranged in the increasin...
1045,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,Contractile proteins are found in: (A) Bones (...
1047,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,Which of these is an alloy? (A) Silver (B) Cop...
1049,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,The area below v-t graph is a measure of: a) A...
1050,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,"On converting 25°C, 38°C and 66°C to Kelvin sc..."
1051,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,Assertion (A): When heat energy is supplied to...

In [130]:
duplicate_check = (
    duplicates
    .groupby(["source_file", "question_text"])
    .size()
    .reset_index(name="count")
)

display(
    duplicate_check[
        duplicate_check["count"] > 1
    ].head(10)
)

,source_file,question_text,count
105,CBSE Class 9 Science Sample Question Paper (Se...,Which of one of the following nutrients is not...,2

In [131]:
clean_bank = clean_bank.drop_duplicates(
    subset=["class", "subject", "source_file", "question_text"],
    keep="first"
).copy()

print("Rows after removing exact duplicates:", len(clean_bank))

Rows after removing exact duplicates: 1795

In [132]:
print(clean_bank["session"].value_counts())

session
2026-27    991
Unknown    743
2025-26     61
Name: count, dtype: int64

In [133]:
import re

def get_session(filename):
    match = re.search(r"(20\d{2}-\d{2})", filename)
    
    if match:
        return match.group(1)
    
    match = re.search(r"(\d{2})-(\d{2})", filename)
    
    if match:
        return "20" + match.group(1) + "-" + match.group(2)
    
    return "Unknown"

clean_bank["session"] = clean_bank["source_file"].apply(get_session)

print(clean_bank["session"].value_counts())

session
2026-27    991
Unknown    358
2025-26    166
2024-25    141
2023-24    139
Name: count, dtype: int64

In [134]:
unknown_sessions = clean_bank[
    clean_bank["session"] == "Unknown"
]

display(
    unknown_sessions[
        ["class", "subject", "source_file"]
    ].drop_duplicates().head(30)
)

,class,subject,source_file
846,class9,maths,Class 9 CBSE Maths Sample Paper Set 5 – FREE P...
1609,class9,social_science,CBSE Class 9 Social Science Set 5 Sample Paper...
1666,class9,social_science,Class 9 Social Science Sample Paper (Set 2) - ...
1749,class9,social_science,Class 9 Social Science Sample Paper (Set 4) - ...
1820,class9,social_science,Download FREE Sample Paper Set 3 for CBSE Clas...

In [135]:
print(
    unknown_sessions["source_file"]
    .drop_duplicates()
    .to_string(index=False)
)

Class 9 CBSE Maths Sample Paper Set 5 – FREE PD...
CBSE Class 9 Social Science Set 5 Sample Paper ...
Class 9 Social Science Sample Paper (Set 2) - F...
Class 9 Social Science Sample Paper (Set 4) - F...
Download FREE Sample Paper Set 3 for CBSE Class...

In [136]:
for filename in unknown_sessions["source_file"].drop_duplicates():

    pdf_path = next(pdf for pdf in pdf_files if pdf.name == filename)

    doc = pymupdf.open(pdf_path)

    first_page_text = doc[0].get_text("text")

    print("\n" + "=" * 80)
    print(filename)
    print("-" * 80)
    print(first_page_text[:1500])

    doc.close()

================================================================================
Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class IX Maths Sample Paper – Set 5
Max. Marks: 80






Time Allowed: 3 hours
General Instructions:
1. This Question Paper has 5 Sections A-E.
2. Section A has 20 MCQs carrying 1 mark each.
3. Section B has 5 questions carrying 02 marks each.
4. Section C has 6 questions carrying 03 marks each.
5. Section D has 4 questions carrying 05 marks each.
6. Section E has 3 case based integrated units of assessment carrying 04 marks each.
7. All Questions are compulsory. However, an internal choice in 2 Qs of 5 marks, 2 Qs of 3
marks and 2 Questions of 2 marks has been provided. An internal choice has been provided in
the 2 marks questions of Section E.
8. Draw neat figures wherever required. Take π =22/7 wherever required if not stated.

Q.
No.
Questions
Marks
Section A
1.
If f is a differentiable function and
( )
0
f
x

= for all x in some interval, then
( )
f x is
1


================================================================================
CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class IX Social Science Sample Paper – Set 5
Max. Marks: 80                                                                                   Time Allowed: 3 hours

General Instructions:
i. Question paper comprises five Sections – A, B, C, D, and E. There are 37 questions in the
question paper. All questions are compulsory.
ii. Section A Questions 1 to 20 are MCQs of 1 mark each.
iii. Section B - Questions no. 21 to 24 are Very Short Answer Type Questions, carrying 2 marks
each. The answer to each question should not exceed 40 words.
iv. Section C - Questions no. 25 to Q.29 are Short Answer Type Questions, carrying 3 marks
each. The answer to each question should not exceed 60 words,
v. Section D - Questions no. 30 to 33 are Long Answer Type Questions, carrying 5 marks each.
Answer to each question should not exceed 120 words
vi. Section E - Questions no. from 34 to 36 are Case Based Questions with three sub-questions
and are of 4 marks each.
vii. Section F - Question no. 37 is Map-based, carrying 5 marks with two parts, 37a from
History (2 marks) and 37b from Geography (3 marks).




================================================================================
Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class 9 Social Science Sample Paper – Set 2
Max. Marks: 80                                                                                   Time Allowed: 3 hours

General Instructions:
Question paper comprises five Sections - A, B, C, D, and E. There are 37 questions in the
question paper. All questions are compulsory.
i.
Section A - Questions 1 to 20 are MCQs of 1 mark each.
ii.
Section B - Questions no. 21 to 24 are Very Short Answer Type Questions, carrying 2
marks each. The answer to each question should not exceed 40 words.
iii.
Section C – Questions no. 25 to Q.29 are Short Answer Type Questions, carrying 3
marks each. The answer to each question should not exceed 60 words,
iv.
Section D - Questions no. 30 to 33 are Long Answer Type Questions, carrying 5 marks
each. Answer to each question should not exceed 120 words
v.
Section E - Questions no. from 34 to 36 are Case Based Questions with three sub-
questions and are of 4 marks each.
vi.
Section F - Question no. 37 is Map-based, carrying 5 marks with two parts, 37a from
History (2 marks) and 37b from Geography (3 marks).
vii.
There is no overall choice in the question paper. However, an internal choice has been
provided in a few questions. Only one of the choices in such questions has to be
attempted.
viii.
In addition to this, separate instructions are given with each section and question,
wherever necessary.





================================================================================
Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class 9 Social Science Sample Paper – Set 4
Max. Marks: 80                                                                                   Time Allowed: 3 hours

General Instructions:
The question paper comprises five Sections - A, B, C, D, and E. There are 37 questions on
the question paper. All questions are compulsory.
i.
Section A - Questions 1 to 20 are MCQs of 1 mark each.
ii.
Section B - Questions no. 21 to 24 are Very Short Answer Type Questions, carrying 2
marks each. The answer to each question should not exceed 40 words.
iii.
Section C – Questions no. 25 to Q.29 are Short Answer Type Questions, carrying 3
marks each. The answer to each question should not exceed 60 words,
iv.
Section D - Questions no. 30 to 33 are Long Answer Type Questions, carrying 5
marks each. Answer to each question should not exceed 120 words
v.
Section E - Questions no. from 34 to 36 are Case Based Questions with three sub-
questions and are of 4 marks each.
vi.
Section F - Question no. 37 is Map-based, carrying 5 marks with two parts, 37a from
History (2 marks) and 37b from Geography (3 marks).
vii.
There is no overall choice in the question paper. However, an internal choice has been
provided in a few questions. Only one of the choices in such questions has to be
attempted.
viii.
In addition to this, separate instructions are given with each section and question,
wherever necessary.






================================================================================
Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class IX Social Science Sample Paper – Set 3
Max. Marks: 80 Marks

                             Time Allowed: 3 hours

General Instructions:
i. Question paper comprises five Sections – A, B, C, D, and E. There are 37 questions in the
question paper. All questions are compulsory.
ii. Section A Questions 1 to 20 are MCQs of 1 mark each.
iii. Section B - Questions no. 21 to 24 are Very Short Answer Type Questions, carrying 2 marks
each. The answer to each question should not exceed 40 words.
iv. Section C - Questions no. 25 to Q.29 are Short Answer Type Questions, carrying 3 marks
each. The answer to each question should not exceed 60 words,
v. Section D - Questions no. 30 to 33 are Long Answer Type Questions, carrying 5 marks each.
Answer to each question should not exceed 120 words
vi. Section E - Questions no. from 34 to 36 are Case Based Questions with three sub-questions
and are of 4 marks each.
vii. Section F - Question no. 37 is Map-based, carrying 5 marks with two parts, 37a from
History (2 marks) and 37b from Geography (3 marks).
viii. There is no overall choice in the question paper. However, an internal choice has been
provided in a few questions. Only one of the choices in such questions has to be attempted.
ix. In addition to this, separate instructions are given with each section and question, wherever
necessary.

In [137]:
clean_bank.loc[
    (clean_bank["class"] == "class9") &
    (clean_bank["session"] == "Unknown"),
    "session"
] = "2026-27"

print(clean_bank["session"].value_counts())

session
2026-27    1349
2025-26     166
2024-25     141
2023-24     139
Name: count, dtype: int64

In [138]:
print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1571
MCQ                   166
Assertion-Reason       47
Case-Based             11
Name: count, dtype: int64

In [139]:
display(
    clean_bank[
        clean_bank["question_type"] == "Short/Long Answer"
    ][
        ["class", "subject", "source_file", "question_number", "question_text"]
    ].head(15)
)

,class,subject,source_file,question_number,question_text
4,class10,computer_application,ComputerApplication-SQP -23-24.pdf,1,The acronym SSH stands for_________________. a...
5,class10,computer_application,ComputerApplication-SQP -23-24.pdf,2,Which of the following is an example of social...
6,class10,computer_application,ComputerApplication-SQP -23-24.pdf,3,M in HTML stands for: a. Modify b. Management ...
7,class10,computer_application,ComputerApplication-SQP -23-24.pdf,4,A _____________ is an online journal or inform...
8,class10,computer_application,ComputerApplication-SQP -23-24.pdf,5,Which of the following is not a valid value fo...
9,class10,computer_application,ComputerApplication-SQP -23-24.pdf,6,"link, vlink, alink are attributes of__________..."
10,class10,computer_application,ComputerApplication-SQP -23-24.pdf,7,The_______ attribute of <img> tag specifies an...
11,class10,computer_application,ComputerApplication-SQP -23-24.pdf,8,Which of the following tag can be used to draw...
12,class10,computer_application,ComputerApplication-SQP -23-24.pdf,9,"In HTML, <dl>, <dd> and <dt> tags are used to ..."
16,class10,computer_application,ComputerApplication-SQP -23-24.pdf,13,Write any two points of comparison in between ...
17,class10,computer_application,ComputerApplication-SQP -23-24.pdf,14,What is e-Learning? Mention its two main advan...
18,class10,computer_application,ComputerApplication-SQP -23-24.pdf,15,Compare 3G and 4G mobile technologies on any t...
19,class10,computer_application,ComputerApplication-SQP -23-24.pdf,16,Which software are termed as open-source softw...
20,class10,computer_application,ComputerApplication-SQP -23-24.pdf,17,Mention any two purposes of using comments whi...
21,class10,computer_application,ComputerApplication-SQP -23-24.pdf,18,Twisha has got confused with a few tags and th...

In [140]:
mcq_pattern = r"(?is)(?:\(?a\)?[\.\):])[\s\S]+(?:\(?b\)?[\.\):])[\s\S]+(?:\(?c\)?[\.\):])[\s\S]+(?:\(?d\)?[\.\):])"

is_mcq = clean_bank["question_text"].fillna("").str.contains(
    mcq_pattern,
    regex=True
)

clean_bank.loc[is_mcq, "question_type"] = "MCQ"

print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1193
MCQ                   569
Assertion-Reason       25
Case-Based              8
Name: count, dtype: int64

In [141]:
# Restore the original question types
original_types = question_bank.set_index("question_id")["question_type"]

clean_bank["question_type"] = clean_bank["question_id"].map(original_types)

# Change only Short/Long Answer rows that clearly contain a,b,c,d options
is_mcq = clean_bank["question_text"].fillna("").str.contains(
    mcq_pattern,
    regex=True
)

clean_bank.loc[
    is_mcq & clean_bank["question_type"].eq("Short/Long Answer"),
    "question_type"
] = "MCQ"

print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1193
MCQ                   544
Assertion-Reason       47
Case-Based             11
Name: count, dtype: int64

In [142]:
display(
    clean_bank[
        clean_bank["question_type"] == "MCQ"
    ][
        ["class", "subject", "question_text"]
    ].head(10)
)

,class,subject,question_text
4,class10,computer_application,The acronym SSH stands for_________________. a...
5,class10,computer_application,Which of the following is an example of social...
6,class10,computer_application,M in HTML stands for: a. Modify b. Management ...
7,class10,computer_application,A _____________ is an online journal or inform...
8,class10,computer_application,Which of the following is not a valid value fo...
9,class10,computer_application,"link, vlink, alink are attributes of__________..."
10,class10,computer_application,The_______ attribute of <img> tag specifies an...
11,class10,computer_application,Which of the following tag can be used to draw...
12,class10,computer_application,"In HTML, <dl>, <dd> and <dt> tags are used to ..."
14,class10,computer_application,Assertion (A): Search engine is a hardware dev...

In [143]:
# Fix Assertion-Reason questions first
is_assertion_reason = (
    clean_bank["question_text"]
    .fillna("")
    .str.contains("assertion", case=False)
    &
    clean_bank["question_text"]
    .fillna("")
    .str.contains("reason", case=False)
)

clean_bank.loc[is_assertion_reason, "question_type"] = "Assertion-Reason"

print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1193
MCQ                   519
Assertion-Reason       72
Case-Based             11
Name: count, dtype: int64

In [144]:
display(
    clean_bank[
        clean_bank["question_type"] == "Case-Based"
    ][
        ["class", "subject", "question_text"]
    ].head(10)
)

,class,subject,question_text
78,class10,home_science,CASE STUDY BASED QUESTIONS Read the passage ca...
111,class10,home_science,Read the passage carefully and answer Question...
331,class10,social_science,(A) : A farmer has borrowed money from a money...
383,class10,social_science,Which of the following is the main factor that...
532,class9,maths,Construct a right triangle whose hypotenuse is...
543,class9,maths,Join BC. Then ABC is right-angled with hypoten...
913,class9,maths,0.3 0.2 0.5. P X P X P X P X  = + + =  = = +...
1499,class9,social_science,Read the following passage and answer the ques...
1561,class9,social_science,Give reasons as to why. i. Seasonal reversal o...
1562,class9,social_science,Read the following text carefully and answer t...

In [145]:
display(
    clean_bank[
        clean_bank["question_type"] == "Case-Based"
    ][
        ["class", "subject", "source_file",
         "question_number", "question_text"]
    ]
)

,class,subject,source_file,question_number,question_text
78,class10,home_science,HomeScience-SQP -23-24.pdf,14,CASE STUDY BASED QUESTIONS Read the passage ca...
111,class10,home_science,HomeScience-SQP -24-25.pdf,16,Read the passage carefully and answer Question...
331,class10,social_science,SocialScience-SQP -23-24.pdf,33,(A) : A farmer has borrowed money from a money...
383,class10,social_science,SocialScience-SQP -24-25.pdf,17,Which of the following is the main factor that...
532,class9,maths,CBSE Class 9 Maths Sample Paper Set 3 for 2026...,35,Construct a right triangle whose hypotenuse is...
543,class9,maths,CBSE Class 9 Maths Sample Paper Set 3 for 2026...,4,Join BC. Then ABC is right-angled with hypoten...
913,class9,maths,Class 9 CBSE Maths Sample Paper Set 5 – FREE P...,3,0.3 0.2 0.5. P X P X P X P X  = + + =  = = +...
1499,class9,social_science,CBSE Class 9 Social Science Sample Paper 2026-...,35,Read the following passage and answer the ques...
1561,class9,social_science,CBSE Class 9 Social Science Sample Paper Set 1...,33,Give reasons as to why. i. Seasonal reversal o...
1562,class9,social_science,CBSE Class 9 Social Science Sample Paper Set 1...,34,Read the following text carefully and answer t...
1603,class9,social_science,CBSE Class 9 Social Science Sample Paper Set 1...,34,i. The passage reflects the Nazi racial ideolo...

In [146]:
# Reset current Case-Based labels
clean_bank.loc[
    clean_bank["question_type"] == "Case-Based",
    "question_type"
] = "Short/Long Answer"

# Identify clearly case/passage-based questions
text = clean_bank["question_text"].fillna("")

is_case = (
    text.str.contains("case study", case=False, na=False)
    | text.str.contains("read the passage", case=False, na=False)
    | text.str.contains("read the following text", case=False, na=False)
)

clean_bank.loc[is_case, "question_type"] = "Case-Based"

print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1172
MCQ                   517
Assertion-Reason       72
Case-Based             34
Name: count, dtype: int64

In [147]:
print(
    "MCQs with empty options:",
    clean_bank.loc[
        clean_bank["question_type"] == "MCQ",
        "options"
    ].fillna("").str.strip().eq("").sum()
)

MCQs with empty options: 195

In [148]:
display(
    clean_bank[
        (clean_bank["question_type"] == "MCQ") &
        (clean_bank["options"].fillna("").str.strip() == "")
    ][
        ["class", "subject", "question_text"]
    ].head(5)
)

,class,subject,question_text
4,class10,computer_application,The acronym SSH stands for_________________. a...
5,class10,computer_application,Which of the following is an example of social...
6,class10,computer_application,M in HTML stands for: a. Modify b. Management ...
7,class10,computer_application,A _____________ is an online journal or inform...
8,class10,computer_application,Which of the following is not a valid value fo...

In [149]:
for _, row in clean_bank[
    (clean_bank["question_type"] == "MCQ") &
    (clean_bank["options"].fillna("").str.strip() == "")
].head(5).iterrows():

    print("\nQUESTION:")
    print(row["question_text"])
    print("-" * 80)

QUESTION:
The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell
--------------------------------------------------------------------------------

QUESTION:
Which of the following is an example of social networking website? a. wikipedia.org b. Facebook.com c. cbse.gov.in d. ncert.nic.in
--------------------------------------------------------------------------------

QUESTION:
M in HTML stands for: a. Modify b. Management c. Multiple d. Markup
--------------------------------------------------------------------------------

QUESTION:
A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic. a. News group b. Blog c. WWW d. e-Groups
--------------------------------------------------------------------------------

QUESTION:
Which of the following is not a valid value for the target attribute of <a> tag? a. _blank b. _self c. _top d. _bottom Page 2 of 5
--------------------------------------------------------------------------------

In [150]:
def extract_options(text):
    pattern = r"(?i)(?:^|\s)([a-d])\.\s*(.*?)(?=\s+[a-d]\.\s+|$)"
    matches = re.findall(pattern, text)

    return " | ".join(
        f"{letter}. {option.strip()}"
        for letter, option in matches
    )

clean_bank["options"] = clean_bank["question_text"].apply(extract_options)

print(
    "MCQs with options:",
    clean_bank.loc[
        clean_bank["question_type"] == "MCQ",
        "options"
    ].ne("").sum()
)

MCQs with options: 100

In [151]:
display(
    clean_bank[
        (clean_bank["question_type"] == "MCQ") &
        (clean_bank["options"].fillna("").str.strip() == "")
    ][
        ["class", "subject", "source_file", "question_text"]
    ].head(5)
)

,class,subject,source_file,question_text
97,class10,home_science,HomeScience-SQP -24-25.pdf,“While advertising manufacturers often give an...
98,class10,home_science,HomeScience-SQP -24-25.pdf,Which of the following characteristic of cogni...
99,class10,home_science,HomeScience-SQP -24-25.pdf,The food whose nature or quality is so affecte...
100,class10,home_science,HomeScience-SQP -24-25.pdf,Which of the following are characteristics to ...
101,class10,home_science,HomeScience-SQP -24-25.pdf,“Adolescents give more importance to their fri...

In [152]:
for _, row in clean_bank[
    (clean_bank["question_type"] == "MCQ") &
    (clean_bank["options"].fillna("").str.strip() == "")
].head(5).iterrows():

    print("\nQUESTION:")
    print(row["question_text"])
    print("-" * 80)

QUESTION:
“While advertising manufacturers often give an exaggerated picture of their product”. Which malpractice of manufacturer is exhibited in this statement? (A)Charging high price (B)Adulteration of goods (C)Misleading information (D)Lack of standardized products 1
--------------------------------------------------------------------------------

QUESTION:
Which of the following characteristic of cognitive development is observed in 4 to 6 years old child? (A) Diminished egocentrism (B) Ability to conserve (C) Egocentrism (D) Can differentiate between living and non-living things OR Which of the following characteristic of emotional development is observed in 8 to 10 years old child? (A) Have imaginary friends (B) Can control impulses (C) Do not hide emotions (D)Emotions are transitory (change rapidly) and unpredictable 1 2
--------------------------------------------------------------------------------

QUESTION:
The food whose nature or quality is so affected that it is injurious to health is- (A) Organic food (B) Unsafe food (C) Raw food (D) Super food 1
--------------------------------------------------------------------------------

QUESTION:
Which of the following are characteristics to identify a stain on a fabric? (A) Colour, smell or feel (B) Colour, taste or look (C)Taste, shape or feel (D) Colour, shape or feel 1
--------------------------------------------------------------------------------

QUESTION:
“Adolescents give more importance to their friends and like to spend more time with them.” Which type of development is exhibited in this statement? (A) Physical (B) Language (C) Social (D) Cognitive 1
--------------------------------------------------------------------------------

In [153]:
def extract_options(text):
    pattern = r"(?i)(?:^|\s)(\([a-d]\)|[a-d][\.\:\)])\s+(.+?)(?=\s+(?:\([a-d]\)|[a-d][\.\:\)])\s+|$)"
    
    matches = re.findall(pattern, text)

    return " | ".join(
        f"{label.upper()} {option.strip()}"
        for label, option in matches
    )


clean_bank["options"] = clean_bank["question_text"].apply(extract_options)

print(
    "MCQs with options:",
    clean_bank.loc[
        clean_bank["question_type"] == "MCQ",
        "options"
    ].ne("").sum()
)

MCQs with options: 515

In [154]:
display(
    clean_bank[
        clean_bank["question_type"] == "MCQ"
    ][["question_text", "options"]].head(5)
)

,question_text,options
4,The acronym SSH stands for_________________. a...,A. Safe Shell | B. Software Shell | C. Secure ...
5,Which of the following is an example of social...,A. wikipedia.org | B. Facebook.com | C. cbse.g...
6,M in HTML stands for: a. Modify b. Management ...,A. Modify | B. Management | C. Multiple | D. M...
7,A _____________ is an online journal or inform...,A. News group | B. Blog | C. WWW | D. e-Groups
8,Which of the following is not a valid value fo...,A. _blank | B. _self | C. _top | D. _bottom Pa...

In [155]:
display(
    clean_bank[
        (clean_bank["question_type"] == "MCQ") &
        (clean_bank["options"].fillna("").str.strip() == "")
    ][
        ["class", "subject", "source_file", "question_text"]
    ]
)

,class,subject,source_file,question_text
97,class10,home_science,HomeScience-SQP -24-25.pdf,“While advertising manufacturers often give an...
1761,class9,social_science,Class 9 Social Science Sample Paper (Set 4) - ...,Arrange the following events in chronological ...

In [156]:
for _, row in clean_bank[
    (clean_bank["question_type"] == "MCQ") &
    (clean_bank["options"].fillna("").str.strip() == "")
].iterrows():

    print("\nQUESTION:")
    print(row["question_text"])
    print("-" * 80)

QUESTION:
“While advertising manufacturers often give an exaggerated picture of their product”. Which malpractice of manufacturer is exhibited in this statement? (A)Charging high price (B)Adulteration of goods (C)Misleading information (D)Lack of standardized products 1
--------------------------------------------------------------------------------

QUESTION:
Arrange the following events in chronological order: i. The Great Economic Depression begins. ii. The mass murder of the Jews begins. iii. Second World War begins. iv. First World War begins. a)iv, ii, i, iii b)iii, i, ii, iv c)i, iv, iii, ii d)iv, i, iii, ii 1
--------------------------------------------------------------------------------

In [157]:
def remove_options(text):
    return re.split(
        r"(?i)\s+(?:\([a-d]\)|[a-d][\.\:\)])\s+",
        text,
        maxsplit=1
    )[0].strip()

clean_bank["question_text_clean"] = (
    clean_bank["question_text"]
    .apply(remove_options)
)

display(
    clean_bank[
        ["question_text", "question_text_clean", "options"]
    ].head(5)
)

,question_text,question_text_clean,options
4,The acronym SSH stands for_________________. a...,The acronym SSH stands for_________________.,A. Safe Shell | B. Software Shell | C. Secure ...
5,Which of the following is an example of social...,Which of the following is an example of social...,A. wikipedia.org | B. Facebook.com | C. cbse.g...
6,M in HTML stands for: a. Modify b. Management ...,M in HTML stands for:,A. Modify | B. Management | C. Multiple | D. M...
7,A _____________ is an online journal or inform...,A _____________ is an online journal or inform...,A. News group | B. Blog | C. WWW | D. e-Groups
8,Which of the following is not a valid value fo...,Which of the following is not a valid value fo...,A. _blank | B. _self | C. _top | D. _bottom Pa...

In [158]:
clean_file = processed_folder / "clean_question_bank.csv"

clean_bank.to_csv(
    clean_file,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", clean_file)
print("Rows:", len(clean_bank))
print("Columns:", len(clean_bank.columns))

Saved: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\clean_question_bank.csv
Rows: 1795
Columns: 18

In [159]:
print("Missing question text:", clean_bank["question_text_clean"].isna().sum())
print("Missing class:", clean_bank["class"].isna().sum())
print("Missing subject:", clean_bank["subject"].isna().sum())
print("Missing session:", clean_bank["session"].isna().sum())

Missing question text: 0
Missing class: 0
Missing subject: 0
Missing session: 0

In [160]:
llm_dataset = clean_bank[
    [
        "question_id",
        "class",
        "subject",
        "session",
        "question_type",
        "question_text_clean",
        "options",
        "source_file"
    ]
].copy()

print("LLM dataset rows:", len(llm_dataset))
print("LLM dataset columns:", llm_dataset.columns.tolist())

display(llm_dataset.head(10))

LLM dataset rows: 1795
LLM dataset columns: ['question_id', 'class', 'subject', 'session', 'question_type', 'question_text_clean', 'options', 'source_file']

,question_id,class,subject,session,question_type,question_text_clean,options,source_file
4,5,class10,computer_application,2023-24,MCQ,The acronym SSH stands for_________________.,A. Safe Shell | B. Software Shell | C. Secure ...,ComputerApplication-SQP -23-24.pdf
5,6,class10,computer_application,2023-24,MCQ,Which of the following is an example of social...,A. wikipedia.org | B. Facebook.com | C. cbse.g...,ComputerApplication-SQP -23-24.pdf
6,7,class10,computer_application,2023-24,MCQ,M in HTML stands for:,A. Modify | B. Management | C. Multiple | D. M...,ComputerApplication-SQP -23-24.pdf
7,8,class10,computer_application,2023-24,MCQ,A _____________ is an online journal or inform...,A. News group | B. Blog | C. WWW | D. e-Groups,ComputerApplication-SQP -23-24.pdf
8,9,class10,computer_application,2023-24,MCQ,Which of the following is not a valid value fo...,A. _blank | B. _self | C. _top | D. _bottom Pa...,ComputerApplication-SQP -23-24.pdf
9,10,class10,computer_application,2023-24,MCQ,"link, vlink, alink are attributes of__________...",A. <body> | B. <a> | C. <html> | D. <img>,ComputerApplication-SQP -23-24.pdf
10,11,class10,computer_application,2023-24,MCQ,The_______ attribute of <img> tag specifies an...,A. alt | B. text | C. alternate | D. msg,ComputerApplication-SQP -23-24.pdf
11,12,class10,computer_application,2023-24,MCQ,Which of the following tag can be used to draw...,A. <line> | B. <hrule> | C. <hr> | D. <rule>,ComputerApplication-SQP -23-24.pdf
12,13,class10,computer_application,2023-24,MCQ,"In HTML, <dl>, <dd> and <dt> tags are used to ...",A. Description list | B. Definition list | C. ...,ComputerApplication-SQP -23-24.pdf
13,14,class10,computer_application,2023-24,Assertion-Reason,A software _________ is a legal instrument gov...,A. license | B. law | C. document | D. piracy ...,ComputerApplication-SQP -23-24.pdf

In [161]:
llm_file = processed_folder / "llm_input_dataset.csv"

llm_dataset.to_csv(
    llm_file,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", llm_file)

Saved: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\llm_input_dataset.csv

In [162]:
import psutil

ram_gb = psutil.virtual_memory().total / (1024 ** 3)

print(f"System RAM: {ram_gb:.1f} GB")

System RAM: 15.9 GB

In [163]:
import torch

print("PyTorch version:", torch.__version__)
print("GPU available:", torch.cuda.is_available())

PyTorch version: 2.14.0+cpu
GPU available: False

In [164]:
from transformers import pipeline
generator = pipeline(
    "text-generation",
    model="Qwen/Qwen2.5-1.5B-Instruct"
)
print("Model loaded successfully!")

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

Model loaded successfully!

In [165]:
messages = [
    {"role": "user",
     "content": "Write one simple Class 9 Maths question about linear equations."
    }]
result = generator(messages, max_new_tokens=100)
print(result)

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[{'generated_text': [{'role': 'user', 'content': 'Write one simple Class 9 Maths question about linear equations.'}, {'role': 'assistant', 'content': "Sure! Here's a simple Class 9 Mathematics question about linear equations:\n\n**Question:**\n\nSolve the following system of linear equations for \\(x\\) and \\(y\\):\n\n1. \\(2x + y = 8\\)\n2. \\(3x - y = 7\\)\n\nShow all your working steps.\n\n---\n\nThis question tests the student's ability to solve a pair of simultaneous linear equations using algebraic methods such as substitution or elimination."}]}]

In [166]:
sample = llm_dataset[
    llm_dataset["question_type"] == "MCQ"
].iloc[0]

print("Class:", sample["class"])
print("Subject:", sample["subject"])
print("Type:", sample["question_type"])
print("Question:", sample["question_text_clean"])
print("Options:", sample["options"])

Class: class10
Subject: computer_application
Type: MCQ
Question: The acronym SSH stands for_________________.
Options: A. Safe Shell | B. Software Shell | C. Secure Shell | D. Simple Shell

In [167]:
sample = llm_dataset[
    llm_dataset["question_type"] == "MCQ"
].iloc[0]

print("Class:", sample["class"])
print("Subject:", sample["subject"])
print("Type:", sample["question_type"])
print("Question:", sample["question_text_clean"])
print("Options:", sample["options"])

Class: class10
Subject: computer_application
Type: MCQ
Question: The acronym SSH stands for_________________.
Options: A. Safe Shell | B. Software Shell | C. Secure Shell | D. Simple Shell

In [168]:
from transformers import GenerationConfig

generation_config = GenerationConfig(
    max_new_tokens=150,
    do_sample=True,
    temperature=0.8,
    top_p=0.9,
    repetition_penalty=1.1
)

def generate_cbse_question(class_name, subject, question_type, topic):
    
    prompt = f"""
You are a CBSE question paper writer.

Generate ONE new {question_type} for:
Class: {class_name}
Subject: {subject}
Topic: {topic}

Rules:
- Do not copy existing questions.
- Keep the question suitable for the given class.
- For MCQ, give exactly 4 options: A, B, C, D.
- Give one correct answer.
- Do not give an explanation.
- Follow exactly this format:

QUESTION:
<question>

A) <option>
B) <option>
C) <option>
D) <option>

ANSWER:
<correct answer>
"""

    result = generator(
        [{"role": "user", "content": prompt}],
        generation_config=generation_config
    )

    return result[0]["generated_text"][-1]["content"]

In [169]:
generated = generate_cbse_question(
    "class10",
    "computer_application",
    "MCQ",
    "Internet and web concepts"
)

print(generated)

QUESTION:
What is the primary function of a domain name server (DNS)?

A) To store user profiles
B) To translate domain names into IP addresses
C) To encrypt internet traffic
D) To manage website content

ANSWER:
B) To translate domain names into IP addresses

In [170]:
generated_file = processed_folder / "generated_questions.csv"
generated_df.to_csv(
    generated_file,
    index=False,
    encoding="utf-8-sig"
)
print("Saved:", generated_file)

Saved: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\generated_questions.csv

In [171]:
generated_file = processed_folder / "generated_questions.csv"

generated_df = pd.read_csv(generated_file)

print("Generated questions:", len(generated_df))
display(generated_df.head(5))

Generated questions: 14

,class,subject,question_type,source_question,generated_question
0,class9,science,MCQ,(a) Amoeba and Euglena arc unicellular organis...,QUESTION:\nWhich of the following statements i...
1,class9,social_science,MCQ,Read the information given below and select th...,QUESTION:\nWhich of the following was a symbol...
2,class9,social_science,MCQ,The river Narmada has its source at:,QUESTION:\nWhat is the primary source of water...
3,class9,maths,MCQ,Which of the following numbers cannot be repre...,QUESTION:\nWhich of the following numbers cann...
4,class9,social_science,MCQ,"On the given map of France, A is marked as a p...","QUESTION:\nOn the given map of France, A is ma..."

In [172]:
display(
    generated_df[
        ["class", "subject", "source_question", "generated_question"]
    ].head(5)
)

,class,subject,source_question,generated_question
0,class9,science,(a) Amoeba and Euglena arc unicellular organis...,QUESTION:\nWhich of the following statements i...
1,class9,social_science,Read the information given below and select th...,QUESTION:\nWhich of the following was a symbol...
2,class9,social_science,The river Narmada has its source at:,QUESTION:\nWhat is the primary source of water...
3,class9,maths,Which of the following numbers cannot be repre...,QUESTION:\nWhich of the following numbers cann...
4,class9,social_science,"On the given map of France, A is marked as a p...","QUESTION:\nOn the given map of France, A is ma..."

In [173]:
for i, row in generated_df.head(5).iterrows():
    print("\n" + "=" * 80)
    print("CLASS:", row["class"])
    print("SUBJECT:", row["subject"])
    print("SOURCE:", row["source_question"])
    print("\nGENERATED:")
    print(row["generated_question"])

================================================================================
CLASS: class9
SUBJECT: science
SOURCE: (a) Amoeba and Euglena arc unicellular organisms. www.vedantu.com 30

GENERATED:
QUESTION:
Which of the following statements is true about amoebas?

A) They have multiple nuclei and chloroplasts.
B) They are photosynthetic and live in water.
C) They reproduce through binary fission but lack cellular structure.
D) They move using pseudopodia and feed on organic matter.

ANSWER:
D) They move using pseudopodia and feed on organic matter.

================================================================================
CLASS: class9
SUBJECT: social_science
SOURCE: Read the information given below and select the correct option. Most of men and women in the eighteenth century could not read or write. So, images and symbols were frequently used instead of printed words to communicate important ideas. Which of the following was a symbol of royal power?

GENERATED:
QUESTION:
Which of the following was a symbol of royal power during the eighteenth century?

A) The Bible
B) The Crown Jewels
C) The Royal Coat of Arms
D) The Flag of Great Britain

ANSWER:
C) The Royal Coat of Arms

================================================================================
CLASS: class9
SUBJECT: social_science
SOURCE: The river Narmada has its source at:

GENERATED:
QUESTION:
What is the primary source of water for the river Narmada?

A) Himalayas
B) Aravallis
C) Western Ghats
D) Eastern Ghats

ANSWER:
B) Aravallis

================================================================================
CLASS: class9
SUBJECT: maths
SOURCE: Which of the following numbers cannot be represented as a terminating decimal?

GENERATED:
QUESTION:
Which of the following numbers cannot be represented as a terminating decimal?

A) 1/3
B) 2/5
C) 7/8
D) 3/2

ANSWER:
A) 1/3

================================================================================
CLASS: class9
SUBJECT: social_science
SOURCE: On the given map of France, A is marked as a place where troops entered following the King’s Command. Identify it from the following options. 1 www.vedantu.com 6

GENERATED:
QUESTION:
On the given map of France, A is marked as a place where troops entered following the King's Command. Identify it from the following options. 3

A) Paris
B) Marseille
C) Strasbourg
D) Bordeaux

ANSWER:
D) Bordeaux

In [174]:
print("Generated:", len(generated_df))

for i, row in generated_df.iterrows():
    print(
        i,
        "|",
        row["class"],
        "|",
        row["subject"]
    )

Generated: 14
0 | class9 | science
1 | class9 | social_science
2 | class9 | social_science
3 | class9 | maths
4 | class9 | social_science
5 | class10 | social_science
6 | class9 | maths
7 | class9 | social_science
8 | class9 | science
9 | class9 | maths
10 | class9 | social_science
11 | class9 | science
12 | class9 | science
13 | class10 | maths

In [175]:
import re
from difflib import SequenceMatcher

def validate_generated(row):
    text = row["generated_question"]

    option_count = len(
        re.findall(r"(?m)^[A-D][\)\.]\s+", text)
    )

    has_answer = bool(
        re.search(r"(?im)^ANSWER:\s*$", text)
    )

    source = row["source_question"]
    similarity = SequenceMatcher(
        None,
        source.lower(),
        text.lower()
    ).ratio()

    if option_count == 4 and has_answer and similarity < 0.75:
        return "PASS_FORMAT"

    return "REVIEW"

generated_df["quality_status"] = generated_df.apply(
    validate_generated,
    axis=1
)

print(generated_df["quality_status"].value_counts())

display(
    generated_df[
        ["class", "subject", "quality_status"]
    ]
)

quality_status
REVIEW    14
Name: count, dtype: int64

      class         subject quality_status
0    class9         science         REVIEW
1    class9  social_science         REVIEW
2    class9  social_science         REVIEW
3    class9           maths         REVIEW
4    class9  social_science         REVIEW
5   class10  social_science         REVIEW
6    class9           maths         REVIEW
7    class9  social_science         REVIEW
8    class9         science         REVIEW
9    class9           maths         REVIEW
10   class9  social_science         REVIEW
11   class9         science         REVIEW
12   class9         science         REVIEW
13  class10           maths         REVIEW

In [176]:
for i, row in generated_df.iterrows():
    text = row["generated_question"]

    option_count = len(
        re.findall(r"(?m)^[A-D][\)\.]\s+", text)
    )

    has_answer = bool(
        re.search(r"(?im)^ANSWER:\s*$", text)
    )

    similarity = SequenceMatcher(
        None,
        row["source_question"].lower(),
        text.lower()
    ).ratio()

    print(
        i,
        "| options:", option_count,
        "| answer:", has_answer,
        "| similarity:", round(similarity, 2)
    )

0 | options: 5 | answer: True | similarity: 0.02
1 | options: 5 | answer: True | similarity: 0.02
2 | options: 5 | answer: True | similarity: 0.33
3 | options: 5 | answer: True | similarity: 0.71
4 | options: 5 | answer: True | similarity: 0.73
5 | options: 5 | answer: True | similarity: 0.05
6 | options: 5 | answer: True | similarity: 0.25
7 | options: 5 | answer: True | similarity: 0.03
8 | options: 5 | answer: True | similarity: 0.05
9 | options: 4 | answer: False | similarity: 0.31
10 | options: 5 | answer: True | similarity: 0.58
11 | options: 5 | answer: True | similarity: 0.0
12 | options: 5 | answer: True | similarity: 0.1
13 | options: 5 | answer: True | similarity: 0.65

In [177]:
def validate_generated(row):
    text = row["generated_question"]

    # Count options only before the ANSWER section
    question_part = text.split("ANSWER:", 1)[0]

    option_count = len(
        re.findall(r"(?m)^[A-D][\)\.]\s+", question_part)
    )

    has_answer = "ANSWER:" in text

    similarity = SequenceMatcher(
        None,
        row["source_question"].lower(),
        text.lower()
    ).ratio()

    if option_count == 4 and has_answer and similarity < 0.75:
        return "PASS_FORMAT"

    return "REVIEW"


generated_df["quality_status"] = generated_df.apply(
    validate_generated,
    axis=1
)

print(generated_df["quality_status"].value_counts())

quality_status
PASS_FORMAT    13
REVIEW          1
Name: count, dtype: int64

In [178]:
display(
    generated_df[
        generated_df["quality_status"] == "REVIEW"
    ][
        ["class", "subject", "source_question", "generated_question"]
    ]
)

,class,subject,source_question,generated_question
9,class9,maths,Which of these is a valid LPP objective functi...,QUESTION:\nWhich of these is a valid LPP objec...

In [179]:
replacement = generate_cbse_question(
    "class9",
    "social_science",
    "MCQ",
    "French Revolution and its major events"
)

print(replacement)

QUESTION:
What event marked the beginning of the French Revolution?

A) The storming of the Bastille
B) The signing of the Declaration of Rights of Man and Citizen
C) The Reign of Terror
D) Napoleon's rise to power

ANSWER:
A) The storming of the Bastille

In [180]:
accepted_df = generated_df[
    generated_df["quality_status"] == "PASS_FORMAT"
].copy()

replacement_row = {
    "class": "class9",
    "subject": "social_science",
    "question_type": "MCQ",
    "source_question": "French Revolution topic",
    "generated_question": replacement,
    "quality_status": "PASS_FORMAT",
    "answer_status": "Needs verification"
}

accepted_df["answer_status"] = "Needs verification"

accepted_df = pd.concat(
    [accepted_df, pd.DataFrame([replacement_row])],
    ignore_index=True
)

print("Final generated questions:", len(accepted_df))

Final generated questions: 14

In [181]:
final_generated_file = processed_folder / "final_generated_questions.csv"

accepted_df.to_csv(
    final_generated_file,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", final_generated_file)

Saved: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\final_generated_questions.csv