In [1]:
import pandas as pd
import pymupdf
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("Pandas version:", pd.__version__)
print("PyMuPDF imported successfully!")

Pandas version: 3.0.5
PyMuPDF imported successfully!

In [2]:
from pathlib import Path

pdf_path=Path(r'E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf')

print('PDF exists:',pdf_path.exists())
print('PDF path:',pdf_path)

PDF exists: True
PDF path: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf

In [4]:
doc=pymupdf.open(pdf_path)

print('PDF opened successfully')
print('Number_of_pages:',len(doc))

PDF opened successfully
Number_of_pages: 41

In [5]:
page=doc[0]
text=page.get_text('text')
print(text)

www.vedantu.com
1



Class 9 Maths Sample Paper – Set 1
Max. Marks: 80                                                                                   Time Allowed: 3 hours

General Instructions:
1. This Question Paper has 5 Sections A-E.
2. Section A has 20 MCQs carrying 1 mark each.
3. Section B has 5 questions carrying 02 marks each.
4. Section C has 6 questions carrying 03 marks each.
5. Section D has 4 questions carrying 05 marks each.
6. Section E has 3 case based integrated units of assessment carrying 04 marks each.
7. All Questions are compulsory. However, an internal choice in 2 Qs of 5 marks, 2 Qs of 3
marks and 2 Questions of 2 marks has been provided. An internal choice has been provided
in the 2 marks questions of Section E.
8. Draw neat figures wherever required. Take π =22/7 wherever required if not stated.

In [6]:
with pymupdf.open(pdf_path) as doc:
    for page_number, page in enumerate(doc, start=1):
        text = page.get_text("text")
        print(f"Page {page_number}: {len(text)} characters")

Page 1: 884 characters
Page 2: 681 characters
Page 3: 587 characters
Page 4: 424 characters
Page 5: 386 characters
Page 6: 564 characters
Page 7: 1061 characters
Page 8: 287 characters
Page 9: 911 characters
Page 10: 598 characters
Page 11: 445 characters
Page 12: 513 characters
Page 13: 917 characters
Page 14: 817 characters
Page 15: 600 characters
Page 16: 990 characters
Page 17: 855 characters
Page 18: 831 characters
Page 19: 543 characters
Page 20: 536 characters
Page 21: 672 characters
Page 22: 765 characters
Page 23: 821 characters
Page 24: 989 characters
Page 25: 661 characters
Page 26: 700 characters
Page 27: 567 characters
Page 28: 654 characters
Page 29: 438 characters
Page 30: 442 characters
Page 31: 745 characters
Page 32: 843 characters
Page 33: 677 characters
Page 34: 642 characters
Page 35: 535 characters
Page 36: 716 characters
Page 37: 805 characters
Page 38: 672 characters
Page 39: 481 characters
Page 40: 842 characters
Page 41: 127 characters

In [7]:
from pathlib import Path
raw_folder = Path(r"E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw")
pdf_files = list(raw_folder.rglob("*.pdf"))
print("Total PDF files found:", len(pdf_files))

for pdf in pdf_files:
    print(pdf)

Total PDF files found: 36
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP-24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP -24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP -24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\science\Science-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\science\Science-SQP -24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\science\Science-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\social_science\SocialScience-SQP -23-24.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\social_science\SocialScience-SQP -24-25.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\social_science\SocialScience-SQP-25-26.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper 2026-27 (Mock Paper 6).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper Set 3 for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper Set 4 (2026-27) – FREE PDF with Solutions.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 2) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Sample Paper Class 9 Maths 2026-27 _ Mock Paper 7 PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper 2026-27 Mock Test Set 6.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper 2026-27 _ Mock Paper 7 PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 4 (2026-27) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 5 (2026-27) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\Class 9 Science Sample Paper Set 3 Download FREE PDF for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper 2025-26 (Mock Paper 6).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper 2026-27 (Mock Paper 7).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper Set 1 FREE PDF for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf

In [8]:
all_pages = []

for pdf_path in pdf_files:
    with pymupdf.open(pdf_path) as doc:

        for page_number, page in enumerate(doc, start=1):
            text = page.get_text("text").strip()

            all_pages.append({
                "source_file": pdf_path.name,
                "source_path": str(pdf_path),
                "page_number": page_number,
                "text": text,
                "text_length": len(text)
            })

print("Total pages extracted:", len(all_pages))

Total pages extracted: 605

In [9]:
import shutil
tesseract_path=shutil.which("tesseract")
print("Tesseract path:",tesseract_path)

Tesseract path: None

In [10]:
import pytesseract
print('pytesseract installed succesfully')

pytesseract installed succesfully

In [11]:
import shutil
tesseract_path=shutil.which("tesseract")
print("Tesseract path:",tesseract_path)

Tesseract path: None

In [12]:
import pytesseract
pytesseract.pytesseract.tesseract_cmd= r"C:\Program Files\Tesseract-OCR\tesseract.exe"
print(pytesseract.get_tesseract_version())

5.5.0.20241111

In [13]:
for i, pdf in enumerate(pdf_files[:10]):
    print(i, pdf)

0 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP -23-24.pdf
1 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP-24-25.pdf
2 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\computer_application\ComputerApplication-SQP-25-26.pdf
3 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP -23-24.pdf
4 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP -24-25.pdf
5 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\home_science\HomeScience-SQP-25-26.pdf
6 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP -23-24.pdf
7 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP -24-25.pdf
8 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\maths\MathsStandard-SQP-25-26.pdf
9 E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class10\science\Science-SQP -23-24.pdf

In [14]:
class9_pdfs = [
    pdf for pdf in pdf_files
    if "class9" in [part.lower() for part in pdf.parts]
]

print("Class 9 PDFs:", len(class9_pdfs))

for pdf in class9_pdfs:
    print(pdf)

Class 9 PDFs: 21
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper 2026-27 (Mock Paper 6).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper Set 3 for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Paper Set 4 (2026-27) – FREE PDF with Solutions.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Class 9 Maths Sample Question Paper (Set 2) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\CBSE Sample Paper Class 9 Maths 2026-27 _ Mock Paper 7 PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\maths\Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper 2026-27 Mock Test Set 6.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper 2026-27 _ Mock Paper 7 PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 4 (2026-27) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Paper Set 5 (2026-27) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\CBSE Class 9 Science Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\science\Class 9 Science Sample Paper Set 3 Download FREE PDF for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper 2025-26 (Mock Paper 6).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper 2026-27 (Mock Paper 7).pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Sample Paper Set 1 FREE PDF for 2026-27.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\raw\class9\social_science\Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf

In [15]:
from PIL import Image
import io
pdf_path = class9_pdfs[0]
doc = pymupdf.open(pdf_path)
page = doc[0]
pix = page.get_pixmap(dpi=200)

image = Image.open(io.BytesIO(pix.tobytes("png")))
ocr_text = pytesseract.image_to_string(image)
print(ocr_text[:2000])
doc.close()

\Wedanti

LIVE ONLINE TUTORING

CBSE Class 9 Subject Maths Sample Question Paper — Set 6

General Instructions

V There are 90 questions in total. All questions are compulsory.

V The paper is divided into Sections A, B, C, D, and E.
V Internal choice follows CBSE norms.

V Questions strictly follow the current CBSE syllabus.

V Include the total marks and time duration based on the questions.

SECTION A — Objective Type Questions

(Include NEW MCQs and Assertion-Reason questions)

1. Which of the following numbers cannot be represented as a terminating decimal?

(a) 3/5
(b) 2/7
(c)1/4
(d) %

2. The value of (81)°"“ is:
(a) 9

(b) 27

(c) 64

(d) 16

3. If ais a root of the equation x’ - 2x + 1= 0, then ais:
(a) only

(b) -lonly

(c) both land -1

(d)o

4. Which of the following is a binomial?
(a)x*

(b) x +2

(c) 4x

(d) x? +x+1

www.vedantu.com

In [16]:
all_extracted_pages=[]

for pdf_path in pdf_files:
      # Find class from folder name
    class_name = "class9" if "class9" in [part.lower() for part in pdf_path.parts] else "class10"

    # Find subject from folder name
    subject = pdf_path.parent.name

    print(f"Processing: {class_name} | {subject} | {pdf_path.name}")

    doc = pymupdf.open(pdf_path)

    for page_number, page in enumerate(doc, start=1):

        # First try normal PDF text extraction
        native_text = page.get_text("text").strip()

        # OCR only when native text is very little
        ocr_text = ""

        if len(native_text) < 150:

            pix = page.get_pixmap(dpi=200)

            image = Image.open(
                io.BytesIO(pix.tobytes("png"))
            )

            ocr_text = pytesseract.image_to_string(image).strip()

        # Choose the better available text
        final_text = native_text if len(native_text) >= 150 else ocr_text

        all_extracted_pages.append({
            "class": class_name,
            "subject": subject,
            "source_file": pdf_path.name,
            "page_number": page_number,
            "native_text": native_text,
            "ocr_text": ocr_text,
            "final_text": final_text
        })

    doc.close()

print("\nTotal pages processed:", len(all_extracted_pages))

Processing: class10 | computer_application | ComputerApplication-SQP -23-24.pdf
Processing: class10 | computer_application | ComputerApplication-SQP-24-25.pdf
Processing: class10 | computer_application | ComputerApplication-SQP-25-26.pdf
Processing: class10 | home_science | HomeScience-SQP -23-24.pdf
Processing: class10 | home_science | HomeScience-SQP -24-25.pdf
Processing: class10 | home_science | HomeScience-SQP-25-26.pdf
Processing: class10 | maths | MathsStandard-SQP -23-24.pdf
Processing: class10 | maths | MathsStandard-SQP -24-25.pdf
Processing: class10 | maths | MathsStandard-SQP-25-26.pdf
Processing: class10 | science | Science-SQP -23-24.pdf
Processing: class10 | science | Science-SQP -24-25.pdf
Processing: class10 | science | Science-SQP-25-26.pdf
Processing: class10 | social_science | SocialScience-SQP -23-24.pdf
Processing: class10 | social_science | SocialScience-SQP -24-25.pdf
Processing: class10 | social_science | SocialScience-SQP-25-26.pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Paper 2026-27 (Mock Paper 6).pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Paper Set 3 for 2026-27.pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Paper Set 4 (2026-27) – FREE PDF with Solutions.pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
Processing: class9 | maths | CBSE Class 9 Maths Sample Question Paper (Set 2) 2026-27 FREE PDF.pdf
Processing: class9 | maths | CBSE Sample Paper Class 9 Maths 2026-27 _ Mock Paper 7 PDF.pdf
Processing: class9 | maths | Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper 2026-27 Mock Test Set 6.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper 2026-27 _ Mock Paper 7 PDF.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper Set 2 (2026-27) FREE Download.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper Set 4 (2026-27) - FREE PDF Download.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Paper Set 5 (2026-27) - FREE PDF Download.pdf
Processing: class9 | science | CBSE Class 9 Science Sample Question Paper (Set 1) 2026-27 FREE PDF.pdf
Processing: class9 | science | Class 9 Science Sample Paper Set 3 Download FREE PDF for 2026-27.pdf
Processing: class9 | social_science | CBSE Class 9 Social Science Sample Paper 2025-26 (Mock Paper 6).pdf
Processing: class9 | social_science | CBSE Class 9 Social Science Sample Paper 2026-27 (Mock Paper 7).pdf
Processing: class9 | social_science | CBSE Class 9 Social Science Sample Paper Set 1 FREE PDF for 2026-27.pdf
Processing: class9 | social_science | CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
Processing: class9 | social_science | Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
Processing: class9 | social_science | Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
Processing: class9 | social_science | Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf

Total pages processed: 605

In [17]:
df_pages = pd.DataFrame(all_extracted_pages)

print("Total page rows:", len(df_pages))
print("Total PDFs:", df_pages["source_file"].nunique())

print("\nClass-wise pages:")
print(df_pages["class"].value_counts())

print("\nSubject-wise pages:")
print(df_pages["subject"].value_counts())

Total page rows: 605
Total PDFs: 36

Class-wise pages:
class
class9     466
class10    139
Name: count, dtype: int64

Subject-wise pages:
subject
maths                   195
science                 186
social_science          186
computer_application     19
home_science             19
Name: count, dtype: int64

In [18]:
print("Pages that used OCR:", (df_pages["ocr_text"] != "").sum())
print("Pages with no final text:", (df_pages["final_text"].str.strip() == "").sum())

Pages that used OCR: 14
Pages with no final text: 0

In [19]:
import re
import pandas as pd

question_rows = []

for (class_name, subject, source_file), group in df_pages.groupby(
    ["class", "subject", "source_file"]
):
    
    group = group.sort_values("page_number")
    full_text = "\n".join(group["final_text"].fillna(""))

    # Remove text before the first section
    section_match = re.search(
        r"\bSECTION\s*[-–]?\s*[A-E]\b",
        full_text,
        flags=re.IGNORECASE
    )

    if section_match:
        full_text = full_text[section_match.start():]

    # Find numbered questions: 1. / 1) / 2. / 2)
    pattern = r"(?m)^\s*(\d{1,3})[\.\)]\s+(.*?)(?=^\s*\d{1,3}[\.\)]\s+|\Z)"

    matches = re.finditer(
        pattern,
        full_text,
        flags=re.MULTILINE | re.DOTALL
    )

    for match in matches:
        question_number = int(match.group(1))
        question_text = re.sub(r"\s+", " ", match.group(2)).strip()

        # Ignore very short accidental matches
        if len(question_text) < 20:
            continue

        session_match = re.search(r"(20\d{2}-\d{2})", source_file)
        session = session_match.group(1) if session_match else "Unknown"

        question_rows.append({
            "question_id": len(question_rows) + 1,
            "class": class_name,
            "subject": subject,
            "session": session,
            "source_file": source_file,
            "question_number": question_number,
            "question_text": question_text,
            "answer": ""
        })

question_df = pd.DataFrame(question_rows)

print("Total questions extracted:", len(question_df))
display(question_df.head(10))

Total questions extracted: 1891

,question_id,class,subject,session,source_file,question_number,question_text,answer
0,1,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,Section B has 7 Short Answer (SA-I) type quest...,
1,2,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Section C has 4 Short Answer (SA-II) type ques...,
2,3,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,Section D has 1 Long Answer (LA) type question...,
3,4,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,7,Section E has 2 Source based /Case-based /Pass...,
4,5,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,1,The acronym SSH stands for_________________. a...,
5,6,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,2,Which of the following is an example of social...,
6,7,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,3,M in HTML stands for: a. Modify b. Management ...,
7,8,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,A _____________ is an online journal or inform...,
8,9,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Which of the following is not a valid value fo...,
9,10,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,"link, vlink, alink are attributes of__________...",

In [20]:
from pathlib import Path

processed_folder = raw_folder.parent / "processed"
processed_folder.mkdir(exist_ok=True)

print("Processed folder:", processed_folder)

Processed folder: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed

In [21]:
output_file = processed_folder / "question_dataset.csv"

question_df.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("Dataset saved:")
print(output_file)

Dataset saved:
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\question_dataset.csv

In [22]:
# Create a richer question-bank dataset from the extracted questions

question_bank = question_df.copy()

# Section
question_bank["section"] = ""

# Question type
question_bank["question_type"] = ""

# Options
question_bank["options"] = ""

# Marks
question_bank["marks"] = ""

# Topic - will be populated during subject-wise cleaning
question_bank["topic"] = ""

# Difficulty - will be assigned later
question_bank["difficulty"] = ""

# Diagram/image indicator
question_bank["has_diagram"] = False

# Answer is unavailable in the current raw question set
question_bank["correct_answer"] = ""

# Explanation is unavailable in the current raw question set
question_bank["answer_explanation"] = ""

print("Rows:", len(question_bank))
print("Columns:")
print(question_bank.columns.tolist())

display(question_bank.head(10))

Rows: 1891
Columns:
['question_id', 'class', 'subject', 'session', 'source_file', 'question_number', 'question_text', 'answer', 'section', 'question_type', 'options', 'marks', 'topic', 'difficulty', 'has_diagram', 'correct_answer', 'answer_explanation']

,question_id,class,subject,session,source_file,question_number,question_text,answer,section,question_type,options,marks,topic,difficulty,has_diagram,correct_answer,answer_explanation
0,1,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,Section B has 7 Short Answer (SA-I) type quest...,,,,,,,,False,,
1,2,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Section C has 4 Short Answer (SA-II) type ques...,,,,,,,,False,,
2,3,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,Section D has 1 Long Answer (LA) type question...,,,,,,,,False,,
3,4,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,7,Section E has 2 Source based /Case-based /Pass...,,,,,,,,False,,
4,5,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,1,The acronym SSH stands for_________________. a...,,,,,,,,False,,
5,6,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,2,Which of the following is an example of social...,,,,,,,,False,,
6,7,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,3,M in HTML stands for: a. Modify b. Management ...,,,,,,,,False,,
7,8,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,A _____________ is an online journal or inform...,,,,,,,,False,,
8,9,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Which of the following is not a valid value fo...,,,,,,,,False,,
9,10,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,"link, vlink, alink are attributes of__________...",,,,,,,,False,,

In [23]:
import re

def detect_question_type(text):
    text_lower = text.lower()

    if re.search(r"\(a\).*?\(b\).*?\(c\).*?\(d\)", text, re.DOTALL):
        return "MCQ"
    elif "assertion" in text_lower and "reason" in text_lower:
        return "Assertion-Reason"
    elif "case-based" in text_lower or "passage" in text_lower:
        return "Case-Based"
    else:
        return "Short/Long Answer"


def extract_options(text):
    matches = re.findall(
        r"\([a-dA-D]\)\s*(.*?)(?=\s*\([a-dA-D]\)|$)",
        text,
        re.DOTALL
    )

    return " | ".join(x.strip() for x in matches)


question_bank["question_type"] = question_bank["question_text"].apply(
    detect_question_type
)

question_bank["options"] = question_bank["question_text"].apply(
    extract_options
)

display(
    question_bank[
        ["question_id", "class", "subject",
         "question_number", "question_type", "options",
         "question_text"]
    ].head(10)
)

,question_id,class,subject,question_number,question_type,options,question_text
0,1,class10,computer_application,4,Short/Long Answer,,Section B has 7 Short Answer (SA-I) type quest...
1,2,class10,computer_application,5,Short/Long Answer,,Section C has 4 Short Answer (SA-II) type ques...
2,3,class10,computer_application,6,Short/Long Answer,,Section D has 1 Long Answer (LA) type question...
3,4,class10,computer_application,7,Case-Based,,Section E has 2 Source based /Case-based /Pass...
4,5,class10,computer_application,1,Short/Long Answer,,The acronym SSH stands for_________________. a...
5,6,class10,computer_application,2,Short/Long Answer,,Which of the following is an example of social...
6,7,class10,computer_application,3,Short/Long Answer,,M in HTML stands for: a. Modify b. Management ...
7,8,class10,computer_application,4,Short/Long Answer,,A _____________ is an online journal or inform...
8,9,class10,computer_application,5,Short/Long Answer,,Which of the following is not a valid value fo...
9,10,class10,computer_application,6,Short/Long Answer,,"link, vlink, alink are attributes of__________..."

In [24]:
final_file = processed_folder / "question_bank_enriched.csv"

question_bank.to_csv(
    final_file,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:")
print(final_file)

Saved:
E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\question_bank_enriched.csv

In [25]:
df=pd.read_csv('E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\question_bank_enriched.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\vivek\AppData\Local\Temp\ipykernel_15932\1262069675.py:1: SyntaxWarning: invalid escape sequence '\C'
  df=pd.read_csv('E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\question_bank_enriched.csv')

,question_id,class,subject,session,source_file,question_number,question_text,answer,section,question_type,options,marks,topic,difficulty,has_diagram,correct_answer,answer_explanation
0,1,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,4,Section B has 7 Short Answer (SA-I) type quest...,NaN,NaN,Short/Long Answer,NaN,NaN,NaN,NaN,False,NaN,NaN
1,2,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,5,Section C has 4 Short Answer (SA-II) type ques...,NaN,NaN,Short/Long Answer,NaN,NaN,NaN,NaN,False,NaN,NaN
2,3,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,6,Section D has 1 Long Answer (LA) type question...,NaN,NaN,Short/Long Answer,NaN,NaN,NaN,NaN,False,NaN,NaN
3,4,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,7,Section E has 2 Source based /Case-based /Pass...,NaN,NaN,Case-Based,NaN,NaN,NaN,NaN,False,NaN,NaN
4,5,class10,computer_application,Unknown,ComputerApplication-SQP -23-24.pdf,1,The acronym SSH stands for_________________. a...,NaN,NaN,Short/Long Answer,NaN,NaN,NaN,NaN,False,NaN,NaN

In [26]:
df.shape

(1891, 17)

In [27]:
df.describe()

,question_id,question_number,answer,section,marks,topic,difficulty,correct_answer,answer_explanation
count,1891.000000,1891.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,946.000000,19.283977,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,546.028998,23.530128,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,473.500000,7.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,946.000000,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1418.500000,29.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1891.000000,800.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df.columns

Index(['question_id', 'class', 'subject', 'session', 'source_file',
       'question_number', 'question_text', 'answer', 'section',
       'question_type', 'options', 'marks', 'topic', 'difficulty',
       'has_diagram', 'correct_answer', 'answer_explanation'],
      dtype='str')

In [29]:
display(question_bank.head(10).T)

,0,1,2,3,4,5,6,7,8,9
question_id,1,2,3,4,5,6,7,8,9,10
class,class10,class10,class10,class10,class10,class10,class10,class10,class10,class10
subject,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application
session,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
source_file,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf
question_number,4,5,6,7,1,2,3,4,5,6
question_text,Section B has 7 Short Answer (SA-I) type quest...,Section C has 4 Short Answer (SA-II) type ques...,Section D has 1 Long Answer (LA) type question...,Section E has 2 Source based /Case-based /Pass...,The acronym SSH stands for_________________. a...,Which of the following is an example of social...,M in HTML stands for: a. Modify b. Management ...,A _____________ is an online journal or inform...,Which of the following is not a valid value fo...,"link, vlink, alink are attributes of__________..."
answer,,,,,,,,,,
section,,,,,,,,,,
question_type,Short/Long Answer,Short/Long Answer,Short/Long Answer,Case-Based,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer
options,,,,,,,,,,
marks,,,,,,,,,,
topic,,,,,,,,,,
difficulty,,,,,,,,,,
has_diagram,False,False,False,False,False,False,False,False,False,False
correct_answer,,,,,,,,,,
answer_explanation,,,,,,,,,,

In [30]:
clean_bank = question_bank[
    ~question_bank["question_text"].str.startswith("Section", na=False)
].copy()

print("Before cleaning:", len(question_bank))
print("After removing section text:", len(clean_bank))

display(clean_bank.head(10).T)

Before cleaning: 1891
After removing section text: 1827

,4,5,6,7,8,9,10,11,12,13
question_id,5,6,7,8,9,10,11,12,13,14
class,class10,class10,class10,class10,class10,class10,class10,class10,class10,class10
subject,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application,computer_application
session,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
source_file,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf,ComputerApplication-SQP -23-24.pdf
question_number,1,2,3,4,5,6,7,8,9,10
question_text,The acronym SSH stands for_________________. a...,Which of the following is an example of social...,M in HTML stands for: a. Modify b. Management ...,A _____________ is an online journal or inform...,Which of the following is not a valid value fo...,"link, vlink, alink are attributes of__________...",The_______ attribute of <img> tag specifies an...,Which of the following tag can be used to draw...,"In HTML, <dl>, <dd> and <dt> tags are used to ...",A software _________ is a legal instrument gov...
answer,,,,,,,,,,
section,,,,,,,,,,
question_type,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Short/Long Answer,Assertion-Reason
options,,,,,,,,,,and Reason (R). Select the most suitable optio...
marks,,,,,,,,,,
topic,,,,,,,,,,
difficulty,,,,,,,,,,
has_diagram,False,False,False,False,False,False,False,False,False,False
correct_answer,,,,,,,,,,
answer_explanation,,,,,,,,,,

In [31]:
print("Empty questions:", clean_bank["question_text"].isna().sum())

print(
    "Very short questions:",
    (clean_bank["question_text"].fillna("").str.len() < 20).sum()
)

print(
    "Duplicate questions:",
    clean_bank.duplicated(
        subset=["class", "subject", "question_text"]
    ).sum()
)

Empty questions: 0
Very short questions: 0
Duplicate questions: 82

In [32]:
duplicates = clean_bank[
    clean_bank.duplicated(
        subset=["class", "subject", "question_text"],
        keep=False
    )
]

display(
    duplicates[
        ["class", "subject", "source_file", "question_text"]
    ].sort_values(["class", "subject", "question_text"]).head(20)
)

,class,subject,source_file,question_text
346,class10,social_science,SocialScience-SQP -24-25.pdf,There is no overall choice in the question pap...
384,class10,social_science,SocialScience-SQP-25-26.pdf,There is no overall choice in the question pap...
496,class9,maths,CBSE Class 9 Maths Sample Paper Set 3 for 2026...,"All Questions are compulsory. However, an inte..."
549,class9,maths,CBSE Class 9 Maths Sample Paper Set 4 (2026-27...,"All Questions are compulsory. However, an inte..."
649,class9,maths,CBSE Class 9 Maths Sample Question Paper (Set ...,"All Questions are compulsory. However, an inte..."
712,class9,maths,CBSE Class 9 Maths Sample Question Paper (Set ...,"All Questions are compulsory. However, an inte..."
844,class9,maths,Class 9 CBSE Maths Sample Paper Set 5 – FREE P...,"All Questions are compulsory. However, an inte..."
497,class9,maths,CBSE Class 9 Maths Sample Paper Set 3 for 2026...,Draw neat figures wherever required. Take π =2...
550,class9,maths,CBSE Class 9 Maths Sample Paper Set 4 (2026-27...,Draw neat figures wherever required. Take π =2...
845,class9,maths,Class 9 CBSE Maths Sample Paper Set 5 – FREE P...,Draw neat figures wherever required. Take π =2...
650,class9,maths,CBSE Class 9 Maths Sample Question Paper (Set ...,Draw neat figures wherever required. Take π =2...
713,class9,maths,CBSE Class 9 Maths Sample Question Paper (Set ...,Draw neat figures wherever required. Take π =2...
1294,class9,science,CBSE Class 9 Science Sample Question Paper (Se...,"(A) Both (A) and (R) are true, and (R) is the ..."
1374,class9,science,Class 9 Science Sample Paper Set 3 Download FR...,"(A) Both (A) and (R) are true, and (R) is the ..."
1297,class9,science,CBSE Class 9 Science Sample Question Paper (Se...,"(A) Both (A) and (R) are true, and (R) is the ..."
1377,class9,science,Class 9 Science Sample Paper Set 3 Download FR...,"(A) Both (A) and (R) are true, and (R) is the ..."
1279,class9,science,CBSE Class 9 Science Sample Question Paper (Se...,(A) Pearl Explanation: Oysters are cultivated ...
1373,class9,science,Class 9 Science Sample Paper Set 3 Download FR...,(A) Pearl Explanation: Oysters are cultivated ...
1074,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,(A) is correct Explanation: Valence electrons ...
1155,class9,science,CBSE Class 9 Science Sample Paper Set 4 (2026-...,(A) is correct Explanation: Valence electrons ...

In [33]:
instruction_patterns = (
    "all questions",
    "there is no overall choice",
    "draw neat figures",
    "general instructions",
    "(a) both",
    "(a) is correct",
    "(a) pearl explanation"
)

clean_bank = clean_bank[
    ~clean_bank["question_text"]
    .fillna("")
    .str.lower()
    .str.startswith(instruction_patterns)
].copy()

print("Rows after removing obvious non-questions:", len(clean_bank))

Rows after removing obvious non-questions: 1796

In [34]:
print(
    "Duplicate questions:",
    clean_bank.duplicated(
        subset=["class", "subject", "question_text"]
    ).sum()
)

Duplicate questions: 70

In [35]:
duplicates = clean_bank[
    clean_bank.duplicated(
        subset=["class", "subject", "question_text"],
        keep=False
    )
]

display(
    duplicates[
        ["class", "subject", "source_file", "question_text"]
    ].head(10)
)

,class,subject,source_file,question_text
1035,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,The pictures show the arrangement of electrons...
1038,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,"In a laboratory, while doing an experiment, ca..."
1040,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,Which of the following figures does not repres...
1043,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,What would be the valency of an element that i...
1044,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,A few substances are arranged in the increasin...
1045,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,Contractile proteins are found in: (A) Bones (...
1047,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,Which of these is an alloy? (A) Silver (B) Cop...
1049,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,The area below v-t graph is a measure of: a) A...
1050,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,"On converting 25°C, 38°C and 66°C to Kelvin sc..."
1051,class9,science,CBSE Class 9 Science Sample Paper Set 2 (2026-...,Assertion (A): When heat energy is supplied to...

In [36]:
duplicate_check = (
    duplicates
    .groupby(["source_file", "question_text"])
    .size()
    .reset_index(name="count")
)

display(
    duplicate_check[
        duplicate_check["count"] > 1
    ].head(10)
)

,source_file,question_text,count
105,CBSE Class 9 Science Sample Question Paper (Se...,Which of one of the following nutrients is not...,2

In [37]:
clean_bank = clean_bank.drop_duplicates(
    subset=["class", "subject", "source_file", "question_text"],
    keep="first"
).copy()

print("Rows after removing exact duplicates:", len(clean_bank))

Rows after removing exact duplicates: 1795

In [38]:
print(clean_bank["session"].value_counts())

session
2026-27    991
Unknown    743
2025-26     61
Name: count, dtype: int64

In [39]:
import re

def get_session(filename):
    match = re.search(r"(20\d{2}-\d{2})", filename)
    
    if match:
        return match.group(1)
    
    match = re.search(r"(\d{2})-(\d{2})", filename)
    
    if match:
        return "20" + match.group(1) + "-" + match.group(2)
    
    return "Unknown"

clean_bank["session"] = clean_bank["source_file"].apply(get_session)

print(clean_bank["session"].value_counts())

session
2026-27    991
Unknown    358
2025-26    166
2024-25    141
2023-24    139
Name: count, dtype: int64

In [40]:
unknown_sessions = clean_bank[
    clean_bank["session"] == "Unknown"
]

display(
    unknown_sessions[
        ["class", "subject", "source_file"]
    ].drop_duplicates().head(30)
)

,class,subject,source_file
846,class9,maths,Class 9 CBSE Maths Sample Paper Set 5 – FREE P...
1609,class9,social_science,CBSE Class 9 Social Science Set 5 Sample Paper...
1666,class9,social_science,Class 9 Social Science Sample Paper (Set 2) - ...
1749,class9,social_science,Class 9 Social Science Sample Paper (Set 4) - ...
1820,class9,social_science,Download FREE Sample Paper Set 3 for CBSE Clas...

In [41]:
print(
    unknown_sessions["source_file"]
    .drop_duplicates()
    .to_string(index=False)
)

Class 9 CBSE Maths Sample Paper Set 5 – FREE PD...
CBSE Class 9 Social Science Set 5 Sample Paper ...
Class 9 Social Science Sample Paper (Set 2) - F...
Class 9 Social Science Sample Paper (Set 4) - F...
Download FREE Sample Paper Set 3 for CBSE Class...

In [42]:
for filename in unknown_sessions["source_file"].drop_duplicates():

    pdf_path = next(pdf for pdf in pdf_files if pdf.name == filename)

    doc = pymupdf.open(pdf_path)

    first_page_text = doc[0].get_text("text")

    print("\n" + "=" * 80)
    print(filename)
    print("-" * 80)
    print(first_page_text[:1500])

    doc.close()

================================================================================
Class 9 CBSE Maths Sample Paper Set 5 – FREE PDF & Expert Solutions.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class IX Maths Sample Paper – Set 5
Max. Marks: 80






Time Allowed: 3 hours
General Instructions:
1. This Question Paper has 5 Sections A-E.
2. Section A has 20 MCQs carrying 1 mark each.
3. Section B has 5 questions carrying 02 marks each.
4. Section C has 6 questions carrying 03 marks each.
5. Section D has 4 questions carrying 05 marks each.
6. Section E has 3 case based integrated units of assessment carrying 04 marks each.
7. All Questions are compulsory. However, an internal choice in 2 Qs of 5 marks, 2 Qs of 3
marks and 2 Questions of 2 marks has been provided. An internal choice has been provided in
the 2 marks questions of Section E.
8. Draw neat figures wherever required. Take π =22/7 wherever required if not stated.

Q.
No.
Questions
Marks
Section A
1.
If f is a differentiable function and
( )
0
f
x

= for all x in some interval, then
( )
f x is
1


================================================================================
CBSE Class 9 Social Science Set 5 Sample Paper with Solutions - FREE PDF.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class IX Social Science Sample Paper – Set 5
Max. Marks: 80                                                                                   Time Allowed: 3 hours

General Instructions:
i. Question paper comprises five Sections – A, B, C, D, and E. There are 37 questions in the
question paper. All questions are compulsory.
ii. Section A Questions 1 to 20 are MCQs of 1 mark each.
iii. Section B - Questions no. 21 to 24 are Very Short Answer Type Questions, carrying 2 marks
each. The answer to each question should not exceed 40 words.
iv. Section C - Questions no. 25 to Q.29 are Short Answer Type Questions, carrying 3 marks
each. The answer to each question should not exceed 60 words,
v. Section D - Questions no. 30 to 33 are Long Answer Type Questions, carrying 5 marks each.
Answer to each question should not exceed 120 words
vi. Section E - Questions no. from 34 to 36 are Case Based Questions with three sub-questions
and are of 4 marks each.
vii. Section F - Question no. 37 is Map-based, carrying 5 marks with two parts, 37a from
History (2 marks) and 37b from Geography (3 marks).




================================================================================
Class 9 Social Science Sample Paper (Set 2) - FREE PDF Download.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class 9 Social Science Sample Paper – Set 2
Max. Marks: 80                                                                                   Time Allowed: 3 hours

General Instructions:
Question paper comprises five Sections - A, B, C, D, and E. There are 37 questions in the
question paper. All questions are compulsory.
i.
Section A - Questions 1 to 20 are MCQs of 1 mark each.
ii.
Section B - Questions no. 21 to 24 are Very Short Answer Type Questions, carrying 2
marks each. The answer to each question should not exceed 40 words.
iii.
Section C – Questions no. 25 to Q.29 are Short Answer Type Questions, carrying 3
marks each. The answer to each question should not exceed 60 words,
iv.
Section D - Questions no. 30 to 33 are Long Answer Type Questions, carrying 5 marks
each. Answer to each question should not exceed 120 words
v.
Section E - Questions no. from 34 to 36 are Case Based Questions with three sub-
questions and are of 4 marks each.
vi.
Section F - Question no. 37 is Map-based, carrying 5 marks with two parts, 37a from
History (2 marks) and 37b from Geography (3 marks).
vii.
There is no overall choice in the question paper. However, an internal choice has been
provided in a few questions. Only one of the choices in such questions has to be
attempted.
viii.
In addition to this, separate instructions are given with each section and question,
wherever necessary.





================================================================================
Class 9 Social Science Sample Paper (Set 4) - FREE PDF Download.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class 9 Social Science Sample Paper – Set 4
Max. Marks: 80                                                                                   Time Allowed: 3 hours

General Instructions:
The question paper comprises five Sections - A, B, C, D, and E. There are 37 questions on
the question paper. All questions are compulsory.
i.
Section A - Questions 1 to 20 are MCQs of 1 mark each.
ii.
Section B - Questions no. 21 to 24 are Very Short Answer Type Questions, carrying 2
marks each. The answer to each question should not exceed 40 words.
iii.
Section C – Questions no. 25 to Q.29 are Short Answer Type Questions, carrying 3
marks each. The answer to each question should not exceed 60 words,
iv.
Section D - Questions no. 30 to 33 are Long Answer Type Questions, carrying 5
marks each. Answer to each question should not exceed 120 words
v.
Section E - Questions no. from 34 to 36 are Case Based Questions with three sub-
questions and are of 4 marks each.
vi.
Section F - Question no. 37 is Map-based, carrying 5 marks with two parts, 37a from
History (2 marks) and 37b from Geography (3 marks).
vii.
There is no overall choice in the question paper. However, an internal choice has been
provided in a few questions. Only one of the choices in such questions has to be
attempted.
viii.
In addition to this, separate instructions are given with each section and question,
wherever necessary.






================================================================================
Download FREE Sample Paper Set 3 for CBSE Class 9 Social Science.pdf
--------------------------------------------------------------------------------




www.vedantu.com
1



Class IX Social Science Sample Paper – Set 3
Max. Marks: 80 Marks

                             Time Allowed: 3 hours

General Instructions:
i. Question paper comprises five Sections – A, B, C, D, and E. There are 37 questions in the
question paper. All questions are compulsory.
ii. Section A Questions 1 to 20 are MCQs of 1 mark each.
iii. Section B - Questions no. 21 to 24 are Very Short Answer Type Questions, carrying 2 marks
each. The answer to each question should not exceed 40 words.
iv. Section C - Questions no. 25 to Q.29 are Short Answer Type Questions, carrying 3 marks
each. The answer to each question should not exceed 60 words,
v. Section D - Questions no. 30 to 33 are Long Answer Type Questions, carrying 5 marks each.
Answer to each question should not exceed 120 words
vi. Section E - Questions no. from 34 to 36 are Case Based Questions with three sub-questions
and are of 4 marks each.
vii. Section F - Question no. 37 is Map-based, carrying 5 marks with two parts, 37a from
History (2 marks) and 37b from Geography (3 marks).
viii. There is no overall choice in the question paper. However, an internal choice has been
provided in a few questions. Only one of the choices in such questions has to be attempted.
ix. In addition to this, separate instructions are given with each section and question, wherever
necessary.

In [43]:
clean_bank.loc[
    (clean_bank["class"] == "class9") &
    (clean_bank["session"] == "Unknown"),
    "session"
] = "2026-27"

print(clean_bank["session"].value_counts())

session
2026-27    1349
2025-26     166
2024-25     141
2023-24     139
Name: count, dtype: int64

In [44]:
print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1571
MCQ                   166
Assertion-Reason       47
Case-Based             11
Name: count, dtype: int64

In [45]:
display(
    clean_bank[
        clean_bank["question_type"] == "Short/Long Answer"
    ][
        ["class", "subject", "source_file", "question_number", "question_text"]
    ].head(15)
)

,class,subject,source_file,question_number,question_text
4,class10,computer_application,ComputerApplication-SQP -23-24.pdf,1,The acronym SSH stands for_________________. a...
5,class10,computer_application,ComputerApplication-SQP -23-24.pdf,2,Which of the following is an example of social...
6,class10,computer_application,ComputerApplication-SQP -23-24.pdf,3,M in HTML stands for: a. Modify b. Management ...
7,class10,computer_application,ComputerApplication-SQP -23-24.pdf,4,A _____________ is an online journal or inform...
8,class10,computer_application,ComputerApplication-SQP -23-24.pdf,5,Which of the following is not a valid value fo...
9,class10,computer_application,ComputerApplication-SQP -23-24.pdf,6,"link, vlink, alink are attributes of__________..."
10,class10,computer_application,ComputerApplication-SQP -23-24.pdf,7,The_______ attribute of <img> tag specifies an...
11,class10,computer_application,ComputerApplication-SQP -23-24.pdf,8,Which of the following tag can be used to draw...
12,class10,computer_application,ComputerApplication-SQP -23-24.pdf,9,"In HTML, <dl>, <dd> and <dt> tags are used to ..."
16,class10,computer_application,ComputerApplication-SQP -23-24.pdf,13,Write any two points of comparison in between ...
17,class10,computer_application,ComputerApplication-SQP -23-24.pdf,14,What is e-Learning? Mention its two main advan...
18,class10,computer_application,ComputerApplication-SQP -23-24.pdf,15,Compare 3G and 4G mobile technologies on any t...
19,class10,computer_application,ComputerApplication-SQP -23-24.pdf,16,Which software are termed as open-source softw...
20,class10,computer_application,ComputerApplication-SQP -23-24.pdf,17,Mention any two purposes of using comments whi...
21,class10,computer_application,ComputerApplication-SQP -23-24.pdf,18,Twisha has got confused with a few tags and th...

In [46]:
mcq_pattern = r"(?is)(?:\(?a\)?[\.\):])[\s\S]+(?:\(?b\)?[\.\):])[\s\S]+(?:\(?c\)?[\.\):])[\s\S]+(?:\(?d\)?[\.\):])"

is_mcq = clean_bank["question_text"].fillna("").str.contains(
    mcq_pattern,
    regex=True
)

clean_bank.loc[is_mcq, "question_type"] = "MCQ"

print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1193
MCQ                   569
Assertion-Reason       25
Case-Based              8
Name: count, dtype: int64

In [47]:
# Restore the original question types
original_types = question_bank.set_index("question_id")["question_type"]

clean_bank["question_type"] = clean_bank["question_id"].map(original_types)

# Change only Short/Long Answer rows that clearly contain a,b,c,d options
is_mcq = clean_bank["question_text"].fillna("").str.contains(
    mcq_pattern,
    regex=True
)

clean_bank.loc[
    is_mcq & clean_bank["question_type"].eq("Short/Long Answer"),
    "question_type"
] = "MCQ"

print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1193
MCQ                   544
Assertion-Reason       47
Case-Based             11
Name: count, dtype: int64

In [48]:
display(
    clean_bank[
        clean_bank["question_type"] == "MCQ"
    ][
        ["class", "subject", "question_text"]
    ].head(10)
)

,class,subject,question_text
4,class10,computer_application,The acronym SSH stands for_________________. a...
5,class10,computer_application,Which of the following is an example of social...
6,class10,computer_application,M in HTML stands for: a. Modify b. Management ...
7,class10,computer_application,A _____________ is an online journal or inform...
8,class10,computer_application,Which of the following is not a valid value fo...
9,class10,computer_application,"link, vlink, alink are attributes of__________..."
10,class10,computer_application,The_______ attribute of <img> tag specifies an...
11,class10,computer_application,Which of the following tag can be used to draw...
12,class10,computer_application,"In HTML, <dl>, <dd> and <dt> tags are used to ..."
14,class10,computer_application,Assertion (A): Search engine is a hardware dev...

In [49]:
# Fix Assertion-Reason questions first
is_assertion_reason = (
    clean_bank["question_text"]
    .fillna("")
    .str.contains("assertion", case=False)
    &
    clean_bank["question_text"]
    .fillna("")
    .str.contains("reason", case=False)
)

clean_bank.loc[is_assertion_reason, "question_type"] = "Assertion-Reason"

print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1193
MCQ                   519
Assertion-Reason       72
Case-Based             11
Name: count, dtype: int64

In [50]:
display(
    clean_bank[
        clean_bank["question_type"] == "Case-Based"
    ][
        ["class", "subject", "question_text"]
    ].head(10)
)

,class,subject,question_text
78,class10,home_science,CASE STUDY BASED QUESTIONS Read the passage ca...
111,class10,home_science,Read the passage carefully and answer Question...
331,class10,social_science,(A) : A farmer has borrowed money from a money...
383,class10,social_science,Which of the following is the main factor that...
532,class9,maths,Construct a right triangle whose hypotenuse is...
543,class9,maths,Join BC. Then ABC is right-angled with hypoten...
913,class9,maths,0.3 0.2 0.5. P X P X P X P X  = + + =  = = +...
1499,class9,social_science,Read the following passage and answer the ques...
1561,class9,social_science,Give reasons as to why. i. Seasonal reversal o...
1562,class9,social_science,Read the following text carefully and answer t...

In [51]:
display(
    clean_bank[
        clean_bank["question_type"] == "Case-Based"
    ][
        ["class", "subject", "source_file",
         "question_number", "question_text"]
    ]
)

,class,subject,source_file,question_number,question_text
78,class10,home_science,HomeScience-SQP -23-24.pdf,14,CASE STUDY BASED QUESTIONS Read the passage ca...
111,class10,home_science,HomeScience-SQP -24-25.pdf,16,Read the passage carefully and answer Question...
331,class10,social_science,SocialScience-SQP -23-24.pdf,33,(A) : A farmer has borrowed money from a money...
383,class10,social_science,SocialScience-SQP -24-25.pdf,17,Which of the following is the main factor that...
532,class9,maths,CBSE Class 9 Maths Sample Paper Set 3 for 2026...,35,Construct a right triangle whose hypotenuse is...
543,class9,maths,CBSE Class 9 Maths Sample Paper Set 3 for 2026...,4,Join BC. Then ABC is right-angled with hypoten...
913,class9,maths,Class 9 CBSE Maths Sample Paper Set 5 – FREE P...,3,0.3 0.2 0.5. P X P X P X P X  = + + =  = = +...
1499,class9,social_science,CBSE Class 9 Social Science Sample Paper 2026-...,35,Read the following passage and answer the ques...
1561,class9,social_science,CBSE Class 9 Social Science Sample Paper Set 1...,33,Give reasons as to why. i. Seasonal reversal o...
1562,class9,social_science,CBSE Class 9 Social Science Sample Paper Set 1...,34,Read the following text carefully and answer t...
1603,class9,social_science,CBSE Class 9 Social Science Sample Paper Set 1...,34,i. The passage reflects the Nazi racial ideolo...

In [52]:
# Reset current Case-Based labels
clean_bank.loc[
    clean_bank["question_type"] == "Case-Based",
    "question_type"
] = "Short/Long Answer"

# Identify clearly case/passage-based questions
text = clean_bank["question_text"].fillna("")

is_case = (
    text.str.contains("case study", case=False, na=False)
    | text.str.contains("read the passage", case=False, na=False)
    | text.str.contains("read the following text", case=False, na=False)
)

clean_bank.loc[is_case, "question_type"] = "Case-Based"

print(clean_bank["question_type"].value_counts())

question_type
Short/Long Answer    1172
MCQ                   517
Assertion-Reason       72
Case-Based             34
Name: count, dtype: int64

In [53]:
print(
    "MCQs with empty options:",
    clean_bank.loc[
        clean_bank["question_type"] == "MCQ",
        "options"
    ].fillna("").str.strip().eq("").sum()
)

MCQs with empty options: 195

In [54]:
display(
    clean_bank[
        (clean_bank["question_type"] == "MCQ") &
        (clean_bank["options"].fillna("").str.strip() == "")
    ][
        ["class", "subject", "question_text"]
    ].head(5)
)

,class,subject,question_text
4,class10,computer_application,The acronym SSH stands for_________________. a...
5,class10,computer_application,Which of the following is an example of social...
6,class10,computer_application,M in HTML stands for: a. Modify b. Management ...
7,class10,computer_application,A _____________ is an online journal or inform...
8,class10,computer_application,Which of the following is not a valid value fo...

In [55]:
for _, row in clean_bank[
    (clean_bank["question_type"] == "MCQ") &
    (clean_bank["options"].fillna("").str.strip() == "")
].head(5).iterrows():

    print("\nQUESTION:")
    print(row["question_text"])
    print("-" * 80)

QUESTION:
The acronym SSH stands for_________________. a. Safe Shell b. Software Shell c. Secure Shell d. Simple Shell
--------------------------------------------------------------------------------

QUESTION:
Which of the following is an example of social networking website? a. wikipedia.org b. Facebook.com c. cbse.gov.in d. ncert.nic.in
--------------------------------------------------------------------------------

QUESTION:
M in HTML stands for: a. Modify b. Management c. Multiple d. Markup
--------------------------------------------------------------------------------

QUESTION:
A _____________ is an online journal or informational website run by an individual, group, or corporation that offers regularly updated content about a topic. a. News group b. Blog c. WWW d. e-Groups
--------------------------------------------------------------------------------

QUESTION:
Which of the following is not a valid value for the target attribute of <a> tag? a. _blank b. _self c. _top d. _bottom Page 2 of 5
--------------------------------------------------------------------------------

In [56]:
def extract_options(text):
    pattern = r"(?i)(?:^|\s)([a-d])\.\s*(.*?)(?=\s+[a-d]\.\s+|$)"
    matches = re.findall(pattern, text)

    return " | ".join(
        f"{letter}. {option.strip()}"
        for letter, option in matches
    )

clean_bank["options"] = clean_bank["question_text"].apply(extract_options)

print(
    "MCQs with options:",
    clean_bank.loc[
        clean_bank["question_type"] == "MCQ",
        "options"
    ].ne("").sum()
)

MCQs with options: 100

In [57]:
display(
    clean_bank[
        (clean_bank["question_type"] == "MCQ") &
        (clean_bank["options"].fillna("").str.strip() == "")
    ][
        ["class", "subject", "source_file", "question_text"]
    ].head(5)
)

,class,subject,source_file,question_text
97,class10,home_science,HomeScience-SQP -24-25.pdf,“While advertising manufacturers often give an...
98,class10,home_science,HomeScience-SQP -24-25.pdf,Which of the following characteristic of cogni...
99,class10,home_science,HomeScience-SQP -24-25.pdf,The food whose nature or quality is so affecte...
100,class10,home_science,HomeScience-SQP -24-25.pdf,Which of the following are characteristics to ...
101,class10,home_science,HomeScience-SQP -24-25.pdf,“Adolescents give more importance to their fri...

In [58]:
for _, row in clean_bank[
    (clean_bank["question_type"] == "MCQ") &
    (clean_bank["options"].fillna("").str.strip() == "")
].head(5).iterrows():

    print("\nQUESTION:")
    print(row["question_text"])
    print("-" * 80)

QUESTION:
“While advertising manufacturers often give an exaggerated picture of their product”. Which malpractice of manufacturer is exhibited in this statement? (A)Charging high price (B)Adulteration of goods (C)Misleading information (D)Lack of standardized products 1
--------------------------------------------------------------------------------

QUESTION:
Which of the following characteristic of cognitive development is observed in 4 to 6 years old child? (A) Diminished egocentrism (B) Ability to conserve (C) Egocentrism (D) Can differentiate between living and non-living things OR Which of the following characteristic of emotional development is observed in 8 to 10 years old child? (A) Have imaginary friends (B) Can control impulses (C) Do not hide emotions (D)Emotions are transitory (change rapidly) and unpredictable 1 2
--------------------------------------------------------------------------------

QUESTION:
The food whose nature or quality is so affected that it is injurious to health is- (A) Organic food (B) Unsafe food (C) Raw food (D) Super food 1
--------------------------------------------------------------------------------

QUESTION:
Which of the following are characteristics to identify a stain on a fabric? (A) Colour, smell or feel (B) Colour, taste or look (C)Taste, shape or feel (D) Colour, shape or feel 1
--------------------------------------------------------------------------------

QUESTION:
“Adolescents give more importance to their friends and like to spend more time with them.” Which type of development is exhibited in this statement? (A) Physical (B) Language (C) Social (D) Cognitive 1
--------------------------------------------------------------------------------

In [59]:
def extract_options(text):
    pattern = r"(?i)(?:^|\s)(\([a-d]\)|[a-d][\.\:\)])\s+(.+?)(?=\s+(?:\([a-d]\)|[a-d][\.\:\)])\s+|$)"
    
    matches = re.findall(pattern, text)

    return " | ".join(
        f"{label.upper()} {option.strip()}"
        for label, option in matches
    )


clean_bank["options"] = clean_bank["question_text"].apply(extract_options)

print(
    "MCQs with options:",
    clean_bank.loc[
        clean_bank["question_type"] == "MCQ",
        "options"
    ].ne("").sum()
)

MCQs with options: 515

In [60]:
display(
    clean_bank[
        clean_bank["question_type"] == "MCQ"
    ][["question_text", "options"]].head(5)
)

,question_text,options
4,The acronym SSH stands for_________________. a...,A. Safe Shell | B. Software Shell | C. Secure ...
5,Which of the following is an example of social...,A. wikipedia.org | B. Facebook.com | C. cbse.g...
6,M in HTML stands for: a. Modify b. Management ...,A. Modify | B. Management | C. Multiple | D. M...
7,A _____________ is an online journal or inform...,A. News group | B. Blog | C. WWW | D. e-Groups
8,Which of the following is not a valid value fo...,A. _blank | B. _self | C. _top | D. _bottom Pa...

In [61]:
display(
    clean_bank[
        (clean_bank["question_type"] == "MCQ") &
        (clean_bank["options"].fillna("").str.strip() == "")
    ][
        ["class", "subject", "source_file", "question_text"]
    ]
)

,class,subject,source_file,question_text
97,class10,home_science,HomeScience-SQP -24-25.pdf,“While advertising manufacturers often give an...
1761,class9,social_science,Class 9 Social Science Sample Paper (Set 4) - ...,Arrange the following events in chronological ...

In [62]:
for _, row in clean_bank[
    (clean_bank["question_type"] == "MCQ") &
    (clean_bank["options"].fillna("").str.strip() == "")
].iterrows():

    print("\nQUESTION:")
    print(row["question_text"])
    print("-" * 80)

QUESTION:
“While advertising manufacturers often give an exaggerated picture of their product”. Which malpractice of manufacturer is exhibited in this statement? (A)Charging high price (B)Adulteration of goods (C)Misleading information (D)Lack of standardized products 1
--------------------------------------------------------------------------------

QUESTION:
Arrange the following events in chronological order: i. The Great Economic Depression begins. ii. The mass murder of the Jews begins. iii. Second World War begins. iv. First World War begins. a)iv, ii, i, iii b)iii, i, ii, iv c)i, iv, iii, ii d)iv, i, iii, ii 1
--------------------------------------------------------------------------------

In [63]:
def remove_options(text):
    return re.split(
        r"(?i)\s+(?:\([a-d]\)|[a-d][\.\:\)])\s+",
        text,
        maxsplit=1
    )[0].strip()

clean_bank["question_text_clean"] = (
    clean_bank["question_text"]
    .apply(remove_options)
)

display(
    clean_bank[
        ["question_text", "question_text_clean", "options"]
    ].head(5)
)

,question_text,question_text_clean,options
4,The acronym SSH stands for_________________. a...,The acronym SSH stands for_________________.,A. Safe Shell | B. Software Shell | C. Secure ...
5,Which of the following is an example of social...,Which of the following is an example of social...,A. wikipedia.org | B. Facebook.com | C. cbse.g...
6,M in HTML stands for: a. Modify b. Management ...,M in HTML stands for:,A. Modify | B. Management | C. Multiple | D. M...
7,A _____________ is an online journal or inform...,A _____________ is an online journal or inform...,A. News group | B. Blog | C. WWW | D. e-Groups
8,Which of the following is not a valid value fo...,Which of the following is not a valid value fo...,A. _blank | B. _self | C. _top | D. _bottom Pa...

In [64]:
clean_file = processed_folder / "clean_question_bank.csv"

clean_bank.to_csv(
    clean_file,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", clean_file)
print("Rows:", len(clean_bank))
print("Columns:", len(clean_bank.columns))

Saved: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\clean_question_bank.csv
Rows: 1795
Columns: 18

In [65]:
print("Missing question text:", clean_bank["question_text_clean"].isna().sum())
print("Missing class:", clean_bank["class"].isna().sum())
print("Missing subject:", clean_bank["subject"].isna().sum())
print("Missing session:", clean_bank["session"].isna().sum())

Missing question text: 0
Missing class: 0
Missing subject: 0
Missing session: 0

In [66]:
llm_dataset = clean_bank[
    [
        "question_id",
        "class",
        "subject",
        "session",
        "question_type",
        "question_text_clean",
        "options",
        "source_file"
    ]
].copy()

print("LLM dataset rows:", len(llm_dataset))
print("LLM dataset columns:", llm_dataset.columns.tolist())

display(llm_dataset.head(10))

LLM dataset rows: 1795
LLM dataset columns: ['question_id', 'class', 'subject', 'session', 'question_type', 'question_text_clean', 'options', 'source_file']

,question_id,class,subject,session,question_type,question_text_clean,options,source_file
4,5,class10,computer_application,2023-24,MCQ,The acronym SSH stands for_________________.,A. Safe Shell | B. Software Shell | C. Secure ...,ComputerApplication-SQP -23-24.pdf
5,6,class10,computer_application,2023-24,MCQ,Which of the following is an example of social...,A. wikipedia.org | B. Facebook.com | C. cbse.g...,ComputerApplication-SQP -23-24.pdf
6,7,class10,computer_application,2023-24,MCQ,M in HTML stands for:,A. Modify | B. Management | C. Multiple | D. M...,ComputerApplication-SQP -23-24.pdf
7,8,class10,computer_application,2023-24,MCQ,A _____________ is an online journal or inform...,A. News group | B. Blog | C. WWW | D. e-Groups,ComputerApplication-SQP -23-24.pdf
8,9,class10,computer_application,2023-24,MCQ,Which of the following is not a valid value fo...,A. _blank | B. _self | C. _top | D. _bottom Pa...,ComputerApplication-SQP -23-24.pdf
9,10,class10,computer_application,2023-24,MCQ,"link, vlink, alink are attributes of__________...",A. <body> | B. <a> | C. <html> | D. <img>,ComputerApplication-SQP -23-24.pdf
10,11,class10,computer_application,2023-24,MCQ,The_______ attribute of <img> tag specifies an...,A. alt | B. text | C. alternate | D. msg,ComputerApplication-SQP -23-24.pdf
11,12,class10,computer_application,2023-24,MCQ,Which of the following tag can be used to draw...,A. <line> | B. <hrule> | C. <hr> | D. <rule>,ComputerApplication-SQP -23-24.pdf
12,13,class10,computer_application,2023-24,MCQ,"In HTML, <dl>, <dd> and <dt> tags are used to ...",A. Description list | B. Definition list | C. ...,ComputerApplication-SQP -23-24.pdf
13,14,class10,computer_application,2023-24,Assertion-Reason,A software _________ is a legal instrument gov...,A. license | B. law | C. document | D. piracy ...,ComputerApplication-SQP -23-24.pdf

In [67]:
llm_file = processed_folder / "llm_input_dataset.csv"

llm_dataset.to_csv(
    llm_file,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", llm_file)

Saved: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\llm_input_dataset.csv

In [68]:
import psutil

ram_gb = psutil.virtual_memory().total / (1024 ** 3)

print(f"System RAM: {ram_gb:.1f} GB")

System RAM: 15.9 GB

In [69]:
import torch

print("PyTorch version:", torch.__version__)
print("GPU available:", torch.cuda.is_available())

PyTorch version: 2.14.0+cpu
GPU available: False

In [70]:
from transformers import pipeline
generator = pipeline(
    "text-generation",
    model="Qwen/Qwen2.5-1.5B-Instruct"
)
print("Model loaded successfully!")

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Model loaded successfully!

In [71]:
messages = [
    {"role": "user",
     "content": "Write one simple Class 9 Maths question about linear equations."
    }]
result = generator(messages, max_new_tokens=100)
print(result)

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer Qwen2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

[{'generated_text': [{'role': 'user', 'content': 'Write one simple Class 9 Maths question about linear equations.'}, {'role': 'assistant', 'content': "Sure! Here's a simple Class 9 Maths question about linear equations:\n\n**Question:**\n\nSolve the following system of linear equations:\n\\[ \n\\begin{cases}\n2x + y = 5 \\\\\n3x - y = 1\n\\end{cases}\n\\]\n\nShow all steps in your solution process.\n\n---\n\nThis question tests the student's ability to solve a system of linear equations using either substitution or elimination methods."}]}]

In [72]:
sample = llm_dataset[
    llm_dataset["question_type"] == "MCQ"
].iloc[0]

print("Class:", sample["class"])
print("Subject:", sample["subject"])
print("Type:", sample["question_type"])
print("Question:", sample["question_text_clean"])
print("Options:", sample["options"])

Class: class10
Subject: computer_application
Type: MCQ
Question: The acronym SSH stands for_________________.
Options: A. Safe Shell | B. Software Shell | C. Secure Shell | D. Simple Shell

In [73]:
sample = llm_dataset[
    llm_dataset["question_type"] == "MCQ"
].iloc[0]

print("Class:", sample["class"])
print("Subject:", sample["subject"])
print("Type:", sample["question_type"])
print("Question:", sample["question_text_clean"])
print("Options:", sample["options"])

Class: class10
Subject: computer_application
Type: MCQ
Question: The acronym SSH stands for_________________.
Options: A. Safe Shell | B. Software Shell | C. Secure Shell | D. Simple Shell

In [74]:
from transformers import GenerationConfig

test_generation_config = GenerationConfig(
    max_new_tokens=120,
    do_sample=True,
    temperature=0.7,
    top_p=0.9,
    repetition_penalty=1.15
)

def generate_new_question(class_name, subject, question_type,
                          source_question, source_options):

    prompt = f"""
You are an expert CBSE question paper writer.

Generate ONE completely NEW question for:

Class: {class_name}
Subject: {subject}
Question Type: {question_type}

SOURCE QUESTION:
{source_question}

SOURCE OPTIONS:
{source_options}

Your task:
Create a NEW application-based or scenario-based question
that tests the SAME KNOWLEDGE CONCEPT as the source.

Do not ask a direct definition or full-form question.
Change the question structure completely.
Do not reuse the source wording or source options.

The generated question should preferably use a short
real-world or practical situation.

Very important:
- Do NOT change to a different concept.
- Do NOT introduce an unrelated topic.
- Do NOT copy or paraphrase the source question.
- Do NOT reuse the source options.
- Do NOT simply change one word.
- The new question must be self-contained.
- Do not refer to maps, images, figures, or diagrams.
- For MCQ, provide exactly 4 options.
- Only ONE option must be correct.
- The correct answer must be factually consistent with the SAME concept as the source.

Example of what NOT to do:
Source about SSH -> do NOT create a question about SSL.
Source about social networking websites -> do NOT create a question about backend programming.

Use exactly this format:

QUESTION:
<new question>

A) <option>
B) <option>
C) <option>
D) <option>

ANSWER:
<correct option>
"""

    result = generator(
        [{"role": "user", "content": prompt}],
        generation_config=test_generation_config
    )

    return result[0]["generated_text"][-1]["content"]

In [75]:
generated_file = processed_folder / "generated_questions.csv"

generated_df = pd.read_csv(generated_file)

print("Generated questions:", len(generated_df))
display(generated_df.head(5))

Generated questions: 14

,class,subject,question_type,source_question,generated_question,quality_status
0,class9,science,MCQ,(a) Amoeba and Euglena arc unicellular organis...,QUESTION:\nWhich of the following statements i...,PASS_FORMAT
1,class9,social_science,MCQ,Read the information given below and select th...,QUESTION:\nWhich of the following was a symbol...,PASS_FORMAT
2,class9,social_science,MCQ,The river Narmada has its source at:,QUESTION:\nWhat is the primary source of water...,PASS_FORMAT
3,class9,maths,MCQ,Which of the following numbers cannot be repre...,QUESTION:\nWhich of the following numbers cann...,PASS_FORMAT
4,class9,social_science,MCQ,"On the given map of France, A is marked as a p...","QUESTION:\nOn the given map of France, A is ma...",PASS_FORMAT

In [76]:
display(
    generated_df[
        ["class", "subject", "source_question", "generated_question"]
    ].head(5)
)

,class,subject,source_question,generated_question
0,class9,science,(a) Amoeba and Euglena arc unicellular organis...,QUESTION:\nWhich of the following statements i...
1,class9,social_science,Read the information given below and select th...,QUESTION:\nWhich of the following was a symbol...
2,class9,social_science,The river Narmada has its source at:,QUESTION:\nWhat is the primary source of water...
3,class9,maths,Which of the following numbers cannot be repre...,QUESTION:\nWhich of the following numbers cann...
4,class9,social_science,"On the given map of France, A is marked as a p...","QUESTION:\nOn the given map of France, A is ma..."

In [77]:
for i, row in generated_df.head(5).iterrows():
    print("\n" + "=" * 80)
    print("CLASS:", row["class"])
    print("SUBJECT:", row["subject"])
    print("SOURCE:", row["source_question"])
    print("\nGENERATED:")
    print(row["generated_question"])

================================================================================
CLASS: class9
SUBJECT: science
SOURCE: (a) Amoeba and Euglena arc unicellular organisms. www.vedantu.com 30

GENERATED:
QUESTION:
Which of the following statements is true about amoebas?

A) They have multiple nuclei and chloroplasts.
B) They are photosynthetic and live in water.
C) They reproduce through binary fission but lack cellular structure.
D) They move using pseudopodia and feed on organic matter.

ANSWER:
D) They move using pseudopodia and feed on organic matter.

================================================================================
CLASS: class9
SUBJECT: social_science
SOURCE: Read the information given below and select the correct option. Most of men and women in the eighteenth century could not read or write. So, images and symbols were frequently used instead of printed words to communicate important ideas. Which of the following was a symbol of royal power?

GENERATED:
QUESTION:
Which of the following was a symbol of royal power during the eighteenth century?

A) The Bible
B) The Crown Jewels
C) The Royal Coat of Arms
D) The Flag of Great Britain

ANSWER:
C) The Royal Coat of Arms

================================================================================
CLASS: class9
SUBJECT: social_science
SOURCE: The river Narmada has its source at:

GENERATED:
QUESTION:
What is the primary source of water for the river Narmada?

A) Himalayas
B) Aravallis
C) Western Ghats
D) Eastern Ghats

ANSWER:
B) Aravallis

================================================================================
CLASS: class9
SUBJECT: maths
SOURCE: Which of the following numbers cannot be represented as a terminating decimal?

GENERATED:
QUESTION:
Which of the following numbers cannot be represented as a terminating decimal?

A) 1/3
B) 2/5
C) 7/8
D) 3/2

ANSWER:
A) 1/3

================================================================================
CLASS: class9
SUBJECT: social_science
SOURCE: On the given map of France, A is marked as a place where troops entered following the King’s Command. Identify it from the following options. 1 www.vedantu.com 6

GENERATED:
QUESTION:
On the given map of France, A is marked as a place where troops entered following the King's Command. Identify it from the following options. 3

A) Paris
B) Marseille
C) Strasbourg
D) Bordeaux

ANSWER:
D) Bordeaux

In [78]:
print("Generated:", len(generated_df))

for i, row in generated_df.iterrows():
    print(
        i,
        "|",
        row["class"],
        "|",
        row["subject"]
    )

Generated: 14
0 | class9 | science
1 | class9 | social_science
2 | class9 | social_science
3 | class9 | maths
4 | class9 | social_science
5 | class10 | social_science
6 | class9 | maths
7 | class9 | social_science
8 | class9 | science
9 | class9 | maths
10 | class9 | social_science
11 | class9 | science
12 | class9 | science
13 | class10 | maths

In [79]:
import re
from difflib import SequenceMatcher

def validate_generated(row):
    text = row["generated_question"]

    option_count = len(
        re.findall(r"(?m)^[A-D][\)\.]\s+", text)
    )

    has_answer = bool(
        re.search(r"(?im)^ANSWER:\s*$", text)
    )

    source = row["source_question"]
    similarity = SequenceMatcher(
        None,
        source.lower(),
        text.lower()
    ).ratio()

    if option_count == 4 and has_answer and similarity < 0.75:
        return "PASS_FORMAT"

    return "REVIEW"

generated_df["quality_status"] = generated_df.apply(
    validate_generated,
    axis=1
)

print(generated_df["quality_status"].value_counts())

display(
    generated_df[
        ["class", "subject", "quality_status"]
    ]
)

quality_status
REVIEW    14
Name: count, dtype: int64

      class         subject quality_status
0    class9         science         REVIEW
1    class9  social_science         REVIEW
2    class9  social_science         REVIEW
3    class9           maths         REVIEW
4    class9  social_science         REVIEW
5   class10  social_science         REVIEW
6    class9           maths         REVIEW
7    class9  social_science         REVIEW
8    class9         science         REVIEW
9    class9           maths         REVIEW
10   class9  social_science         REVIEW
11   class9         science         REVIEW
12   class9         science         REVIEW
13  class10           maths         REVIEW

In [80]:
for i, row in generated_df.iterrows():
    text = row["generated_question"]

    option_count = len(
        re.findall(r"(?m)^[A-D][\)\.]\s+", text)
    )

    has_answer = bool(
        re.search(r"(?im)^ANSWER:\s*$", text)
    )

    similarity = SequenceMatcher(
        None,
        row["source_question"].lower(),
        text.lower()
    ).ratio()

    print(
        i,
        "| options:", option_count,
        "| answer:", has_answer,
        "| similarity:", round(similarity, 2)
    )

0 | options: 5 | answer: True | similarity: 0.02
1 | options: 5 | answer: True | similarity: 0.02
2 | options: 5 | answer: True | similarity: 0.33
3 | options: 5 | answer: True | similarity: 0.71
4 | options: 5 | answer: True | similarity: 0.73
5 | options: 5 | answer: True | similarity: 0.05
6 | options: 5 | answer: True | similarity: 0.25
7 | options: 5 | answer: True | similarity: 0.03
8 | options: 5 | answer: True | similarity: 0.05
9 | options: 4 | answer: False | similarity: 0.31
10 | options: 5 | answer: True | similarity: 0.58
11 | options: 5 | answer: True | similarity: 0.0
12 | options: 5 | answer: True | similarity: 0.1
13 | options: 5 | answer: True | similarity: 0.65

In [81]:
def validate_generated(row):
    text = row["generated_question"]

    # Count options only before the ANSWER section
    question_part = text.split("ANSWER:", 1)[0]

    option_count = len(
        re.findall(r"(?m)^[A-D][\)\.]\s+", question_part)
    )

    has_answer = "ANSWER:" in text

    similarity = SequenceMatcher(
        None,
        row["source_question"].lower(),
        text.lower()
    ).ratio()

    if option_count == 4 and has_answer and similarity < 0.75:
        return "PASS_FORMAT"

    return "REVIEW"


generated_df["quality_status"] = generated_df.apply(
    validate_generated,
    axis=1
)

print(generated_df["quality_status"].value_counts())

quality_status
PASS_FORMAT    13
REVIEW          1
Name: count, dtype: int64

In [82]:
display(
    generated_df[
        generated_df["quality_status"] == "REVIEW"
    ][
        ["class", "subject", "source_question", "generated_question"]
    ]
)

,class,subject,source_question,generated_question
9,class9,maths,Which of these is a valid LPP objective functi...,QUESTION:\nWhich of these is a valid LPP objec...

In [83]:
replacement = """QUESTION:
Which event is considered to have marked the beginning of the French Revolution?

A) The storming of the Bastille
B) The signing of the Treaty of Versailles
C) The Reign of Terror
D) Napoleon's rise to power

ANSWER:
A) The storming of the Bastille"""

print(replacement)

QUESTION:
Which event is considered to have marked the beginning of the French Revolution?

A) The storming of the Bastille
B) The signing of the Treaty of Versailles
C) The Reign of Terror
D) Napoleon's rise to power

ANSWER:
A) The storming of the Bastille

In [84]:
accepted_df = generated_df[
    generated_df["quality_status"] == "PASS_FORMAT"
].copy()

replacement_row = {
    "class": "class9",
    "subject": "social_science",
    "question_type": "MCQ",
    "source_question": "French Revolution topic",
    "generated_question": replacement,
    "quality_status": "PASS_FORMAT",
    "answer_status": "Needs verification"
}

accepted_df["answer_status"] = "Needs verification"

accepted_df = pd.concat(
    [accepted_df, pd.DataFrame([replacement_row])],
    ignore_index=True
)

print("Final generated questions:", len(accepted_df))

Final generated questions: 14

In [85]:
final_generated_file = processed_folder / "final_generated_questions.csv"
accepted_df.to_csv(final_generated_file,index=False,encoding="utf-8-sig")
print("Saved:", final_generated_file)

Saved: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\final_generated_questions.csv

In [86]:
final_df = pd.read_csv(final_generated_file)

print("Total generated questions:", len(final_df))
print("\nColumns:")
print(final_df.columns.tolist())

print("\nQuality status:")
print(final_df["quality_status"].value_counts())

final_df.head()

Total generated questions: 14

Columns:
['class', 'subject', 'question_type', 'source_question', 'generated_question', 'quality_status', 'answer_status']

Quality status:
quality_status
PASS_FORMAT    14
Name: count, dtype: int64

,class,subject,question_type,source_question,generated_question,quality_status,answer_status
0,class9,science,MCQ,(a) Amoeba and Euglena arc unicellular organis...,QUESTION:\nWhich of the following statements i...,PASS_FORMAT,Needs verification
1,class9,social_science,MCQ,Read the information given below and select th...,QUESTION:\nWhich of the following was a symbol...,PASS_FORMAT,Needs verification
2,class9,social_science,MCQ,The river Narmada has its source at:,QUESTION:\nWhat is the primary source of water...,PASS_FORMAT,Needs verification
3,class9,maths,MCQ,Which of the following numbers cannot be repre...,QUESTION:\nWhich of the following numbers cann...,PASS_FORMAT,Needs verification
4,class9,social_science,MCQ,"On the given map of France, A is marked as a p...","QUESTION:\nOn the given map of France, A is ma...",PASS_FORMAT,Needs verification

In [87]:
for i, row in final_df.iterrows():
    print("=" * 80)
    print(f"Question {i+1}")
    print("Subject:", row["subject"])
    print("\nSource:")
    print(row["source_question"])
    print("\nGenerated:")
    print(row["generated_question"])

================================================================================
Question 1
Subject: science

Source:
(a) Amoeba and Euglena arc unicellular organisms. www.vedantu.com 30

Generated:
QUESTION:
Which of the following statements is true about amoebas?

A) They have multiple nuclei and chloroplasts.
B) They are photosynthetic and live in water.
C) They reproduce through binary fission but lack cellular structure.
D) They move using pseudopodia and feed on organic matter.

ANSWER:
D) They move using pseudopodia and feed on organic matter.
================================================================================
Question 2
Subject: social_science

Source:
Read the information given below and select the correct option. Most of men and women in the eighteenth century could not read or write. So, images and symbols were frequently used instead of printed words to communicate important ideas. Which of the following was a symbol of royal power?

Generated:
QUESTION:
Which of the following was a symbol of royal power during the eighteenth century?

A) The Bible
B) The Crown Jewels
C) The Royal Coat of Arms
D) The Flag of Great Britain

ANSWER:
C) The Royal Coat of Arms
================================================================================
Question 3
Subject: social_science

Source:
The river Narmada has its source at:

Generated:
QUESTION:
What is the primary source of water for the river Narmada?

A) Himalayas
B) Aravallis
C) Western Ghats
D) Eastern Ghats

ANSWER:
B) Aravallis
================================================================================
Question 4
Subject: maths

Source:
Which of the following numbers cannot be represented as a terminating decimal?

Generated:
QUESTION:
Which of the following numbers cannot be represented as a terminating decimal?

A) 1/3
B) 2/5
C) 7/8
D) 3/2

ANSWER:
A) 1/3
================================================================================
Question 5
Subject: social_science

Source:
On the given map of France, A is marked as a place where troops entered following the King’s Command. Identify it from the following options. 1 www.vedantu.com 6

Generated:
QUESTION:
On the given map of France, A is marked as a place where troops entered following the King's Command. Identify it from the following options. 3

A) Paris
B) Marseille
C) Strasbourg
D) Bordeaux

ANSWER:
D) Bordeaux
================================================================================
Question 6
Subject: social_science

Source:
Changes in power-sharing require a 1/3rd majority in both houses of Parliament. Options

Generated:
QUESTION:
What is required to change the government in India?

A) More than half of members from one house
B) More than half of members from both houses
C) More than three-fourths of members from one house
D) More than three-fourths of members from both houses

ANSWER:
B) More than half of members from both houses
================================================================================
Question 7
Subject: maths

Source:
The feasible region of a linear programming problem (LPP) is always a

Generated:
QUESTION:
What does the feasible region of a linear programming problem (LPP) represent?

A) Area where all constraints and objective function intersect
B) Region within which solutions to LPP problems exist
C) Set of points that satisfy both inequalities or equations simultaneously
D) Space defined by non-negative coefficients only

ANSWER:
B) Region within which solutions to LPP problems exist
================================================================================
Question 8
Subject: social_science

Source:
Two places A and B have been marked on the given outline map of the world. Identify then and write their correct names on the lines drawn near them

Generated:
QUESTION:
Which two countries are identified in the following outline map?

A) Japan and Russia
B) China and India
C) Brazil and Argentina
D) United States and Canada

ANSWER:
D) United States and Canada
================================================================================
Question 9
Subject: science

Source:
Plasmolysis is the process in which the cell membrane pulls away from the cell wall due to the loss of water from the cell. This happens when the cell is placed in a hypertonic solution, causing water to leave the cell by osmosis. When a plasmolysed cell is placed in water (a hypotonic solution), it absorbs water, and the cell membrane moves back toward the cell wall. This process is called deplasmolysis, and the cell becomes turgid again. OR

Generated:
QUESTION:
Which statement best describes the effect of placing a plasmolysed plant cell in a hypotonic solution?

A) The cell will absorb water and become turgid.
B) The cell will lose water and shrink.
C) The cell will remain unchanged as no water enters or exits.
D) The cell will burst due to excessive water absorption.

ANSWER:
A) The cell will absorb water and become turgid.
================================================================================
Question 10
Subject: social_science

Source:
Which of the following is known as the twin of the Narmada?

Generated:
QUESTION:
Which of the following is known as the twin of the Narmada?

A) Godavari
B) Mahanadi
C) Kaveri
D) Tungabhadra

ANSWER:
D) Tungabhadra
================================================================================
Question 11
Subject: science

Source:
Three students used three different containers

Generated:
QUESTION:
Three students used three different containers to measure water in liters. The first student filled her container to the brim and measured 50 liters. The second student poured half of what she had into a larger container but still managed to fill another smaller container with the remaining amount, which was also 25 liters. How much water did the third student use if her measurement is twice that of the second student?

A) 10 liters
B) 25 liters
C) 50 liters
D) 75 liters

ANSWER:
D) 75 liters
================================================================================
Question 12
Subject: science

Source:
Rutherford’s a-particle scattering experiment showed that: (i) Electrons have a negative charge. (ii) The mass and positive charge of the atom is concentrated in the nucleus. (iii) Neutron exists outside the nucleus. (iv) Most of the space in the atom is empty. Which of the above statements are correct?

Generated:
QUESTION:
Which statement correctly describes the findings of Rutherford's alpha particle scattering experiment?

A) Electrons have a negative charge.
B) The mass and positive charge of the atom are concentrated in the nucleus.
C) Neutrons exist outside the nucleus.
D) Most of the space in the atom is empty.

ANSWER:
B) The mass and positive charge of the atom are concentrated in the nucleus.
================================================================================
Question 13
Subject: maths

Source:
Which of the following gives the middle most observation of the data?

Generated:
QUESTION:
Which of the following gives the middle most observation of the data?

A) Median
B) Mean
C) Mode
D) Range

ANSWER:
A) Median
================================================================================
Question 14
Subject: social_science

Source:
French Revolution topic

Generated:
QUESTION:
Which event is considered to have marked the beginning of the French Revolution?

A) The storming of the Bastille
B) The signing of the Treaty of Versailles
C) The Reign of Terror
D) Napoleon's rise to power

ANSWER:
A) The storming of the Bastille

In [88]:
review_questions = [4, 5, 6, 8, 10, 11, 12, 13]

review_df = final_df.iloc[
    [q - 1 for q in review_questions]
].copy()

review_df[[
    "subject",
    "source_question",
    "generated_question",
    "quality_status"
]]

,subject,source_question,generated_question,quality_status
3,maths,Which of the following numbers cannot be repre...,QUESTION:\nWhich of the following numbers cann...,PASS_FORMAT
4,social_science,"On the given map of France, A is marked as a p...","QUESTION:\nOn the given map of France, A is ma...",PASS_FORMAT
5,social_science,Changes in power-sharing require a 1/3rd major...,QUESTION:\nWhat is required to change the gove...,PASS_FORMAT
7,social_science,Two places A and B have been marked on the giv...,QUESTION:\nWhich two countries are identified ...,PASS_FORMAT
9,social_science,Which of the following is known as the twin of...,QUESTION:\nWhich of the following is known as ...,PASS_FORMAT
10,science,Three students used three different containers,QUESTION:\nThree students used three different...,PASS_FORMAT
11,science,Rutherford’s a-particle scattering experiment ...,QUESTION:\nWhich statement correctly describes...,PASS_FORMAT
12,maths,Which of the following gives the middle most o...,QUESTION:\nWhich of the following gives the mi...,PASS_FORMAT

In [89]:
review_status = {
    0: "Needs Review",
    1: "Needs Review",
    2: "Needs Review",
    3: "Reject",
    4: "Reject",
    5: "Reject",
    6: "Needs Review",
    7: "Reject",
    8: "Good Candidate",
    9: "Reject",
    10: "Reject",
    11: "Reject",
    12: "Reject",
    13: "Needs Review"
}
final_df["review_status"] = final_df.index.map(review_status)
print(final_df["review_status"].value_counts())
final_df[["subject", "review_status", "generated_question"]]

review_status
Reject            8
Needs Review      5
Good Candidate    1
Name: count, dtype: int64

,subject,review_status,generated_question
0,science,Needs Review,QUESTION:\nWhich of the following statements i...
1,social_science,Needs Review,QUESTION:\nWhich of the following was a symbol...
2,social_science,Needs Review,QUESTION:\nWhat is the primary source of water...
3,maths,Reject,QUESTION:\nWhich of the following numbers cann...
4,social_science,Reject,"QUESTION:\nOn the given map of France, A is ma..."
5,social_science,Reject,QUESTION:\nWhat is required to change the gove...
6,maths,Needs Review,QUESTION:\nWhat does the feasible region of a ...
7,social_science,Reject,QUESTION:\nWhich two countries are identified ...
8,science,Good Candidate,QUESTION:\nWhich statement best describes the ...
9,social_science,Reject,QUESTION:\nWhich of the following is known as ...
10,science,Reject,QUESTION:\nThree students used three different...
11,science,Reject,QUESTION:\nWhich statement correctly describes...
12,maths,Reject,QUESTION:\nWhich of the following gives the mi...
13,social_science,Needs Review,QUESTION:\nWhich event is considered to have m...

In [90]:
llm_input_dataset = pd.read_csv(
    processed_folder / "llm_input_dataset.csv"
)
print("Columns in llm_input_dataset:")
print(llm_input_dataset.columns.tolist())

print("\nFirst 5 rows:")
display(llm_input_dataset.head())

Columns in llm_input_dataset:
['question_id', 'class', 'subject', 'session', 'question_type', 'question_text_clean', 'options', 'source_file']

First 5 rows:

,question_id,class,subject,session,question_type,question_text_clean,options,source_file
0,5,class10,computer_application,2023-24,MCQ,The acronym SSH stands for_________________.,A. Safe Shell | B. Software Shell | C. Secure ...,ComputerApplication-SQP -23-24.pdf
1,6,class10,computer_application,2023-24,MCQ,Which of the following is an example of social...,A. wikipedia.org | B. Facebook.com | C. cbse.g...,ComputerApplication-SQP -23-24.pdf
2,7,class10,computer_application,2023-24,MCQ,M in HTML stands for:,A. Modify | B. Management | C. Multiple | D. M...,ComputerApplication-SQP -23-24.pdf
3,8,class10,computer_application,2023-24,MCQ,A _____________ is an online journal or inform...,A. News group | B. Blog | C. WWW | D. e-Groups,ComputerApplication-SQP -23-24.pdf
4,9,class10,computer_application,2023-24,MCQ,Which of the following is not a valid value fo...,A. _blank | B. _self | C. _top | D. _bottom Pa...,ComputerApplication-SQP -23-24.pdf

In [91]:
candidate_df = llm_input_dataset[
    (llm_input_dataset["question_type"] == "MCQ") &
    (llm_input_dataset["question_text_clean"].notna()) &
    (llm_input_dataset["options"].notna()) &
    (llm_input_dataset["question_text_clean"].str.len().between(20, 250))
].copy()

# Remove questions that depend on visual material
visual_words = r"\b(map|figure|diagram|image|picture|outline map|given map)\b"
candidate_df = candidate_df[
    ~candidate_df["question_text_clean"].str.contains(
        visual_words,
        case=False,
        regex=True,
        na=False
    )
]
print("Candidate questions:", len(candidate_df))
display(
    candidate_df[
        ["question_id", "class", "subject",
         "question_text_clean", "options"]
    ].head(20))

Candidate questions: 448

C:\Users\vivek\AppData\Local\Temp\ipykernel_15932\4240940937.py:11: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ~candidate_df["question_text_clean"].str.contains(

,question_id,class,subject,question_text_clean,options
0,5,class10,computer_application,The acronym SSH stands for_________________.,A. Safe Shell | B. Software Shell | C. Secure ...
1,6,class10,computer_application,Which of the following is an example of social...,A. wikipedia.org | B. Facebook.com | C. cbse.g...
2,7,class10,computer_application,M in HTML stands for:,A. Modify | B. Management | C. Multiple | D. M...
3,8,class10,computer_application,A _____________ is an online journal or inform...,A. News group | B. Blog | C. WWW | D. e-Groups
4,9,class10,computer_application,Which of the following is not a valid value fo...,A. _blank | B. _self | C. _top | D. _bottom Pa...
5,10,class10,computer_application,"link, vlink, alink are attributes of__________...",A. <body> | B. <a> | C. <html> | D. <img>
7,12,class10,computer_application,Which of the following tag can be used to draw...,A. <line> | B. <hrule> | C. <hr> | D. <rule>
8,13,class10,computer_application,"In HTML, <dl>, <dd> and <dt> tags are used to ...",A. Description list | B. Definition list | C. ...
26,31,class10,computer_application,It is an era of Internet and we as a netizen s...,"A. Suggest any two netiquettes, which she shou..."
27,36,class10,computer_application,Shreya wants to securely copy files between tw...,A. FTP | B. HTTP | C. SCP | D. Telnet 1
28,37,class10,computer_application,Which of the following is not an e-governance ...,A. www.drdo.nic.in | B. www.passport.gov.in | ...
29,38,class10,computer_application,Which tag besides <B> can be used to make the ...,A. <strong> | B. <dark> | C. <fat> | D. <I> 1
30,39,class10,computer_application,What is the full form of SMTP?,A. Simple Message Transfer Protocol | B. Secur...
31,40,class10,computer_application,Which protocol is used for video conferencing ...,A. Telnet | B. Http | C. VoIP | D. SFTP 1
32,41,class10,computer_application,Select the correct option to fill in the blank...,A. Static Webpages | B. Dynamic Webpages | C. ...
33,42,class10,computer_application,"Aman, a student of Class X, wants to create nu...",A. <UL> | B. <OL> | C. <DL> | D. <list> 1
34,43,class10,computer_application,Making a copy of your webpage on the computer ...,A. Uploading | B. Browsing | C. Downloading | ...
35,44,class10,computer_application,"Himani, a class X student, wants to remotely a...",A. FTP | B. SFTP | C. TCP/IP | D. TELNET 1
53,66,class10,home_science,What could be the possible reason of cross con...,A. Using same chopping boards for both vegetar...
54,67,class10,home_science,Which is the best way to save energy while wor...,A. Improve posture | B. Sleep in between the w...

In [92]:
selected_questions = candidate_df[
    candidate_df["question_id"].isin([5, 6, 7, 8, 12])
].copy()
display(
    selected_questions[
        ["question_id", "class", "subject",
         "question_text_clean", "options"]])

,question_id,class,subject,question_text_clean,options
0,5,class10,computer_application,The acronym SSH stands for_________________.,A. Safe Shell | B. Software Shell | C. Secure ...
1,6,class10,computer_application,Which of the following is an example of social...,A. wikipedia.org | B. Facebook.com | C. cbse.g...
2,7,class10,computer_application,M in HTML stands for:,A. Modify | B. Management | C. Multiple | D. M...
3,8,class10,computer_application,A _____________ is an online journal or inform...,A. News group | B. Blog | C. WWW | D. e-Groups
7,12,class10,computer_application,Which of the following tag can be used to draw...,A. <line> | B. <hrule> | C. <hr> | D. <rule>

In [93]:
print("Classes:")
print(llm_input_dataset["class"].unique())

print("\nSubjects and question counts:")
display(llm_input_dataset.groupby(["class", "subject"]).size().reset_index(name="question_count"))

Classes:
<ArrowStringArray>
['class10', 'class9']
Length: 2, dtype: str

Subjects and question counts:

     class               subject  question_count
0  class10  computer_application              53
1  class10          home_science              90
2  class10                 maths             126
3  class10        social_science             116
4   class9                 maths             466
5   class9               science             463
6   class9        social_science             481

In [94]:
mapped_df=pd.read_csv(r"E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\class10_maths_mapped.csv")

print("Database shape:",mapped_df.shape)
print("\nColumn names:")
print(mapped_df.columns.tolist())
display(mapped_df.head())

Database shape: (126, 10)

Column names:
['question_id', 'class', 'subject', 'session', 'question_type', 'question_text_clean', 'options', 'source_file', 'chapter', 'chapter_confidence']

,question_id,class,subject,session,question_type,question_text_clean,options,source_file,chapter,chapter_confidence
0,162,class10,maths,2023-24,MCQ,If two positive integers a and b are written a...,B) is | (A) xy | (B) xy2 | (C) x3y3 | (D) x2y2 1,MathsStandard-SQP -23-24.pdf,Number Systems,0.362864
1,163,class10,maths,2023-24,MCQ,The given linear polynomial y = f(x) has,(A) 2 zeros | (B) 1 zero and the zero is ‘3’ |...,MathsStandard-SQP -23-24.pdf,Algebra,0.145703
2,164,class10,maths,2023-24,MCQ,The lines representing the given pair of linea...,(A) ௔ଵ ௔ଶ = ௕ଵ ௕ଶ = ௖ଵ ௖ଶ | (B) ௔ଵ ௔ଶ = ௕ଵ ௕ଶ ...,MathsStandard-SQP -23-24.pdf,Algebra,0.492972
3,165,class10,maths,2023-24,MCQ,The nature of roots of the quadratic equation ...,(A) No real roots | (B) 2 equal real roots | (...,MathsStandard-SQP -23-24.pdf,Algebra,0.254558
4,166,class10,maths,2023-24,MCQ,Two APs have the same common difference. The f...,(A) 1 | (B) -7 | (C) 7 | (D) 9 1,MathsStandard-SQP -23-24.pdf,Algebra,0.406763

In [95]:
print("Questions in each chapter:")
print(mapped_df["chapter"].value_counts(dropna=False))

print("\nChapter confidence summary:")
print(mapped_df["chapter_confidence"].describe())

print("\n10 questions with the lowest scores:")
display(
    mapped_df.sort_values("chapter_confidence")[
        [
            "question_id",
            "question_text_clean",
            "chapter",
            "chapter_confidence"
        ]
    ].head(10)
)

Questions in each chapter:
chapter
Algebra                       23
Geometry                      21
Statistics and Probability    20
Not a Question                17
Trigonometry                  15
Number Systems                10
Mensuration                   10
Coordinate Geometry            9
Needs Review                   1
Name: count, dtype: int64

Chapter confidence summary:
count    126.000000
mean       0.233983
std        0.111638
min        0.000000
25%        0.171015
50%        0.233793
75%        0.300326
max        0.492972
Name: chapter_confidence, dtype: float64

10 questions with the lowest scores:

,question_id,question_text_clean,chapter,chapter_confidence
10,172,"Given that sin θ = ௔ ௕, then cos θ is.",Trigonometry,0.0
11,173,(sec A + tan,Not a Question,0.0
29,191,"If 1 + sin2θ = 3sinθ cosθ , then prove that ta...",Trigonometry,0.0
23,185,If tan (A +,Not a Question,0.0
44,207,Take π =22/7 wherever required if not stated.,Not a Question,0.0
94,259,"If 𝑠𝑒𝑐𝛳 + 𝑡𝑎𝑛𝛳 = 𝑥 ,then 𝑠𝑒𝑐𝛳 − 𝑡𝑎𝑛𝛳 will be",Trigonometry,0.0
74,238,"If cosθ + sinθ = 1 , then prove that cosθ - si...",Trigonometry,0.0
68,232,Evaluate: 2𝑠𝑖𝑛 260𝑜 − 𝑡𝑎𝑛230𝑜 𝑠𝑒𝑐2 45𝑜 2,Trigonometry,0.0
117,282,"If 𝑠𝑖𝑛𝛳+ 𝑐𝑜𝑠𝛳 = √3 ,then prove that 𝑡𝑎𝑛𝛳 + 𝑐𝑜𝑡...",Trigonometry,0.0
112,277,(A),Not a Question,0.0

In [96]:
problem_df = mapped_df[
    mapped_df["chapter"].isin(["Not a Question", "Needs Review"])]

display(problem_df[["question_id","question_text_clean","chapter","chapter_confidence"]])

,question_id,question_text_clean,chapter,chapter_confidence
11,173,(sec A + tan,Not a Question,0.000000
18,180,"DIRECTION: In the question number 19 and 20, a...",Not a Question,0.227066
23,185,If tan (A +,Not a Question,0.000000
39,201,"In Section B, Questions no. 21-25 are very sho...",Not a Question,0.111087
40,202,"In Section C, Questions no. 26-31 are short an...",Not a Question,0.111087
41,203,"In Section D, Questions no. 32-35 are long ans...",Not a Question,0.111087
42,204,"In Section E, Questions no. 36-38 are case stu...",Not a Question,0.238091
43,206,Draw neat and clean figures wherever required.,Not a Question,0.123028
44,207,Take π =22/7 wherever required if not stated.,Not a Question,0.000000
45,208,Use of calculators is not allowed. Section A S...,Not a Question,0.246739
48,211,Which of the following statements is not true?,Needs Review,0.269268
84,248,"In Section B, Question numbers 21-25 are very ...",Not a Question,0.300326
85,249,"In Section C, Question numbers 26-31 are short...",Not a Question,0.300326
86,250,"In Section D, Question numbers 32-35 are long ...",Not a Question,0.300326
87,251,"In Section E, Question numbers 36-38 are case ...",Not a Question,0.329819
88,253,Draw neat and clean figures wherever required....,Not a Question,0.123028
89,254,Use of calculators is not allowed. (Section,Not a Question,0.235274
112,277,(A),Not a Question,0.000000

In [97]:
non_question_ids = [
    180, 201, 202, 203, 204, 206, 207,
    208, 248, 249, 250, 251, 253, 254
]

incomplete_ids = [173, 185, 277]
context_ids = [211]

review_df = mapped_df[mapped_df["question_id"].isin(non_question_ids + incomplete_ids + context_ids)].copy()

review_df["review_status"] = "Needs context"

review_df.loc[review_df["question_id"].isin(non_question_ids),"review_status"] = "Instruction - exclude from question bank"

review_df.loc[review_df["question_id"].isin(incomplete_ids),"review_status"] = "Incomplete extraction - check source PDF"

display(review_df[["question_id","question_text_clean","chapter","review_status"]])

,question_id,question_text_clean,chapter,review_status
11,173,(sec A + tan,Not a Question,Incomplete extraction - check source PDF
18,180,"DIRECTION: In the question number 19 and 20, a...",Not a Question,Instruction - exclude from question bank
23,185,If tan (A +,Not a Question,Incomplete extraction - check source PDF
39,201,"In Section B, Questions no. 21-25 are very sho...",Not a Question,Instruction - exclude from question bank
40,202,"In Section C, Questions no. 26-31 are short an...",Not a Question,Instruction - exclude from question bank
41,203,"In Section D, Questions no. 32-35 are long ans...",Not a Question,Instruction - exclude from question bank
42,204,"In Section E, Questions no. 36-38 are case stu...",Not a Question,Instruction - exclude from question bank
43,206,Draw neat and clean figures wherever required.,Not a Question,Instruction - exclude from question bank
44,207,Take π =22/7 wherever required if not stated.,Not a Question,Instruction - exclude from question bank
45,208,Use of calculators is not allowed. Section A S...,Not a Question,Instruction - exclude from question bank
48,211,Which of the following statements is not true?,Needs Review,Needs context
84,248,"In Section B, Question numbers 21-25 are very ...",Not a Question,Instruction - exclude from question bank
85,249,"In Section C, Question numbers 26-31 are short...",Not a Question,Instruction - exclude from question bank
86,250,"In Section D, Question numbers 32-35 are long ...",Not a Question,Instruction - exclude from question bank
87,251,"In Section E, Question numbers 36-38 are case ...",Not a Question,Instruction - exclude from question bank
88,253,Draw neat and clean figures wherever required....,Not a Question,Instruction - exclude from question bank
89,254,Use of calculators is not allowed. (Section,Not a Question,Instruction - exclude from question bank
112,277,(A),Not a Question,Incomplete extraction - check source PDF

In [98]:
from pathlib import Path
mapping_df = mapped_df.copy()

# Add the missing topic column
mapping_df["topic"] = ""

# Give each record a review status
mapping_df["review_status"] = "Verify chapter and map topic"

instruction_ids = [180, 201, 202, 203, 204, 206, 207,208, 248, 249, 250, 251, 253, 254]

incomplete_ids = [173, 185, 277]

mapping_df.loc[mapping_df["question_id"].isin(instruction_ids),"review_status"] = "Exclude: exam instruction"

mapping_df.loc[mapping_df["question_id"].isin(incomplete_ids),"review_status"] = "Recover from source PDF"

mapping_df.loc[mapping_df["question_id"] == 211,"review_status"] = "Check question and options"

output_path = Path("data/processed/class10_maths_mapping_review.csv")

output_path.parent.mkdir(parents=True, exist_ok=True)

mapping_df.to_csv(output_path, index=False)

print("Saved:", output_path)
print("\nReview summary:")
print(mapping_df["review_status"].value_counts())

Saved: data\processed\class10_maths_mapping_review.csv

Review summary:
review_status
Verify chapter and map topic    108
Exclude: exam instruction        14
Recover from source PDF           3
Check question and options        1
Name: count, dtype: int64

In [99]:
import re

usable_df = mapping_df[mapping_df["review_status"] == "Verify chapter and map topic"].copy()

topic_rules = [
    (r"hcf|lcm|euclid|prime factor|irrational number", "Real Numbers"),
    (r"polynomial|zeros of", "Polynomials"),
    (r"pair of linear equations|linear equations|consistent|inconsistent", "Pair of Linear Equations"),
    (r"quadratic equation|discriminant|nature of roots", "Quadratic Equations"),
    (r"arithmetic progression|common difference|nth term", "Arithmetic Progressions"),
    (r"angle of elevation|angle of depression", "Heights and Distances"),
    (r"coordinate|distance formula|section formula|midpoint", "Coordinate Geometry"),
    (r"triangle|pythagoras|similar triangles", "Triangles"),
    (r"sector|segment|circumference|arc length", "Areas Related to Circles"),
    (r"cylinder|cone|sphere|hemisphere|frustum|volume|surface area", "Surface Areas and Volumes"),
    (r"probability|dice|coin|playing cards", "Probability"),
    (r"\bmean\b|\bmedian\b|\bmode\b|frequency distribution", "Statistics"),
    (r"\bsin\b|\bcos\b|\btan\b|\bsec\b|\bcosec\b|\bcot\b|trigonometric", "Trigonometry"),
    (r"\btangent\b|\bchord\b", "Circles"),]

def suggest_topic(question):
    text = str(question).lower()
    for pattern, topic in topic_rules:
        if re.search(pattern, text):
            return topic
    return "Needs manual review"

usable_df["topic_candidate"] = usable_df[
    "question_text_clean"
].apply(suggest_topic)

usable_df["topic_status"] = usable_df["topic_candidate"].apply(lambda x: "Review required" if x == "Needs manual review"else "Verify candidate")

output_path = Path("data/processed/class10_maths_topic_candidates.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)
usable_df.to_csv(output_path, index=False)

print("Saved:", output_path)
print("\nTopic candidates:")
print(usable_df["topic_candidate"].value_counts())

Saved: data\processed\class10_maths_topic_candidates.csv

Topic candidates:
topic_candidate
Needs manual review          38
Probability                   9
Real Numbers                  8
Polynomials                   7
Circles                       7
Triangles                     6
Statistics                    6
Arithmetic Progressions       5
Surface Areas and Volumes     5
Areas Related to Circles      4
Pair of Linear Equations      3
Quadratic Equations           3
Coordinate Geometry           3
Heights and Distances         3
Trigonometry                  1
Name: count, dtype: int64

In [100]:
display(
    usable_df[
        usable_df["topic_candidate"] == "Needs manual review"
    ][
        ["question_id", "question_text_clean", "chapter"]
    ].to_string(index=False)
)

' question_id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   question_text_clean                    chapter\n         168                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            A point (x,y) is at a distance of 5 units from the origin. How many such points lie in the third quadrant?        Coordinate Geometry\n         169                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 In 𝛥 ABC, DE ‖ AB. If AB = a, DE = x, BE = b and EC =                   Geometry\n         171                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       A quadrilateral PQRS is drawn to circumscribe a circle. If PQ = 12 cm, QR = 15 cm and RS = 14 cm, then find the length of SP is                   Geometry\n         174                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               If a pole 6 m high casts a shadow 2 √3m long on the ground, then the Sun’s elevation is               Trigonometry\n         175                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     If the perimeter and the area of a circle are numerically equal, then the radius of the circle is                Mensuration\n         176                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           It is proposed to build a new circular park equal in area to the sum of areas of two circular parks of diameters 16 m and 12 m in a locality. The radius of the new park is                Mensuration\n         179                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           The upper limit of the modal class of the given distribution is: Height [in cm] Below 140 Below 145 Below 150 Below 155 Below 160 Below 165 Number of girls 4 11 29 40 46 51 1 Page 4 of 10 Statistics and Probability\n         183                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ABCD is a parallelogram. Point P divides AB in the ratio 2:3 and point Q divides DC in the ratio 4:1. Prove that OC is half of OA. 2                   Geometry\n         187                                                                                                                                                                                                                                                                                                  National Art convention got registrations from students from all parts of the country, of which 60 are interested in music, 84 are interested in dance and 108 students are interested 3 A B C D P Q O Page 6 of 10 in handicrafts. For optimum cultural exchange, organisers wish to keep them in minimum number of groups such that each group consists of students interested in the same artform and the number of students in each group is the same. Find the number of students in each group. Find the number of groups in each art form. How many rooms are required if each group will be allotted a room?             Number Systems\n         189                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           The sum of a two digit number and the number obtained by reversing the digits is 66. If the digits of the number differ by 2, find the number. How many such numbers are there? 3 [or] Solve : - ଶ √௫ + ଷ √௬ = 2 ; ସ √௫ - ଽ √௬ = -1, x, y>o                    Algebra\n         191                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         If 1 + sin2θ = 3sinθ cosθ , then prove that tanθ = 1 or ଵ ଶ 3               Trigonometry\n         193                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          A motor boat whose speed is 18 km/h in still water takes 1 hour more to go 24 km upstream than to return downstream to the same spot. Find the speed of stream. 5 [or] Two water taps together can fill a tank in 9 ଷ଼ hours. The tap of larger diameter takes 10 hours less than the smaller one to fill the tank separately. Find the time in which each tap can separately fill the tank.                    Algebra\n         194                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    (a) State and prove Basic Proportionality theorem.                   Geometry\n         198 Manpreet Kaur is the national record holder for women in the shot-put discipline. Her throw of 18.86m at the Asian Grand Prix in 2017 is the maximum distance for an Indian female athlete. Keeping her as a role model, Sanjitha is determined to earn gold in Olympics one day. Initially her throw reached 7.56m only. Being an athlete in school, she regularly practiced both in the mornings and in the evenings and was able to improve the distance by 9cm every week. During the special camp for 15 days, she started with 40 throws and every day kept increasing the number of throws by 12 to achieve this remarkable progress. (i) How many throws Sanjitha practiced on 11th day of the camp? 1 (ii) What would be Sanjitha’s throw distance at the end of 6 weeks? (or) When will she be able to achieve a throw of 11.16 m? 2 (iii) How many throws did she do during the entire camp of 15 days ? 1 Statistics and Probability\n         214                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If tan𝜃 = 5 2 then 4 𝑠𝑖𝑛𝜃 + 𝑐𝑜𝑠𝜃 4 𝑠𝑖𝑛𝜃 − 𝑐𝑜𝑠𝜃 is equal to               Trigonometry\n         218                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   O is the point of intersection of two chords AB and CD of a circle. If ∠𝐵𝑂𝐶= 80𝑂 and OA = OD then 𝛥𝑂𝐷𝐴 𝑎𝑛𝑑 𝛥𝑂𝐵𝐶 are                   Geometry\n         220                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             If 𝜃 = 30𝑜 then the value of 3tan𝜃 is A)1               Trigonometry\n         223                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              The point on the x- axis nearest to the point (-4,-5) is        Coordinate Geometry\n         224                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Which of the following gives the middle most observation of the data? Statistics and Probability\n         232                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Evaluate: 2𝑠𝑖𝑛 260𝑜 − 𝑡𝑎𝑛230𝑜 𝑠𝑒𝑐2 45𝑜 2               Trigonometry\n         233                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

In [101]:
topic_map = {
    168: "Distance and quadrants",
    169: "Basic Proportionality Theorem",
    171: "Tangents to a circle",
    174: "Heights and Distances",
    175: "Area and circumference of a circle",
    176: "Areas of circles",
    179: "Mode of grouped data",
    183: "Parallelogram properties",
    187: "HCF applications",
    189: "Pair of linear equations",
    191: "Trigonometric identities",
    193: "Quadratic equations in word problems",
    194: "Basic Proportionality Theorem",
    198: "Arithmetic Progressions: nth term and sum",
    214: "Trigonometric ratios and identities",
    218: "Intersecting chords and triangle relationships",
    220: "Trigonometric ratios: tan 30 degrees",
    223: "Distance from a point to the x-axis",
    224: "Median of data",
    232: "Trigonometric ratios and standard angles",
    233: "Distance formula",
    236: "Quadratic equations using reciprocals",
    238: "Trigonometric identities",
    239: "Area of a sector",
    242: "Tangents from an external point",
    256: "Distance from a point to the y-axis",
    257: "Conditions for parallel lines",
    258: "Tangents in a circumscribed quadrilateral",
    259: "Trigonometric identities",
    263: "Trigonometric ratios and equations",
    268: "Similarity of triangles and perimeter",
    270: "Identifying figures using coordinates",
    274: "Trigonometric identities: assertion and reason",
    275: "Trigonometric ratios and angle relationships",
    280: "HCF applications",
    282: "Trigonometric identities",
    284: "Probability: consecutive heads",
    286: "Quadratic equations: speed and time",
}

# Assign topic candidates to the 38 questions
usable_df["topic_candidate"] = (
    usable_df["question_id"]
    .map(topic_map)
    .fillna(usable_df["topic_candidate"])
)

usable_df["topic_status"] = "Topic candidate - verify"

# These questions need extra checking due to incomplete text,
# OCR issues, diagrams, or multiple questions in one record.
check_ids = [183, 189, 193, 218, 263, 270, 274, 282, 284]

usable_df.loc[
    usable_df["question_id"].isin(check_ids),
    "topic_status"
] = "Check source PDF/context"

output_path = Path(
    "data/processed/class10_maths_topic_candidates_reviewed.csv"
)
output_path.parent.mkdir(parents=True, exist_ok=True)
usable_df.to_csv(output_path, index=False)

print("Saved:", output_path)
print("Total records:", len(usable_df))
print("\nTopic status:")
print(usable_df["topic_status"].value_counts())
print("\nQuestions still needing topic assignment:")
print(
    usable_df.loc[
        usable_df["topic_candidate"] == "Needs manual review",
        ["question_id", "question_text_clean"]
    ]
)

Saved: data\processed\class10_maths_topic_candidates_reviewed.csv
Total records: 108

Topic status:
topic_status
Topic candidate - verify    99
Check source PDF/context     9
Name: count, dtype: int64

Questions still needing topic assignment:
Empty DataFrame
Columns: [question_id, question_text_clean]
Index: []

In [102]:
# Combine topic candidates with the original 126-question dataset
topic_lookup = usable_df.set_index("question_id")

mapping_df["topic"] = mapping_df["question_id"].map(
    topic_lookup["topic_candidate"]
)

mapping_df["topic_status"] = mapping_df["question_id"].map(
    topic_lookup["topic_status"]
)

mapping_df.loc[
    mapping_df["review_status"] == "Exclude: exam instruction",
    "topic_status"
] = "Not applicable - instruction"

mapping_df.loc[
    mapping_df["review_status"] == "Recover from source PDF",
    "topic_status"
] = "Blocked - incomplete text"

mapping_df.loc[
    mapping_df["review_status"] == "Check question and options",
    "topic_status"
] = "Blocked - needs context"

output_path = Path(
    "data/processed/class10_maths_mapping_progress.csv"
)

mapping_df.to_csv(output_path, index=False)

print("Saved:", output_path)
print("\nReview status:")
print(mapping_df["topic_status"].value_counts(dropna=False))

Saved: data\processed\class10_maths_mapping_progress.csv

Review status:
topic_status
Topic candidate - verify        99
Not applicable - instruction    14
Check source PDF/context         9
Blocked - incomplete text        3
Blocked - needs context          1
Name: count, dtype: int64

In [103]:
def get_chapter(topic):
    if pd.isna(topic) or not str(topic).strip():
        return ""

    t = str(topic).lower()

    if "parallelogram properties" in t:
        return "Needs manual review"
    if "intersecting chords" in t:
        return "Needs manual review"

    if "heights and distances" in t:
        return "Heights and Distances"
    if "surface areas and volumes" in t:
        return "Surface Areas and Volumes"
    if any(x in t for x in ["area of a sector", "areas of circles",
                             "areas related to circles",
                             "area and circumference of a circle"]):
        return "Areas Related to Circles"
    if "probability" in t:
        return "Probability"
    if any(x in t for x in ["statistics", "median of data",
                             "mode of grouped data"]):
        return "Statistics"
    if any(x in t for x in ["coordinate", "distance and quadrants",
                             "distance formula", "distance from a point"]):
        return "Coordinate Geometry"
    if any(x in t for x in ["hcf applications", "real numbers"]):
        return "Real Numbers"
    if "polynomial" in t:
        return "Polynomials"
    if "linear equation" in t or "conditions for parallel lines" in t:
        return "Pair of Linear Equations in Two Variables"
    if "quadratic" in t:
        return "Quadratic Equations"
    if "arithmetic progression" in t:
        return "Arithmetic Progressions"
    if any(x in t for x in ["basic proportionality", "similarity of triangles"]):
        return "Triangles"
    if any(x in t for x in ["tangent", "circle", "chord"]):
        return "Circles"
    if "trigonometric" in t or "trigonometry" in t:
        return "Introduction to Trigonometry"

    return "Needs manual review"


# Preserve the existing chapter labels as syllabus units
final_mapping = mapping_df.rename(
    columns={"chapter": "unit"}
).copy()

# Generate chapter candidates from the topic labels
final_mapping["chapter_candidate"] = (
    final_mapping["topic"].apply(get_chapter)
)

output_path = Path(
    "data/processed/class10_maths_unit_chapter_candidates.csv"
)
output_path.parent.mkdir(parents=True, exist_ok=True)
final_mapping.to_csv(output_path, index=False)

print("Saved:", output_path)
print("\nChapter candidates:")
print(final_mapping["chapter_candidate"].value_counts())

Saved: data\processed\class10_maths_unit_chapter_candidates.csv

Chapter candidates:
chapter_candidate
                                             18
Introduction to Trigonometry                 11
Real Numbers                                 10
Circles                                      10
Probability                                  10
Coordinate Geometry                           8
Statistics                                    8
Needs manual review                           8
Polynomials                                   7
Areas Related to Circles                      7
Quadratic Equations                           6
Arithmetic Progressions                       6
Pair of Linear Equations in Two Variables     5
Surface Areas and Volumes                     5
Heights and Distances                         4
Triangles                                     3
Name: count, dtype: int64

In [104]:
# Recognize "Triangles" as a chapter
mask = (
    final_mapping["topic"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("triangles"))

final_mapping.loc[mask, "chapter_candidate"] = "Triangles"

# Keep genuinely ambiguous cases flagged
output_path = Path(
    "data/processed/class10_maths_unit_chapter_candidates.csv"
)
final_mapping.to_csv(output_path, index=False)

print("Updated file:", output_path)
print("\nChapter candidate counts:")
print(final_mapping["chapter_candidate"].value_counts())

print("\nRecords still needing manual review:")
display(
    final_mapping.loc[
        final_mapping["chapter_candidate"] == "Needs manual review",
        ["question_id", "question_text_clean", "topic"]])

Updated file: data\processed\class10_maths_unit_chapter_candidates.csv

Chapter candidate counts:
chapter_candidate
                                             18
Introduction to Trigonometry                 11
Real Numbers                                 10
Circles                                      10
Probability                                  10
Triangles                                     9
Coordinate Geometry                           8
Statistics                                    8
Polynomials                                   7
Areas Related to Circles                      7
Quadratic Equations                           6
Arithmetic Progressions                       6
Pair of Linear Equations in Two Variables     5
Surface Areas and Volumes                     5
Heights and Distances                         4
Needs manual review                           2
Name: count, dtype: int64

Records still needing manual review:

,question_id,question_text_clean,topic
21,183,ABCD is a parallelogram. Point P divides AB in...,Parallelogram properties
55,218,O is the point of intersection of two chords A...,Intersecting chords and triangle relationships

In [105]:
final_mapping.loc[final_mapping["question_id"] == 218,"chapter_candidate"] = "Circles"
final_mapping.to_csv("data/processed/class10_maths_unit_chapter_candidates.csv",index=False)
print("Updated and saved successfully!")

Updated and saved successfully!

In [106]:
display(final_mapping.loc[final_mapping["question_id"] == 183,
        [  "question_id",
            "source_file",
            "session",
            "question_text_clean",
            "unit",
            "topic",
            "chapter_candidate"]])

,question_id,source_file,session,question_text_clean,unit,topic,chapter_candidate
21,183,MathsStandard-SQP -23-24.pdf,2023-24,ABCD is a parallelogram. Point P divides AB in...,Geometry,Parallelogram properties,Needs manual review

In [107]:
mask = final_mapping["question_id"] == 183
final_mapping.loc[mask, "topic"] = "Similarity of triangles"
final_mapping.loc[mask, "chapter_candidate"] = "Triangles"
final_mapping.loc[mask, "topic_status"] = "Candidate updated; verify"
final_mapping.to_csv(
    "data/processed/class10_maths_unit_chapter_candidates.csv",
    index=False)
display(final_mapping.loc[mask,["question_id", "unit", "topic", "chapter_candidate"]])

    question_id      unit                    topic chapter_candidate
21          183  Geometry  Similarity of triangles         Triangles

In [108]:
pd.set_option("display.max_colwidth", None)
review_batch = final_mapping.loc[
    final_mapping["topic_status"] == "Topic candidate - verify",
    [
        "question_id",
        "question_text_clean",
        "unit",
        "topic",
        "chapter_candidate"]].sort_values("question_id").head(10)

display(review_batch)

,question_id,question_text_clean,unit,topic,chapter_candidate
0,162,"If two positive integers a and b are written as a = x3y2 and b = xy3, where x, y are prime numbers, then the result obtained by dividing the product of the positive integers by the LCM (a,",Number Systems,Real Numbers,Real Numbers
1,163,The given linear polynomial y = f(x) has,Algebra,Polynomials,Polynomials
2,164,The lines representing the given pair of linear equations are non-intersecting. Which of the following statements is true?,Algebra,Pair of Linear Equations,Pair of Linear Equations in Two Variables
3,165,The nature of roots of the quadratic equation 9x2 – 6x – 2 = 0 is:,Algebra,Quadratic Equations,Quadratic Equations
4,166,Two APs have the same common difference. The first term of one of these is –1 and that of the other is – 8. The difference between their 4th terms is,Algebra,Arithmetic Progressions,Arithmetic Progressions
5,167,"What is the ratio in which the line segment joining (2,-3) and (5, 6) is divided by x-axis?",Coordinate Geometry,Areas Related to Circles,Areas Related to Circles
6,168,"A point (x,y) is at a distance of 5 units from the origin. How many such points lie in the third quadrant?",Coordinate Geometry,Distance and quadrants,Coordinate Geometry
7,169,"In 𝛥 ABC, DE ‖ AB. If AB = a, DE = x, BE = b and EC =",Geometry,Basic Proportionality Theorem,Triangles
8,170,"If O is centre of a circle and Chord PQ makes an angle 50° with the tangent PR at the point of contact P, then the angle subtended by the chord at the centre is",Geometry,Circles,Circles
9,171,"A quadrilateral PQRS is drawn to circumscribe a circle. If PQ = 12 cm, QR = 15 cm and RS = 14 cm, then find the length of SP is",Geometry,Tangents to a circle,Circles

In [109]:
mask = final_mapping["question_id"] == 167
final_mapping.loc[mask, "topic"] = ("Section Formula")
final_mapping.loc[mask, "chapter_candidate"] = ("Coordinate Geometry")
final_mapping.loc[mask, "topic_status"] = ("Corrected candidate - verify")
final_mapping.to_csv("data/processed/class10_maths_unit_chapter_candidates.csv",index=False)
display(final_mapping.loc[mask,
        [  "question_id",
            "unit",
            "topic",
            "chapter_candidate"]])

   question_id                 unit            topic    chapter_candidate
5          167  Coordinate Geometry  Section Formula  Coordinate Geometry

In [110]:
next_batch = final_mapping[
    (final_mapping["question_id"] > 171) &
    (final_mapping["topic_status"] == "Topic candidate - verify")
][
    [  "question_id",
        "question_text_clean",
        "unit",
        "topic",
        "chapter_candidate"]].sort_values("question_id").head(10)

display(next_batch)

,question_id,question_text_clean,unit,topic,chapter_candidate
10,172,"Given that sin θ = ௔ ௕, then cos θ is.",Trigonometry,Trigonometry,Introduction to Trigonometry
12,174,"If a pole 6 m high casts a shadow 2 √3m long on the ground, then the Sun’s elevation is",Trigonometry,Heights and Distances,Heights and Distances
13,175,"If the perimeter and the area of a circle are numerically equal, then the radius of the circle is",Mensuration,Area and circumference of a circle,Areas Related to Circles
14,176,It is proposed to build a new circular park equal in area to the sum of areas of two circular parks of diameters 16 m and 12 m in a locality. The radius of the new park is,Mensuration,Areas of circles,Areas Related to Circles
15,177,There is a square board of side ‘2a’ units circumscribing a red circle. Jayadev is asked to keep a dot on the above said board. The probability that he keeps the dot on the shaded region is.,Statistics and Probability,Probability,Probability
16,178,2 cards of hearts and 4 cards of spades are missing from a pack of 52 cards. A card is drawn at random from the remaining pack. What is the probability of getting a black card?,Statistics and Probability,Probability,Probability
17,179,The upper limit of the modal class of the given distribution is: Height [in cm] Below 140 Below 145 Below 150 Below 155 Below 160 Below 165 Number of girls 4 11 29 40 46 51 1 Page 4 of 10,Statistics and Probability,Mode of grouped data,Statistics
19,181,"Statement A (Assertion): -5, ି ହ ଶ , 0, ହ ଶ , …. is in Arithmetic Progression. Statement R (Reason) : The terms of an Arithmetic Progression cannot have both positive and negative rational numbers.",Algebra,Arithmetic Progressions,Arithmetic Progressions
20,182,Prove that √2 is an irrational number. 2 Page 5 of 10,Number Systems,Real Numbers,Real Numbers
22,184,"From an external point P, two tangents, PA and PB are drawn to a circle with centre O. At a point E on the circle, a tangent is drawn to intersect PA and PB at C and D, respectively. If PA = 10 cm, find the perimeter of ∆PCD. 2",Geometry,Circles,Circles

In [111]:
# Question 172: make the topic more specific; verify OCR
final_mapping.loc[
    final_mapping["question_id"] == 172,
    ["topic", "topic_status"]] = ["Trigonometric ratios", "Check source PDF - OCR issue"]

# Question 174: use the official chapter name
final_mapping.loc[
    final_mapping["question_id"] == 174,
    ["topic", "chapter_candidate", "topic_status"]] = [
    "Heights and Distances",
    "Some Applications of Trigonometry",
    "Candidate corrected - verify"]

# Question 177: diagram is needed to verify the probability setup
final_mapping.loc[final_mapping["question_id"] == 177,
    "topic_status"] = "Check original diagram"

# Question 184: specify the topic
final_mapping.loc[final_mapping["question_id"] == 184,"topic"] = "Tangents to a circle"
final_mapping.loc[final_mapping["question_id"] == 184,"topic_status"] = "Candidate refined - verify"
final_mapping.to_csv("data/processed/class10_maths_unit_chapter_candidates.csv",index=False)

print("Corrections saved successfully!")

Corrections saved successfully!

In [112]:
next_batch = final_mapping[
    (final_mapping["question_id"] > 184) &
    (final_mapping["topic"].notna()) &
    (final_mapping["topic"].astype(str).str.strip() != "") &
    (~final_mapping["topic_status"].isin([
        "Not applicable - instruction",
        "Blocked - incomplete text",
        "Blocked - needs context",
        "Check source PDF/context",
        "Check original diagram"]))
][[     "question_id",
        "question_text_clean",
        "unit",
        "topic",
        "chapter_candidate"]].sort_values("question_id").head(10)

display(next_batch)

,question_id,question_text_clean,unit,topic,chapter_candidate
24,186,"With vertices A, B and C of ΔABC as centres, arcs are drawn with radii 14 cm and the three portions of the triangle so obtained are removed. Find the total area removed from the triangle. 2 [or] Find the area of the unshaded region shown in the given figure. SECTION C Section C consists of 6 questions of 3 marks each",Geometry,Triangles,Triangles
25,187,"National Art convention got registrations from students from all parts of the country, of which 60 are interested in music, 84 are interested in dance and 108 students are interested 3 A B C D P Q O Page 6 of 10 in handicrafts. For optimum cultural exchange, organisers wish to keep them in minimum number of groups such that each group consists of students interested in the same artform and the number of students in each group is the same. Find the number of students in each group. Find the number of groups in each art form. How many rooms are required if each group will be allotted a room?",Number Systems,HCF applications,Real Numbers
26,188,"If 𝛼, β are zeroes of quadratic polynomial 5x2 + 5x + 1, find the value of",Algebra,Polynomials,Polynomials
28,190,"PA and PB are tangents drawn to a circle of centre O from an external point P. Chord AB makes an angle of 30° with the radius at the point of contact. If length of the chord is 6 cm, find the length of the tangent PA and the length of the radius OA. 3 [or] Two tangents TP and TQ are drawn to a circle with centre O from an external point T. Prove that ∠PTQ = 2 ∠ OPQ.",Geometry,Circles,Circles
29,191,"If 1 + sin2θ = 3sinθ cosθ , then prove that tanθ = 1 or ଵ ଶ 3",Trigonometry,Trigonometric identities,Introduction to Trigonometry
30,192,"The length of 40 leaves of a plant are measured correct to nearest millimetre, and the data obtained is represented in the following table. Length [in mm] Number of leaves 118 – 126 3 127 – 135 5 136 – 144 9 3 Page 7 of 10 145 – 153 12 154 – 162 5 163 – 171 4 172 – 180 2 Find the mean length of the leaves. SECTION D Section D consists of 4 questions of 5 marks each",Statistics and Probability,Statistics,Statistics
32,194,(a) State and prove Basic Proportionality theorem.,Geometry,Basic Proportionality Theorem,Triangles
33,195,"Water is flowing at the rate of 15 km/h through a pipe of diameter 14 cm into a cuboidal pond which is 50 m long and 44 m wide. In what time will the level of water in pond rise by 21 cm? What should be the speed of water if the rise in water level is to be attained in 1 hour? 5 [or] A tent is in the shape of a cylinder surmounted by a conical top. If the height and radius of the cylindrical part are 3 m and 14 m respectively, and the total height of the tent is 13.5 m, find the area of the canvas required for making the tent, keeping a provision of 26 m2 of canvas for stitching and wastage. Also, find the cost of the canvas to be purchased at the rate of ₹ 500 per m2. Page 8 of 10",Mensuration,Surface Areas and Volumes,Surface Areas and Volumes
34,196,"The median of the following data is 50. Find the values of ‘p’ and ‘q’, if the sum of all frequencies is",Statistics and Probability,Statistics,Statistics
35,197,Also find the mode of the data. Marks obtained Number of students 20 – 30 p 30 – 40 15 40 – 50 25 50 – 60 20 60 – 70 q 70 – 80 8 80 - 90 10 5 SECTION E,Statistics and Probability,Statistics,Statistics

In [113]:
# Question 186: correct the mapping
mask = final_mapping["question_id"] == 186

final_mapping.loc[mask, "unit"] = "Mensuration"
final_mapping.loc[mask, "topic"] = "Areas of sectors"
final_mapping.loc[mask, "chapter_candidate"] = "Areas Related to Circles"
final_mapping.loc[mask, "topic_status"] = "Corrected candidate - verify"

# Question 190: make the topic more specific
mask = final_mapping["question_id"] == 190

final_mapping.loc[mask, "topic"] = "Tangents to a circle"
final_mapping.loc[mask, "topic_status"] = "Candidate refined - verify"

# Flag Question 195 for splitting its alternatives
final_mapping.loc[
    final_mapping["question_id"] == 195,
    "topic_status"
] = "Check source PDF - split OR alternatives"

# Flag Questions 196 and 197 for checking
final_mapping.loc[
    final_mapping["question_id"].isin([196, 197]),
    "topic_status"
] = "Check source PDF - possible split question"

# Save the updated mapping file
final_mapping.to_csv(
    "data/processed/class10_maths_unit_chapter_candidates.csv",
    index=False
)

print("Corrections saved successfully!")

Corrections saved successfully!

In [114]:
next_batch = final_mapping[
    (final_mapping["question_id"] > 197) &
    (final_mapping["topic"].notna()) &
    (final_mapping["topic"].astype(str).str.strip() != "") &
    (~final_mapping["topic_status"].isin([
        "Not applicable - instruction",
        "Blocked - incomplete text",
        "Blocked - needs context",
        "Check source PDF/context",
        "Check original diagram"
    ]))
][
    [
        "question_id",
        "question_text_clean",
        "unit",
        "topic",
        "chapter_candidate"
    ]
].sort_values("question_id").head(10)

display(next_batch)

,question_id,question_text_clean,unit,topic,chapter_candidate
36,198,"Manpreet Kaur is the national record holder for women in the shot-put discipline. Her throw of 18.86m at the Asian Grand Prix in 2017 is the maximum distance for an Indian female athlete. Keeping her as a role model, Sanjitha is determined to earn gold in Olympics one day. Initially her throw reached 7.56m only. Being an athlete in school, she regularly practiced both in the mornings and in the evenings and was able to improve the distance by 9cm every week. During the special camp for 15 days, she started with 40 throws and every day kept increasing the number of throws by 12 to achieve this remarkable progress. (i) How many throws Sanjitha practiced on 11th day of the camp? 1 (ii) What would be Sanjitha’s throw distance at the end of 6 weeks? (or) When will she be able to achieve a throw of 11.16 m? 2 (iii) How many throws did she do during the entire camp of 15 days ? 1",Statistics and Probability,Arithmetic Progressions: nth term and sum,Arithmetic Progressions
37,199,"Tharunya was thrilled to know that the football tournament is fixed with a monthly timeframe from 20th July to 20th August 2023 and for the first time in the FIFA Women’s World Cup’s history, two nations host in 10 venues. Her father felt that the game can be better understood if the position of players is represented as points on a coordinate plane. Page 9 of 10 (i) At an instance, the midfielders and forward formed a parallelogram. Find the position of the central midfielder",Coordinate Geometry,Coordinate Geometry,Coordinate Geometry
38,200,"One evening, Kaushik was in a park. Children were playing cricket. Birds were singing on a nearby tree of height 80m. He observed a bird on the tree at an angle of elevation of 45°. When a sixer was hit, a ball flew through the tree frightening the bird to fly away. In 2 seconds, he observed the bird flying at the same height at an angle of elevation of 30° and the ball flying towards him at the same height at an angle of elevation of 60°. Page 10 of 10 (i) At what distance from the foot of the tree was he observing the bird sitting on the tree? 1 (ii) How far did the bird fly in the mentioned time? (or) After hitting the tree, how far did the ball travel in the sky when Kaushik saw the ball? 2 (iii) What is the speed of the bird in m/min if it had flown 20(√3 + 1) m? 1",Trigonometry,Heights and Distances,Heights and Distances
46,209,"The graph of a quadratic polynomial p(x) passes through the points (-6,0), (0, -30), (4,-20) and (6,0). The zeroes of the polynomial are",Algebra,Polynomials,Polynomials
47,210,"The value of k for which the system of equations 3x-ky= 7 and 6x+ 10y =3 is inconsistent, is",Algebra,Pair of Linear Equations,Pair of Linear Equations in Two Variables
49,212,If nth term of an A.P. is 7n-4 then the common difference of the A.P. is,Algebra,Arithmetic Progressions,Arithmetic Progressions
50,213,The radius of the base of a right circular cone and the radius of a sphere are each 5 cm in length. If the volume of the cone is equal to the volume of the sphere then the height of the cone is,Mensuration,Surface Areas and Volumes,Surface Areas and Volumes
51,214,If tan𝜃 = 5 2 then 4 𝑠𝑖𝑛𝜃 + 𝑐𝑜𝑠𝜃 4 𝑠𝑖𝑛𝜃 − 𝑐𝑜𝑠𝜃 is equal to,Trigonometry,Trigonometric ratios and identities,Introduction to Trigonometry
52,215,"In the given figure, a tangent has been drawn at a point P on the circle centred at O. If ∠ TPQ= 110𝑂 then ∠POQ is equal to",Geometry,Circles,Circles
53,216,A quadratic polynomial having zeroes - √5 2 and √5 2 is,Algebra,Polynomials,Polynomials

In [115]:
# Question 200: use the chapter name
final_mapping.loc[
    final_mapping["question_id"] == 200,
    "chapter_candidate"
] = "Some Applications of Trigonometry"

final_mapping.loc[
    final_mapping["question_id"] == 200,
    "topic_status"
] = "Candidate corrected - verify"

# Question 199: incomplete context
final_mapping.loc[
    final_mapping["question_id"] == 199,
    "topic_status"
] = "Check source PDF and figure"

# Question 214: check mathematical OCR
final_mapping.loc[
    final_mapping["question_id"] == 214,
    "topic_status"
] = "Check source PDF - mathematical notation"

# Question 215: specify the likely topic, pending figure verification
final_mapping.loc[
    final_mapping["question_id"] == 215,
    "topic"
] = "Tangent-chord angle relationship"

final_mapping.loc[
    final_mapping["question_id"] == 215,
    "topic_status"
] = "Check original figure"

final_mapping.to_csv(
    "data/processed/class10_maths_unit_chapter_candidates.csv",
    index=False
)

print("Updates saved successfully!")

Updates saved successfully!

In [116]:
skip_statuses = [
    "Not applicable - instruction",
    "Blocked - incomplete text",
    "Blocked - needs context",
    "Check source PDF/context",
    "Check original diagram",
    "Check source PDF - split OR alternatives",
    "Check source PDF - possible split question",
    "Check source PDF and figure",
    "Check source PDF - mathematical notation",
    "Check original figure",
    "Check source PDF - OCR issue",]

next_batch = final_mapping[
    (final_mapping["question_id"] > 216)
    & final_mapping["topic"].notna()
    & (final_mapping["topic"].astype(str).str.strip() != "")
    & (~final_mapping["topic_status"].fillna("").isin(skip_statuses))
][[  "question_id",
     "question_text_clean",
     "unit",
     "topic",
     "chapter_candidate",]].sort_values("question_id").head(10)

display(next_batch)

,question_id,question_text_clean,unit,topic,chapter_candidate
54,217,Consider the frequency distribution of 45 observations. Class 0-10 10-20 20-30 30-40 40-50 Frequency 5 9 15 10 6 The upper limit of median class is,Statistics and Probability,Statistics,Statistics
56,219,The roots of the quadratic equation 𝑥2+x-1 = 0 are,Algebra,Quadratic Equations,Quadratic Equations
57,220,If 𝜃 = 30𝑜 then the value of 3tan𝜃 is A)1,Trigonometry,Trigonometric ratios: tan 30 degrees,Introduction to Trigonometry
58,221,The volume of a solid hemisphere is 396 7 𝑐𝑚3.The total surface area of the solid hemisphere (in sq.cm) is,Mensuration,Surface Areas and Volumes,Surface Areas and Volumes
59,222,"In a bag containing 24 balls, 4 are blue, 11 are green and the rest are white. One ball is drawn at random. The probability that drawn ball is white in colour is 𝐴) 1 6",Statistics and Probability,Probability,Probability
60,223,"The point on the x- axis nearest to the point (-4,-5) is",Coordinate Geometry,Distance from a point to the x-axis,Coordinate Geometry
61,224,Which of the following gives the middle most observation of the data?,Statistics and Probability,Median of data,Statistics
62,225,"A point on the x-axis divides the line segment joining the points A(2, -3) and B(5, 6) in the ratio 1:2. The point is",Coordinate Geometry,Areas Related to Circles,Areas Related to Circles
63,226,A card is drawn from a well shuffled deck of playing cards. The probability of getting red face card is 𝐴) 3 13,Statistics and Probability,Probability,Probability
64,227,Assertion (A): HCF of any two consecutive even natural numbers is always 2. Reason (R): Even natural numbers are divisible by 2. 1,Number Systems,Real Numbers,Real Numbers

In [117]:
mask = final_mapping["question_id"] == 225
final_mapping.loc[mask, "topic"] = "Section Formula"
final_mapping.loc[mask, "chapter_candidate"] = "Coordinate Geometry"
final_mapping.loc[mask, "topic_status"] = "Corrected candidate - verify"
final_mapping.to_csv("data/processed/class10_maths_unit_chapter_candidates.csv",index=False)
print("Question 225 corrected and saved!")

Question 225 corrected and saved!

In [118]:
skip_statuses = [
    "Not applicable - instruction",
    "Blocked - incomplete text",
    "Blocked - needs context",
    "Check source PDF/context",
    "Check original diagram",
    "Check source PDF - split OR alternatives",
    "Check source PDF - possible split question",
    "Check source PDF and figure",
    "Check source PDF - mathematical notation",
    "Check original figure",
    "Check source PDF - OCR issue",]

next_batch = final_mapping[(final_mapping["question_id"] > 227)& final_mapping["topic"].notna()
& (final_mapping["topic"].astype(str).str.strip() != "")
& (~final_mapping["topic_status"].fillna("").isin(skip_statuses))
][["question_id",
"question_text_clean",
"unit",
"topic",
"chapter_candidate",]].sort_values("question_id").head(10)
display(next_batch)

,question_id,question_text_clean,unit,topic,chapter_candidate
65,228,Assertion (A): If the radius of sector of a circle is reduced to its half and angle is doubled then the perimeter of the sector remains the same. 1 Reason (R): The length of the arc subtending angle θ at the centre of a circle of radius r = 𝛱𝑟𝜃,Mensuration,Areas Related to Circles,Areas Related to Circles
66,230,(A)Find the H.C.F and L.C.M of 480 and 720 using the Prime factorisation method. OR,Number Systems,Real Numbers,Real Numbers
67,231,"(A) Two dice are rolled together bearing numbers 4, 6, 7, 9, 11, 12. Find the probability that the product of numbers obtained is an odd number OR",Statistics and Probability,Probability,Probability
68,232,Evaluate: 2𝑠𝑖𝑛 260𝑜 − 𝑡𝑎𝑛230𝑜 𝑠𝑒𝑐2 45𝑜 2,Trigonometry,Trigonometric ratios and standard angles,Introduction to Trigonometry
69,233,"Find the point(s) on the x-axis which is at a distance of √41 units from the point (8, -5). 2",Coordinate Geometry,Distance formula,Coordinate Geometry
70,234,"Show that the points A(-5,6), B(3, 0) and C( 9, 8) are the vertices of an isosceles triangle. 2 Section C Section C consists of 6 questions of 3 marks each.",Geometry,Triangles,Triangles
71,235,"(A) In 𝛥ABC, D, E and F are midpoints of BC,CA and AB respectively. Prove that △𝐹𝐵𝐷 ∼ △ DEF and △ DEF ∼ △ ABC OR",Geometry,Coordinate Geometry,Coordinate Geometry
72,236,The sum of two numbers is 18 and the sum of their reciprocals is 9/40. Find the numbers. 3,Algebra,Quadratic equations using reciprocals,Quadratic Equations
73,237,If 𝛼 and 𝛽 are zeroes of a polynomial 6𝑥2 -5x+1 then form a quadratic polynomial whose zeroes are 𝛼2 and 𝛽2. 3,Algebra,Polynomials,Polynomials
74,238,"If cosθ + sinθ = 1 , then prove that cosθ - sinθ = ±1 3",Trigonometry,Trigonometric identities,Introduction to Trigonometry

In [119]:
# Question 228: make the topic more specific
mask = final_mapping["question_id"] == 228
final_mapping.loc[mask, "topic"] = "Arc length and perimeter of a sector"
final_mapping.loc[mask, "topic_status"] = "Candidate refined - verify"

# Question 232: flag mathematical notation for checking
final_mapping.loc[
    final_mapping["question_id"] == 232,
    "topic_status"
] = "Check source PDF - mathematical notation"

# Question 234: uses coordinates and distance calculations
mask = final_mapping["question_id"] == 234
final_mapping.loc[mask, "unit"] = "Coordinate Geometry"
final_mapping.loc[mask, "topic"] = "Distance formula applications"
final_mapping.loc[mask, "chapter_candidate"] = "Coordinate Geometry"
final_mapping.loc[mask, "topic_status"] = "Corrected candidate - verify"

# Question 235: this is a similar-triangles question
mask = final_mapping["question_id"] == 235
final_mapping.loc[mask, "topic"] = "Similarity of triangles"
final_mapping.loc[mask, "chapter_candidate"] = "Triangles"
final_mapping.loc[mask, "topic_status"] = "Corrected candidate - verify"

# Save the existing file
final_mapping.to_csv("data/processed/class10_maths_unit_chapter_candidates.csv",index=False)
print("Corrections saved successfully!")

Corrections saved successfully!

In [120]:
skip_statuses = [
    "Not applicable - instruction",
    "Blocked - incomplete text",
    "Blocked - needs context",
    "Check source PDF/context",
    "Check original diagram",
    "Check source PDF - split OR alternatives",
    "Check source PDF - possible split question",
    "Check source PDF and figure",
    "Check source PDF - mathematical notation",
    "Check original figure",
    "Check source PDF - OCR issue",
    "Check source PDF - possible split question",
]

next_batch = final_mapping[
    (final_mapping["question_id"] > 238)
    & final_mapping["topic"].notna()
    & (final_mapping["topic"].astype(str).str.strip() != "")
    & (~final_mapping["topic_status"].fillna("").isin(skip_statuses))
][
    [
        "question_id",
        "question_text_clean",
        "unit",
        "topic",
        "chapter_candidate",]].sort_values("question_id").head(10)

display(next_batch)

,question_id,question_text_clean,unit,topic,chapter_candidate
75,239,(A) The minute hand of a wall clock is 18 cm long. Find the area of the face of the clock described by the minute hand in 35 minutes. OR,Mensuration,Area of a sector,Areas Related to Circles
76,240,Prove that √3 is an irrational number. 3 Section D Section D consists of 4 questions of 5 marks each,Number Systems,Real Numbers,Real Numbers
77,241,"(A) Solve the following system of linear equations graphically: x+2y = 3, 2x-3y+8 = 0 OR",Algebra,Pair of Linear Equations,Pair of Linear Equations in Two Variables
78,242,"Prove that the lengths of tangents drawn from an external point to a circle are equal. Using above result, find the length BC of 𝛥ABC. Given that, a circle is inscribed in 𝛥ABC touching the sides AB, BC and CA at R, P and Q respectively and AB= 10 cm, AQ= 7cm ,CQ= 5cm. 5",Geometry,Tangents from an external point,Circles
79,243,"A boy whose eye level is 1.35 m from the ground, spots a balloon moving with the wind in a horizontal line at some height from the ground. The angle of elevation of the balloon from the eyes of the boy at an instant is 60𝑜. After 12 seconds, the angle of elevation reduces to 30°. If the speed of the wind is 3m/s then find the height of the balloon from the ground. (Use √3= 1.73) 5",Trigonometry,Heights and Distances,Heights and Distances
80,244,Find the mean and median of the following data: Class 85-90 90-95 95-100 100-105 105-110 110-115 frequency 15 22 20 18 20 25 OR The monthly expenditure on milk in 200 families of a Housing Society is given below Monthly Expendit ure (in Rs.) 1000- 1500 1500- 2000 2000- 2500 2500- 3000 3000- 3500 3500- 4000 4000- 4500 4500- 5000 Number of families 24 40 33 x 30 22 16 7 Find the value of x and also find the mean expenditure 5 Section E Section E consists of 3 case study based questions of 4 marks each.,Statistics and Probability,Statistics,Statistics
81,245,"Ms. Sheela visited a store near her house and found that the glass jars are arranged one above the other in a specific pattern. A B C P Q R On the top layer there are 3 jars. In the next layer there are 6 jars. In the 3rd layer from the top there are 9 jars and so on till the 8th layer. On the basis of the above situation answer the following questions. (i) Write an A.P whose terms represent the number of jars in different layers starting from top . Also, find the common difference. (ii) Is it possible to arrange 34 jars in a layer if this pattern is continued? Justify your answer. (iii)",Algebra,Arithmetic Progressions,Arithmetic Progressions
82,246,Triangle is a very popular shape used in interior designing. The picture given above shows a cabinet designed by a famous interior designer. Here the largest triangle is represented by △ ABC and smallest one with shelf is represented by △ DEF. PQ is parallel to EF. (i) Show that △ DPQ ∼ △ DEF. 1 A B C D E F P Q (ii) If DP= 50 cm and PE = 70 cm then find 𝑃𝑄 𝐸𝐹 . (iii),Geometry,Triangles,Triangles
83,247,Metallic silos are used by farmers for storing grains. Farmer Girdhar has decided to build a new metallic silo to store his harvested grains. It is in the shape of a cylinder mounted by a cone. Dimensions of the conical part of a silo is as follows: Radius of base = 1.5 m Height = 2 m Dimensions of the cylindrical part of a silo is as follows: Radius = 1.5 m Height = 7 m On the basis of the above information answer the following questions. (i) Calculate the slant height of the conical part of one silo. (ii) Find the curved surface area of the conical part of one silo. (iii)(A) Find the cost of metal sheet used to make the curved cylindrical part of 1 silo at the rate of ₹2000 per 𝑚2. OR (iii),Mensuration,Surface Areas and Volumes,Surface Areas and Volumes
90,255,"If 𝑎= 22 × 3𝑥 ,𝑏= 22 × 3 × 5,𝑐= 22 × 3 × 7 and LCM (𝑎, 𝑏, 𝑐) = 3780, then 𝑥 is equal to",Number Systems,Real Numbers,Real Numbers

In [121]:
# Question 239: check the alternative question in the source PDF
final_mapping.loc[
    final_mapping["question_id"] == 239,
    "topic_status"
] = "Check source PDF - alternative after OR"

# Question 241: check the alternative question in the source PDF
final_mapping.loc[
    final_mapping["question_id"] == 241,
    "topic_status"
] = "Check source PDF - alternative after OR"

# Question 243: refine the official chapter name
final_mapping.loc[
    final_mapping["question_id"] == 243,
    "chapter_candidate"
] = "Some Applications of Trigonometry"

final_mapping.loc[
    final_mapping["question_id"] == 243,
    "topic_status"
] = "Candidate corrected - verify"

# Question 244: two alternatives appear combined in one record
final_mapping.loc[
    final_mapping["question_id"] == 244,
    "topic_status"
] = "Check source PDF - split OR alternatives"

# Save the existing candidate file
final_mapping.to_csv(
    "data/processed/class10_maths_unit_chapter_candidates.csv",
    index=False
)

print("Updates saved successfully!")

Updates saved successfully!

In [122]:
skip_statuses = [
    "Not applicable - instruction",
    "Blocked - incomplete text",
    "Blocked - needs context",
    "Check source PDF/context",
    "Check original diagram",
    "Check source PDF - split OR alternatives",
    "Check source PDF - possible split question",
    "Check source PDF and figure",
    "Check source PDF - mathematical notation",
    "Check original figure",
    "Check source PDF - OCR issue",
    "Check source PDF - alternative after OR",
    "Check source PDF - possible split question",
    "Check source PDF and figure",
]

next_batch = final_mapping[
    (final_mapping["question_id"] > 255)
    & final_mapping["topic"].notna()
    & (final_mapping["topic"].astype(str).str.strip() != "")
    & (~final_mapping["topic_status"].fillna("").isin(skip_statuses))
][
    [
        "question_id",
        "question_text_clean",
        "unit",
        "topic",
        "chapter_candidate",
    ]
].sort_values("question_id").head(10)

display(next_batch)

,question_id,question_text_clean,unit,topic,chapter_candidate
91,256,"The shortest distance (in units) of the point (2,3) from y-axis is",Coordinate Geometry,Distance from a point to the y-axis,Coordinate Geometry
92,257,"If the lines given by 3x +2ky =2 and 2x+5y +1=0 are not parallel, then k has to be",Algebra,Conditions for parallel lines,Pair of Linear Equations in Two Variables
93,258,"A quadrilateral ABCD is drawn to circumscribe a circle. If BC=7cm, CD=4cm and AD=3cm, then the length of AB is",Geometry,Tangents in a circumscribed quadrilateral,Circles
94,259,"If 𝑠𝑒𝑐𝛳 + 𝑡𝑎𝑛𝛳 = 𝑥 ,then 𝑠𝑒𝑐𝛳 − 𝑡𝑎𝑛𝛳 will be",Trigonometry,Trigonometric identities,Introduction to Trigonometry
95,260,Which one of the following is not a quadratic equation?,Algebra,Quadratic Equations,Quadratic Equations
96,261,"Given below is the picture of the Olympic rings made by taking five congruent circles of radius 1cm each, intersecting in such a way that the chord formed by joining the point of intersection of two circles is also of length 1cm.Total area of all the dotted regions (assuming the thickness of the rings to be negligible) is",Geometry,Circles,Circles
97,262,A pair of dice is tossed. The probability of not getting the sum eight is,Statistics and Probability,Probability,Probability
99,264,"The sum of two numbers is 1215 and their HCF is 81, then the possible pairs of such numbers are",Number Systems,Real Numbers,Real Numbers
100,265,"If the area of the base of a right circular cone is 51cm2 and it's volume is 85cm2, then the height of the cone is given as",Mensuration,Surface Areas and Volumes,Surface Areas and Volumes
101,266,"If zeroes of the quadratic polynomial a𝑥2 + b𝑥 +c (a, c ≠0) are equal, then",Algebra,Polynomials,Polynomials

In [123]:
# Question 257: the question asks about lines that are NOT parallel
mask = final_mapping["question_id"] == 257
final_mapping.loc[mask, "topic"] = (
    "Conditions for parallel and non-parallel lines"
)
final_mapping.loc[mask, "topic_status"] = (
    "Topic refined - verify"
)

# Question 261: the question focuses on areas of intersecting circles
mask = final_mapping["question_id"] == 261
final_mapping.loc[mask, "unit"] = "Mensuration"
final_mapping.loc[mask, "topic"] = (
    "Area of overlapping circular regions"
)
final_mapping.loc[mask, "chapter_candidate"] = (
    "Areas Related to Circles"
)
final_mapping.loc[mask, "topic_status"] = (
    "Candidate corrected - verify original figure"
)

final_mapping.to_csv(
    "data/processed/class10_maths_unit_chapter_candidates.csv",
    index=False
)

print("Corrections saved successfully!")

Corrections saved successfully!

In [124]:
# Display the remaining questions after ID 266
remaining_df = final_mapping.loc[
    final_mapping["question_id"] > 266,
    [
        "question_id",
        "question_text_clean",
        "unit",
        "topic",
        "chapter_candidate",
        "topic_status"
    ]
].sort_values("question_id")

pd.set_option("display.max_colwidth", None)
display(remaining_df)

,question_id,question_text_clean,unit,topic,chapter_candidate,topic_status
102,267,The area (in cm2) of a sector of a circle of radius 21cm cut off by an arc of length 22cm is,Mensuration,Areas Related to Circles,Areas Related to Circles,Topic candidate - verify
103,268,"If ∆ABC ~∆DEF, AB=6cm, DE=9cm, EF=6cm and FD=12cm, then the perimeter of ∆ABC is",Geometry,Similarity of triangles and perimeter,Triangles,Topic candidate - verify
104,269,"If the probability of the letter chosen at random from the letters of the word “Mathematics” to be a vowel is 2 2𝑥+1, then 𝑥 is equal to",Statistics and Probability,Probability,Probability,Topic candidate - verify
105,270,"The points A(9,0), B(9, -6) ,C(-9,0) and D(-9,6) are the vertices of a",Coordinate Geometry,Identifying figures using coordinates,Coordinate Geometry,Check source PDF/context
106,271,"The median of a set of 9 distinct observation is 20.5. If each of the observations of a set is increased by 2,then the median of a new set",Statistics and Probability,Statistics,Statistics,Topic candidate - verify
107,272,The length of a tangent drawn to a circle of radius 9 cm from a point at a distance of 41cm from the centre of the circle is,Geometry,Circles,Circles,Topic candidate - verify
108,273,"Assertion (A): The number 5n cannot end with the digit 0, where n is a natural number Reason (R): A number ends with 0, if its prime factorization contains both 2 and 5 1",Number Systems,Real Numbers,Real Numbers,Topic candidate - verify
109,274,"Assertion (A): If cosA + cos2A=1, then sin2A + sin4A =1 Reason (R): sin2A + cos2A =1 1 (Section –",Trigonometry,Trigonometric identities: assertion and reason,Introduction to Trigonometry,Check source PDF/context
110,275,"If 𝑠𝑖𝑛(𝐴+ 𝐵) = 1 and 𝑐𝑜𝑠(𝐴 − 𝐵) = √3 2 ,0° < 𝐴, 𝐵 < 90°, find the measure of angles 𝐴 and 𝐵. 2",Trigonometry,Trigonometric ratios and angle relationships,Introduction to Trigonometry,Topic candidate - verify
111,276,"If AP and DQ are medians of triangles ABC and DEF respectively, where ∆ABC~ ∆DEF, then prove that 𝐴𝐵 𝐷𝐸 = 𝐴𝑃 𝐷𝑄 2",Statistics and Probability,Triangles,Triangles,Topic candidate - verify
112,277,(A),Not a Question,NaN,,Blocked - incomplete text
113,278,"A ∆ABC is drawn to circumscribe a circle of radius 4 cm such that the segments BD and DC are of lengths 10 cm and 8 cm respectively. Find the lengths of the sides AB and AC, if it is given that ar(∆ABC) = 90cm2 For Visually Impaired candidates: A circle is inscribed in a right-angled triangle ABC, right angled at",Geometry,Triangles,Triangles,Topic candidate - verify
114,279,"In Figure, XY and X′Y′ are two parallel tangents to a circle with centre O and another tangent AB with point of contact C intersecting XY at A and X′Y′ at",Geometry,Circles,Circles,Topic candidate - verify
115,280,"In a workshop, the number of teachers of English, Hindi and Science are 36, 60 and 84 respectively. Find the minimum number of rooms required, if in each room the same number of teachers are to be seated and all of them being of the same subject. 3",Number Systems,HCF applications,Real Numbers,Topic candidate - verify
116,281,Find the zeroes of the quadratic polynomial 2𝑥2 – (1 + 2√2) 𝑥 + √2 and verify the relationship between the zeroes and coefficents of the polynomial. 3,Algebra,Polynomials,Polynomials,Topic candidate - verify
117,282,"If 𝑠𝑖𝑛𝛳+ 𝑐𝑜𝑠𝛳 = √3 ,then prove that 𝑡𝑎𝑛𝛳 + 𝑐𝑜𝑡𝛳 = 1 OR Prove that 𝑐𝑜𝑠𝐴−𝑠𝑖𝑛𝐴+1 𝑐𝑜𝑠𝐴+𝑠𝑖𝑛𝐴−1 =cosecA + cotA 3",Trigonometry,Trigonometric identities,Introduction to Trigonometry,Check source PDF/context
118,283,"On a particular day, Vidhi and Unnati couldn’t decide on who would get to drive the car. They had one coin each and flipped their coin exactly three times. The following was agreed upon:",Statistics and Probability,Probability,Probability,Topic candidate - verify
119,284,"If Vidhi gets two heads in a row, she would drive the car",Statistics and Probability,Probability: consecutive heads,Probability,Check source PDF/context
120,285,"If Unnati gets a head immediately followed by a tail, she would drive the car. Who has greater probability to drive the car that day? Justify your answer. 3 31.(A)",Statistics and Probability,Probability,Probability,Topic candidate - verify
121,286,"A train travels at a certain average speed for a distance of 63km and then travels at a distance of 72km at an average speed of 6km/hr more than its original speed. If it takes 3 hours to complete the total journey, what is the original average speed? 5",Algebra,Quadratic equations: speed and time,Quadratic Equations,Topic candidate - verify
122,287,"Prove that if a line is drawn parallel to one side of a triangle to intersect the other two sides in distinct points, the other two sides are divided in the sameratio. Hence in ΔPQR, prove that a line ℓ intersects the sides PQ and PR of a ∆PQR at L and M respectively such that LM II QR. If PL = 5.7cm, PQ=15.2cm and MR=5.5cm, then find the length of PM (in cm) 5 34.(A)",Geometry,Triangles,Triangles,Topic candidate - verify
123,288,"In a class, the teacher asks every student to write an example of A.P. Two boys Aryan and Roshan writes the progression as −5, −2,1,4, …… and 187, 184, 181, …. respectively. Now the teacher asks his various students the following questions on progression. Help the students to find answers for the following: i. Find the sum of the common difference of two progressions. ii. Find the 34th term of progression written by Roshan. iii.",Algebra,Arithmetic Progressions,Arithmetic Progressions,Topic candidate - verify
124,289,"A group of class X students goes to picnic during winter holidays. The position of three friends Aman, Kirti and Chahat are shown by the points P, Q and R (i) Find the distance between P and R. (ii) Is Q, the midpoint of PR? Justify by finding midpoint of PR. (iii)",Coordinate Geometry,Coordinate Geometry,Coordinate Geometry,Topic candidate - verify
125,290,"India gate (formerly known as All India war memorial) is located near Karthavya path. (formerly Rajpath) at New Delhi. It stands as a memorial to 74187 soldiers of Indian Army, who gave their life in the first world war. This 42m tall structure was designed by Sir Edwin Lutyens in the style of Roman triumphal arches. A student Shreya of height 1 m visited India Gate as a part of her study tour. i. What is the angle of elevation from Shreya’s eye to the top of India Gate, if she is standing at a distance of 41m away from the India Gate? ii. If Shreya observes the angle of elevation from her eye to the top of India Gate to be 60o, then how far is the she standing from the base of the India Gate? iii.",Trigonometry,Heights and Distances,Heights and Distances,Topic candidate - verify

In [125]:
# Question 267: identify the exact topic
mask = final_mapping["question_id"] == 267
final_mapping.loc[mask, "topic"] = "Area of a sector"

# Question 272: specify the tangent topic
mask = final_mapping["question_id"] == 272
final_mapping.loc[mask, "topic"] = "Tangents to a circle"
final_mapping.loc[mask, "topic_status"] = "Candidate refined - verify"

# Question 279: incomplete text needs the original figure
final_mapping.loc[
    final_mapping["question_id"] == 279,
    "topic_status"
] = "Check original PDF and figure"

# Question 283 is the case-study introduction for questions 284-285
final_mapping.loc[
    final_mapping["question_id"] == 283,
    "topic_status"
] = "Context record - link with questions 284-285"

final_mapping.loc[
    final_mapping["question_id"].isin([284, 285]),
    "topic_status"
] = "Review with probability case-study context"

# Question 278 needs source verification
final_mapping.loc[
    final_mapping["question_id"] == 278,
    "topic_status"
] = "Check source PDF - chapter and context"

# Question 290: use the official chapter name
mask = final_mapping["question_id"] == 290
final_mapping.loc[mask, "chapter_candidate"] = (
    "Some Applications of Trigonometry"
)
final_mapping.loc[mask, "topic_status"] = "Candidate corrected - verify"

# Save the consolidated mapping file
output_path = (
    "data/processed/class10_maths_unit_chapter_candidates.csv"
)
final_mapping.to_csv(output_path, index=False)

print("Saved:", output_path)
print("\nTotal records:", len(final_mapping))
print("\nTopic candidates by status:")
print(final_mapping["topic_status"].value_counts(dropna=False))

print("\nMissing topics:",
      final_mapping["topic"].isna().sum())
print("Missing chapter candidates:",
      final_mapping["chapter_candidate"].isna().sum())

Saved: data/processed/class10_maths_unit_chapter_candidates.csv

Total records: 126

Topic candidates by status:
topic_status
Topic candidate - verify                        68
Not applicable - instruction                    14
Check source PDF/context                         7
Corrected candidate - verify                     5
Candidate corrected - verify                     4
Candidate refined - verify                       4
Blocked - incomplete text                        3
Check source PDF - split OR alternatives         2
Check source PDF - possible split question       2
Check source PDF - mathematical notation         2
Check source PDF - alternative after OR          2
Review with probability case-study context       2
Check source PDF - OCR issue                     1
Check original diagram                           1
Candidate updated; verify                        1
Check source PDF and figure                      1
Blocked - needs context                          1
Check original figure                            1
Topic refined - verify                           1
Candidate corrected - verify original figure     1
Check source PDF - chapter and context           1
Check original PDF and figure                    1
Context record - link with questions 284-285     1
Name: count, dtype: int64

Missing topics: 18
Missing chapter candidates: 0

In [126]:
missing_topic_df = final_mapping[final_mapping["topic"].isna()
    | final_mapping["topic"].astype(str).str.strip().eq("")]

display(missing_topic_df[
        [
            "question_id",
            "question_text_clean",
            "topic_status"]])

print("Records missing topics:", len(missing_topic_df))

,question_id,question_text_clean,topic_status
11,173,(sec A + tan,Blocked - incomplete text
18,180,"DIRECTION: In the question number 19 and 20, a statement of assertion",Not applicable - instruction
23,185,If tan (A +,Blocked - incomplete text
39,201,"In Section B, Questions no. 21-25 are very short answer (VSA) type questions, carrying 02 marks each.",Not applicable - instruction
40,202,"In Section C, Questions no. 26-31 are short answer (SA) type questions, carrying 03 marks each.",Not applicable - instruction
41,203,"In Section D, Questions no. 32-35 are long answer (LA) type questions, carrying 05 marks each.",Not applicable - instruction
42,204,"In Section E, Questions no. 36-38 are case study based questions carrying 4 marks each with sub parts of the values of 1, 1 and 2 marks each respectively.",Not applicable - instruction
43,206,Draw neat and clean figures wherever required.,Not applicable - instruction
44,207,Take π =22/7 wherever required if not stated.,Not applicable - instruction
45,208,Use of calculators is not allowed. Section A Section A consists of 20 questions of 1 mark each.,Not applicable - instruction
48,211,Which of the following statements is not true?,Blocked - needs context
84,248,"In Section B, Question numbers 21-25 are very short answer (VSA) type questions, carrying 02 marks each.",Not applicable - instruction
85,249,"In Section C, Question numbers 26-31 are short answer (SA) type questions, carrying 03 marks each.",Not applicable - instruction
86,250,"In Section D, Question numbers 32-35 are long answer (LA) type questions, carrying 05 marks each.",Not applicable - instruction
87,251,"In Section E, Question numbers 36-38 are case study-based questions carrying 4 marks each with sub parts of the values of 1, 1 and 2 marks each respectively.",Not applicable - instruction
88,253,Draw neat and clean figures wherever required. Take 𝜋 = 22 7 wherever required if not stated.,Not applicable - instruction
89,254,Use of calculators is not allowed. (Section,Not applicable - instruction
112,277,(A),Blocked - incomplete text

Records missing topics: 18

In [127]:
import os
print("Current folder:", os.getcwd())
file_path = os.path.abspath("data/processed/class10_maths_unit_chapter_candidates.csv")
print("Full file path:", file_path)
print("File exists:", os.path.exists(file_path))

Current folder: e:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\notebooks
Full file path: e:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\notebooks\data\processed\class10_maths_unit_chapter_candidates.csv
File exists: True

In [ ]:
from pathlib import Path
output_path = Path("../data/processed/class10_maths_unit_chapter_candidates.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)
final_mapping.to_csv(output_path, index=False)
print("Saved to:", output_path.resolve())
print("File exists:", output_path.exists())

Saved to: E:\COLLEGEPUR\WORKS\AIML work\CBSE_AI_Assessment\data\processed\class10_maths_unit_chapter_candidates.csv
File exists: True